### ISSUE TITLE
How To Switch Buffer And Tab

### ISSUE THREAD

**Issue by liangguohuan** [amix/vimrc#102]
who can tell me how can i switch Buffer And Tab ?
any keybind or command ?
i can mouse click the rightTop Tab to switch Buffer , but others, how?

**Comment by Titan-p** [comment]
Try gT or gt.

**Comment by liangguohuan** [comment]
hi , `Titan-p`

`gt` only work on tabs, i meat how to switch `tabs` and `buffers` 
it meat the windows switch.

**Comment by Titan-p** [comment]
http://vim.wikia.com/wiki/Easier_buffer_switching


It might help.


—
Titan

**Comment by liangguohuan** [comment]
@Titan-p  Thanks for passionate help.

may be you dont understand my meaning.
http://vim.wikia.com/wiki/Easier_buffer_switching is showing how to switch buffers, i knew it.

Buffers Frame And Tabs Frame Switch. The righttop button status will showing  `buffers` or `tabs` when i doing switch.

**Comment by dessalines** [comment]
It'd be super useful to add this to the tab commands. I can do a PR if you'd like.
