### ISSUE TITLE
errors when source .vimrc

### ISSUE THREAD

**Issue by roblum** [amix/vimrc#103]
getting some errors thrown when trying to source my .vimrc file

/Users/rob/.vim_runtime/vimrcs/basic.vim:1: command not found: \n
/Users/rob/.vim_runtime/vimrcs/basic.vim:3: command not found:        Amir Salihefendic\n
/Users/rob/.vim_runtime/vimrcs/basic.vim:5: command not found: \n
/Users/rob/.vim_runtime/vimrcs/basic.vim:7: no such file or directory:        5.0 - 29/05/12 15:43:36\n
/Users/rob/.vim_runtime/vimrcs/basic.vim:9: command not found:  Blog_post: \n
/Users/rob/.vim_runtime/vimrcs/basic.vim:11: command not found: \n
/Users/rob/.vim_runtime/vimrcs/basic.vim:13: command not found:        Get this config, nice color schemes and lots of plugins!\n
/Users/rob/.vim_runtime/vimrcs/basic.vim:15: command not found:        Install the awesome version from:\n
/Users/rob/.vim_runtime/vimrcs/basic.vim:17: no such file or directory:            https://github.com/amix/vimrc\n
/Users/rob/.vim_runtime/vimrcs/basic.vim:19: command not found:  Syntax_highlighted:\n
/Users/rob/.vim_runtime/vimrcs/basic.vim:21: command not found: \n
/Users/rob/.vim_runtime/vimrcs/basic.vim:23: no such file or directory:        http://amix.dk/vim/vimrc.txt\n
/Users/rob/.vim_runtime/vimrcs/basic.vim:25: command not found:  Sections:\n
/Users/rob/.vim_runtime/vimrcs/basic.vim:27: command not found:     -> VIM user interface\n
/Users/rob/.vim_runtime/vimrcs/basic.vim:29: command not found:     -> Files and backups\n
/Users/rob/.vim_runtime/vimrcs/basic.vim:31: command not found:     -> Visual mode related\n
/Users/rob/.vim_runtime/vimrcs/basic.vim:33: command not found:     -> Status line\n
/Users/rob/.vim_runtime/vimrcs/basic.vim:35: command not found:     -> vimgrep searching and cope displaying\n
/Users/rob/.vim_runtime/vimrcs/basic.vim:37: command not found:     -> Misc\n
/Users/rob/.vim_runtime/vimrcs/basic.vim:39: command not found: \n
/Users/rob/.vim_runtime/vimrcs/basic.vim:43: command not found: \n
/Users/rob/.vim_runtime/vimrcs/basic.vim:45: command not found: \n
/Users/rob/.vim_runtime/vimrcs/basic.vim:49: command not found:  Enable filetype plugins\nfiletype plugin on\nfiletype indent on\n\n
/Users/rob/.vim_runtime/vimrcs/basic.vim:56: no such file or directory: leader
/Users/rob/.vim_runtime/vimrcs/basic.vim:58: bad math expression: operand expected at `='
/Users/rob/.vim_runtime/vimrcs/basic.vim:59: ':' without '?'
/Users/rob/.vim_runtime/vimrcs/basic.vim:61: command not found:  Fast saving\nnmap <leader>w :w!<cr>\n\n
/Users/rob/.vim_runtime/vimrcs/basic.vim:65: no such file or directory:  (useful for handling the permission-denied error)\ncommand W w !sudo tee % > /dev/null\n\n\n
/Users/rob/.vim_runtime/vimrcs/basic.vim:70: command not found:  => VIM user interface\n
/Users/rob/.vim_runtime/vimrcs/basic.vim:72: no such file or directory:  Set 7 lines to the cursor - when moving vertically using j/k\nset so=7\n\n
/Users/rob/.vim_runtime/vimrcs/basic.vim:76: bad floating point constant
/Users/rob/.vim_runtime/vimrcs/basic.vim:source:78: no such file or directory: /delmenu.vim
/Users/rob/.vim_runtime/vimrcs/basic.vim:source:79: no such file or directory: /menu.vim
/Users/rob/.vim_runtime/vimrcs/basic.vim:81: command not found:  Turn on the WiLd menu\nset wildmenu\n\n
/Users/rob/.vim_runtime/vimrcs/basic.vim:85: no matches found: wildignore=*.o,*~,*.pyc
/Users/rob/.vim_runtime/vimrcs/filetypes.vim:1: permission denied: 
/Users/rob/.vim_runtime/vimrcs/filetypes.vim:2: file name too long:  => Python section\n\nlet python_highlight_all = 1\nau FileType python syn keyword pythonDecorator True None False self\n\nau BufNewFile,BufRead *.jinja set syntax=htmljinja\nau BufNewFile,BufRead *.mako set ft=mako\n\nau FileType python map <buffer> F :set foldmethod=indent<cr>\n\nau FileType python inoremap <buffer>  return \nau FileType python inoremap <buffer>  import \nau FileType python inoremap <buffer>  print \nau FileType python inoremap <buffer>  #--- PH ----------------------------------------------<esc>FP2xi\nau FileType python map <buffer> <leader>1 /class \nau FileType python map <buffer> <leader>2 /def \nau FileType python map <buffer> <leader>C ?class \nau FileType python map <buffer> <leader>D ?def \n\n\n\n
/Users/rob/.vim_runtime/vimrcs/filetypes.vim:24: file name too long: \nau FileType javascript call JavaScriptFold()\nau FileType javascript setl fen\nau FileType javascript setl nocindent\n\nau FileType javascript imap <c-t> ();<esc>hi\nau FileType javascript imap <c-a> alert();<esc>hi\n\nau FileType javascript inoremap <buffer>  return \nau FileType javascript inoremap <buffer>  //--- PH ----------------------------------------------<esc>FP2xi\n\nfunction! JavaScriptFold() \n    setl foldmethod=syntax\n    setl foldlevelstart=1\n    syn region foldBraces start=/{/ end=/}/ transparent fold keepend extend\n\n    function! FoldText()\n        return substitute(getline(v:foldstart), '{.*', '{...}', '')\n    endfunction\n    setl foldtext=FoldText()\nendfunction\n\n\n\n
/Users/rob/.vim_runtime/vimrcs/filetypes.vim:57: unmatched "
/Users/rob/.vim_runtime/vimrcs/plugins_config.vim:1: command not found: \n
/Users/rob/.vim_runtime/vimrcs/plugins_config.vim:3: no such file or directory:        This requries that you install https://github.com/amix/vimrc !\n
/Users/rob/.vim_runtime/vimrcs/plugins_config.vim:5: command not found: \n\n\n\n
/Users/rob/.vim_runtime/vimrcs/plugins_config.vim:10: permission denied: 
/Users/rob/.vim_runtime/vimrcs/plugins_config.vim:11: unknown file attribute
/Users/rob/.vim_runtime/vimrcs/extended.vim:1: command not found: \n
/Users/rob/.vim_runtime/vimrcs/extended.vim:3: no such file or directory:        This requries that you install https://github.com/amix/vimrc !\n
/Users/rob/.vim_runtime/vimrcs/extended.vim:5: command not found: \n\n\n
/Users/rob/.vim_runtime/vimrcs/extended.vim:9: command not found:  => GUI related\n
/Users/rob/.vim_runtime/vimrcs/extended.vim:11: file name too long:  Set font according to system\nif has(mac) || has(macunix)\n    set gfn=Source\ Code\ Pro:h15,Menlo:h15\nelseif has(win16) || has(win32)\n    set gfn=Source\ Code\ Pro:h12,Bitstream\ Vera\ Sans\ Mono:h11\nelseif has(linux)\n    set gfn=Source\ Code\ Pro:h12,Bitstream\ Vera\ Sans\ Mono:h11\nelseif has(unix)\n    set gfn=Monospace\ 11\nendif\n\n
/Users/rob/.vim_runtime/vimrcs/extended.vim:38: parse error near `else'
/Users/rob/.vimrc:8: command not found: ===================================================\nRUN
autocmd:10: = not found

**Comment by Josaphat** [comment]
How are you sourcing this file? The install script should do pretty much everything for you. You shouldn't run `source /path/to/vimrc`. Just execute the install script. If you've made changes to the plugins or vimrcs while vim was open, run `:so $MYVIMRC` to reload them.

**Comment by RoyLING** [comment]
`source /path/to/vimrc` --> shell command
`:so $MYVIMRC` --> vim command

I did this once ago, and there were many empty files created, see those `>` chars in this vimrc, which are interpreted as bash redirection :cry:
