### ISSUE TITLE
Hey, what's the diff between the two folders

### ISSUE THREAD

**Issue by andyqee** [amix/vimrc#108]
call pathogen#infect('~/.vim_runtime/sources_forked/{}')
 call pathogen#infect('~/.vim_runtime/sources_non_forked/{}')

**Comment by andyqee** [comment]
Does it just means the two type of plugins, based on if you have forked ? Am I right?

**Comment by amix** [comment]
@andyqee non forked are those that aren't changed (used as is). Forked are those that include my changes.
