### ISSUE TITLE
vim-airline Not showing fancy status bar

### ISSUE THREAD

**Issue by OscarOrSomething** [amix/vimrc#109]
In the screenshots the status bars look like this:
<img src="http://amix.dk/uploads/ultimate_vimrc_screenshot.png">

But i have:
<img src="http://i.imgur.com/heKOn7H.jpg">

Archlinux, vim 7.4.663

**Comment by dvrts** [comment]
@OscarOrSomething, which colorscheme do you use?

**Comment by OscarOrSomething** [comment]
Desert.

**Comment by fooozhe** [comment]
same issue

**Comment by fooozhe** [comment]
@idvoretskyi 
fixed. 
just 'set t_Co=256' in vim

**Comment by idvoretskyi** [comment]
Please, close this issue.

**Comment by OscarOrSomething** [comment]
Sorry.
