### ISSUE TITLE
Become compatible with neovim

### ISSUE THREAD

**Issue by logoff** [amix/vimrc#111]
[Neovim](http://neovim.io/) seems to be a great project. Would be possible adapt your configuration in order to be compatible with neovim?

**Comment by onkelpit** [comment]
:+1:

**Comment by amix** [comment]
It should actually already be compatible. At least I can run neovim without many issues.

**Comment by woshichuanqilz** [comment]
> It should actually already be compatible. At least I can run neovim without many issues.
Install for neovim is completely same as vim ? `my_configs.vim` files seems not loaded in my neovim, I installed awesome version, any instructions on install for nvim?

**Comment by thouger** [comment]
Although it was an issue a long time ago, I still want to answer it to avoid future people not knowing.Start `nvim` and use command

> :call mkdir(stdpath('config'), 'p')
:exe 'edit '.stdpath('config').'/init.vim'

.Then write them 

> set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
" ~/.vimrc
source ~/.vimrc

**Comment by MicaelJarniac** [comment]
The formatting on the previous comment is a bit messy, and it lacks a source, so here it is:
https://neovim.io/doc/user/nvim.html#nvim-from-vim
