### ISSUE TITLE
How to restore vim default keymap?

### ISSUE THREAD

**Issue by MichaelScofield** [amix/vimrc#119]
I'm on Mac osx 10.10.3.

In the default vim, Ctrl-F and Ctrl-B was mapped to "page down" and "page up". But after I install vimrc, there are changed. How do I restore the default behaviors?

**Comment by rajeshvaya** [comment]
What are the mappings for page down / up after installing the awesome .vimrc ? I am new to VIM and can't seem figure out the changed mapping

**Comment by onebraveman** [comment]
@MichaelScofield Hi, I also met the problem, so just use page up/down instead!

**Comment by MichaelScofield** [comment]
@onebraveman However I am using OS X ...

**Comment by wsdjeg** [comment]
i use ctrl f open unite filesearch
ctrl b open unite buffrer list

**Comment by danielarndt** [comment]
@MichaelScofield These fields are purposely used by this vimrc for other things, but you can bind this functionality back to these keys (or to any other key) by adding something like this to `~/.vim_runtime/my_configs.vim`:

`nnoremap <C-f> <PageUp>`
`nnoremap <C-b> <PageDown>`

Or, use `inoremap` if you'd like these to work in insert mode instead. tbh I'm not sure what the default behaviour is so you'll have to take it from there.

Keep in mind you will be unbinding the features that are currently bound, which I believe are very useful. You may want to consider re-binding them to something else.

**Comment by onebraveman** [comment]
@MichaelScofield  I just think as @danielarndt , overwrite the mapkey. The result shows it works.

**Comment by amix** [comment]
Thanks for resolving this guys 👍
