### ISSUE TITLE
:Ack not working

### ISSUE THREAD

**Issue by horttanainen** [amix/vimrc#120]
:Ack gives me an error message: E492: Not an editor command: Ack (whatever I try to search for)

**Comment by jingzhou123** [comment]
apt-get install ack-grep

**Comment by amix** [comment]
Please note that we have now switched to Ag.vim:
https://github.com/rking/ag.vim

**Comment by seanxwzhang** [comment]
I guess this problem re-emerged after switching back to Ack, a freshly install reports:
`E492: Not an editor command: Ack class`
