### ISSUE TITLE
errors on fresh centos vim (solved)

### ISSUE THREAD

**Issue by ghost** [amix/vimrc#129]
the awesome version install fails to work on a completely fresh CEntOS 7

git clone git://github.com/amix/vimrc.git ~/.vim_runtime
sh ~/.vim_runtime/install_awesome_vimrc.sh
--> Installed the Ultimate Vim configuration successfully! Enjoy :-)
vi .vimrc
-->
Error detected while processing /root/.vim_runtime/vimrcs/basic.vim:
line  140:
E518: Unknown option: foldcolumn=1
Error detected while processing /root/.vim_runtime/vimrcs/filetypes.vim:
line   36:
E518: Unknown option: foldmethod=syntax
line   37:
E518: Unknown option: foldlevelstart=1
line   43:
E518: Unknown option: foldtext=FoldText()
line   51:
E518: Unknown option: foldmethod=indent
line   52:
E518: Unknown option: foldlevelstart=1
Error detected while processing /root/.vimrc:
line    9:
E484: Can't open file /root/.vim_runtime/my_configs.vim
Press ENTER or type command to continue

_____

there is no syntax highlighting or auto indent. commenting out the offending lines didnt help either

running Vi IMproved 7.4.160

**Comment by BenWohl** [comment]
vi != vim

while 'vi' opens 'Vi IMproved 7.4.160' as well, this version doesnt support syntax highlighting.

sorry for this ticket

**Comment by amix** [comment]
No problems :)

**Comment by liuhuiwisdom** [comment]
How did you solved the problem?
I met the same problem now.

**Comment by forevernull** [comment]
You can modify your .bashrc to add,
```
export EDITOR=vim
alias vi="vim"
```
It works for me!

**Comment by bernardocasares** [comment]
I just installed The Ultimate Vim configuration, but now, when I try to run use vim, I get the following initial message: 

ine  364:
E10: \ should be followed by /, ? or &
line  365:
E10: \ should be followed by /, ? or &
line  366:
E10: \ should be followed by /, ? or &
line  367:
E10: \ should be followed by /, ? or &
line  368:
E10: \ should be followed by /, ? or &
line  369:
E10: \ should be followed by /, ? or &
line  370:
E10: \ should be followed by /, ? or &
line  371:
E10: \ should be followed by /, ? or &
line  372:
E10: \ should be followed by /, ? or &
line  373:
E10: \ should be followed by /, ? or &
line  374:
E10: \ should be followed by /, ? or &
line  375:
E10: \ should be followed by /, ? or &
line  376:
E10: \ should be followed by /, ? or &
line  377:
E10: \ should be followed by /, ? or &
line  378:
E10: \ should be followed by /, ? or &
line  379:
E10: \ should be followed by /, ? or &
line  380:
E10: \ should be followed by /, ? or &
line  381:
E10: \ should be followed by /, ? or &
line  382:
E10: \ should be followed by /, ? or &
line  383:
E10: \ should be followed by /, ? or &
line  384:
E10: \ should be followed by /, ? or &
line  385:
E10: \ should be followed by /, ? or &
line  386:
E10: \ should be followed by /, ? or &
line  387:
E10: \ should be followed by /, ? or &
line  388:
E10: \ should be followed by /, ? or &
line  389:
E10: \ should be followed by /, ? or &
line  390:
E10: \ should be followed by /, ? or &
line  391:
E10: \ should be followed by /, ? or &
line  392:
E10: \ should be followed by /, ? or &
line  393:
E10: \ should be followed by /, ? or &
line  394:
E10: \ should be followed by /, ? or &
line  395:
E10: \ should be followed by /, ? or &
line  396:
E10: \ should be followed by /, ? or &
line  397:
E10: \ should be followed by /, ? or &
line  398:
E10: \ should be followed by /, ? or &
line  399:
E10: \ should be followed by /, ? or &
line  400:
E10: \ should be followed by /, ? or &
line  401:
E10: \ should be followed by /, ? or &
line  402:
E10: \ should be followed by /, ? or &
line  403:
E10: \ should be followed by /, ? or &
line  404:
E10: \ should be followed by /, ? or &
line  405:
E10: \ should be followed by /, ? or &
line  406:
E10: \ should be followed by /, ? or &
line  407:
E10: \ should be followed by /, ? or &
line  408:
E10: \ should be followed by /, ? or &
line  409:
E10: \ should be followed by /, ? or &
line  410:
E10: \ should be followed by /, ? or &
line  411:
E10: \ should be followed by /, ? or &
line  412:
E10: \ should be followed by /, ? or &
line  413:
E10: \ should be followed by /, ? or &
line  414:
E10: \ should be followed by /, ? or &
line  415:
E10: \ should be followed by /, ? or &
line  416:
E10: \ should be followed by /, ? or &
line  417:
E10: \ should be followed by /, ? or &
line  418:
E10: \ should be followed by /, ? or &
line  419:
E10: \ should be followed by /, ? or &
line  420:
E10: \ should be followed by /, ? or &
line  421:
E10: \ should be followed by /, ? or &
line  422:
E10: \ should be followed by /, ? or &
line  423:
E10: \ should be followed by /, ? or &
line  424:
E10: \ should be followed by /, ? or &
line  425:
E10: \ should be followed by /, ? or &
line  426:
E10: \ should be followed by /, ? or &
line  427:
E10: \ should be followed by /, ? or &
line  428:
E10: \ should be followed by /, ? or &
line  429:
E10: \ should be followed by /, ? or &
line  430:
E10: \ should be followed by /, ? or &
line  431:
E10: \ should be followed by /, ? or &
line  432:
E10: \ should be followed by /, ? or &
line  433:
E10: \ should be followed by /, ? or &
line  434:
E10: \ should be followed by /, ? or &
line  435:
E10: \ should be followed by /, ? or &
line  436:
E10: \ should be followed by /, ? or &
line  437:
E10: \ should be followed by /, ? or &
line  438:
E10: \ should be followed by /, ? or &
line  439:
E10: \ should be followed by /, ? or &
line  440:
E10: \ should be followed by /, ? or &
line  441:
E10: \ should be followed by /, ? or &
line  442:
E10: \ should be followed by /, ? or &
line  443:
E10: \ should be followed by /, ? or &
line  444:
E10: \ should be followed by /, ? or &
line  445:
E10: \ should be followed by /, ? or &
line  446:
E10: \ should be followed by /, ? or &
line  447:
E10: \ should be followed by /, ? or &
line  448:
E10: \ should be followed by /, ? or &
line  449:
E10: \ should be followed by /, ? or &
line  450:
E10: \ should be followed by /, ? or &
line  451:
E10: \ should be followed by /, ? or &
line  452:
E10: \ should be followed by /, ? or &
line  453:
E10: \ should be followed by /, ? or &
line  454:
E10: \ should be followed by /, ? or &
line  455:
E10: \ should be followed by /, ? or &
line  456:
E10: \ should be followed by /, ? or &
line  457:
E10: \ should be followed by /, ? or &
line  458:
E10: \ should be followed by /, ? or &
line  459:
E10: \ should be followed by /, ? or &
line  460:
E10: \ should be followed by /, ? or &
line  461:
E10: \ should be followed by /, ? or &
line  462:
E10: \ should be followed by /, ? or &
line  463:
E10: \ should be followed by /, ? or &
line  464:
E10: \ should be followed by /, ? or &
line  465:
E10: \ should be followed by /, ? or &
line  466:
E10: \ should be followed by /, ? or &
line  467:
E10: \ should be followed by /, ? or &
line  468:
E10: \ should be followed by /, ? or &
line  470:
E121: Undefined variable: s:delimiterMap
E15: Invalid expression: s:delimiterMap
Error detected while processing function <SNR>22_CreateMaps:
line    8:
E116: Invalid arguments for function get(['', 'comment', '&comment', '&Plugin.&comment'],
E15: Invalid expression: get(['', 'comment', '&comment', '&Plugin.&comment'],
line    9:
E10: \ should be followed by /, ? or &
line   10:
E121: Undefined variable: menuRoot
E15: Invalid expression: 'menu <silent> ' . menuRoot . '.' . escape(a:desc, ' ')
line   13:
E121: Undefined variable: menu_command
line   15:
E121: Undefined variable: menu_command
line   26:
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
line    8:
E116: Invalid arguments for function get(['', 'comment', '&comment', '&Plugin.&comment'],
E15: Invalid expression: get(['', 'comment', '&comment', '&Plugin.&comment'],
line    9:
E10: \ should be followed by /, ? or &
line   10:
E121: Undefined variable: menuRoot
E15: Invalid expression: 'menu <silent> ' . menuRoot . '.' . escape(a:desc, ' ')
line   13:
E121: Undefined variable: menu_command
line   15:
E121: Undefined variable: menu_command
line   26:
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
line    8:
E116: Invalid arguments for function get(['', 'comment', '&comment', '&Plugin.&comment'],
E15: Invalid expression: get(['', 'comment', '&comment', '&Plugin.&comment'],
line    9:
E10: \ should be followed by /, ? or &
line   10:
E121: Undefined variable: menuRoot
E15: Invalid expression: 'menu <silent> ' . menuRoot . '.' . escape(a:desc, ' ')
line   13:
E121: Undefined variable: menu_command
line   15:
E121: Undefined variable: menu_command
line   26:
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
line    8:
E116: Invalid arguments for function get(['', 'comment', '&comment', '&Plugin.&comment'],
E15: Invalid expression: get(['', 'comment', '&comment', '&Plugin.&comment'],
line    9:
E10: \ should be followed by /, ? or &
line   10:
E121: Undefined variable: menuRoot
E15: Invalid expression: 'menu <silent> ' . menuRoot . '.' . escape(a:desc, ' ')
line   13:
E121: Undefined variable: menu_command
line   15:
E121: Undefined variable: menu_command
line   26:
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
line    8:
E116: Invalid arguments for function get(['', 'comment', '&comment', '&Plugin.&comment'],
E15: Invalid expression: get(['', 'comment', '&comment', '&Plugin.&comment'],
line    9:
E10: \ should be followed by /, ? or &
line   10:
E121: Undefined variable: menuRoot
E15: Invalid expression: 'menu <silent> ' . menuRoot . '.' . escape(a:desc, ' ')
line   13:
E121: Undefined variable: menu_command
line   15:
E121: Undefined variable: menu_command
line   26:
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
line    8:
E116: Invalid arguments for function get(['', 'comment', '&comment', '&Plugin.&comment'],
E15: Invalid expression: get(['', 'comment', '&comment', '&Plugin.&comment'],
line    9:
E10: \ should be followed by /, ? or &
line   10:
E121: Undefined variable: menuRoot
E15: Invalid expression: 'menu <silent> ' . menuRoot . '.' . escape(a:desc, ' ')
line   13:
E121: Undefined variable: menu_command
line   15:
E121: Undefined variable: menu_command
line   26:
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
line    8:
E116: Invalid arguments for function get(['', 'comment', '&comment', '&Plugin.&comment'],
E15: Invalid expression: get(['', 'comment', '&comment', '&Plugin.&comment'],
line    9:
E10: \ should be followed by /, ? or &
line   10:
E121: Undefined variable: menuRoot
E15: Invalid expression: 'menu <silent> ' . menuRoot . '.' . escape(a:desc, ' ')
line   13:
E121: Undefined variable: menu_command
line   15:
E121: Undefined variable: menu_command
line   26:
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
line    8:
E116: Invalid arguments for function get(['', 'comment', '&comment', '&Plugin.&comment'],
E15: Invalid expression: get(['', 'comment', '&comment', '&Plugin.&comment'],
line    9:
E10: \ should be followed by /, ? or &
line   10:
E121: Undefined variable: menuRoot
E15: Invalid expression: 'menu <silent> ' . menuRoot . '.' . escape(a:desc, ' ')
line   13:
E121: Undefined variable: menu_command
line   15:
E121: Undefined variable: menu_command
line   26:
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
line    8:
E116: Invalid arguments for function get(['', 'comment', '&comment', '&Plugin.&comment'],
E15: Invalid expression: get(['', 'comment', '&comment', '&Plugin.&comment'],
line    9:
E10: \ should be followed by /, ? or &
line   10:
E121: Undefined variable: menuRoot
E15: Invalid expression: 'menu <silent> ' . menuRoot . '.' . escape(a:desc, ' ')
line   13:
E121: Undefined variable: menu_command
line   15:
E121: Undefined variable: menu_command
line   26:
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
line    8:
E116: Invalid arguments for function get(['', 'comment', '&comment', '&Plugin.&comment'],
E15: Invalid expression: get(['', 'comment', '&comment', '&Plugin.&comment'],
line    9:
E10: \ should be followed by /, ? or &
line   10:
E121: Undefined variable: menuRoot
E15: Invalid expression: 'menu <silent> ' . menuRoot . '.' . escape(a:desc, ' ')
line   15:
E121: Undefined variable: menu_command
line   26:
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
line    8:
E116: Invalid arguments for function get(['', 'comment', '&comment', '&Plugin.&comment'],
E15: Invalid expression: get(['', 'comment', '&comment', '&Plugin.&comment'],
line    9:
E10: \ should be followed by /, ? or &
line   10:
E121: Undefined variable: menuRoot
E15: Invalid expression: 'menu <silent> ' . menuRoot . '.' . escape(a:desc, ' ')
line   13:
E121: Undefined variable: menu_command
line   15:
E121: Undefined variable: menu_command
line   26:
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
line    8:
E116: Invalid arguments for function get(['', 'comment', '&comment', '&Plugin.&comment'],
E15: Invalid expression: get(['', 'comment', '&comment', '&Plugin.&comment'],
line    9:
E10: \ should be followed by /, ? or &
line   10:
E121: Undefined variable: menuRoot
E15: Invalid expression: 'menu <silent> ' . menuRoot . '.' . escape(a:desc, ' ')
line   13:
E121: Undefined variable: menu_command
line   15:
E121: Undefined variable: menu_command
line   26:
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
line    8:
E116: Invalid arguments for function get(['', 'comment', '&comment', '&Plugin.&comment'],
E15: Invalid expression: get(['', 'comment', '&comment', '&Plugin.&comment'],
line    9:
E10: \ should be followed by /, ? or &
line   10:
E121: Undefined variable: menuRoot
E15: Invalid expression: 'menu <silent> ' . menuRoot . '.' . escape(a:desc, ' ')
line   15:
E121: Undefined variable: menu_command
line   26:
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
line    8:
E116: Invalid arguments for function get(['', 'comment', '&comment', '&Plugin.&comment'],
E15: Invalid expression: get(['', 'comment', '&comment', '&Plugin.&comment'],
line    9:
E10: \ should be followed by /, ? or &
line   10:
E121: Undefined variable: menuRoot
E15: Invalid expression: 'menu <silent> ' . menuRoot . '.' . escape(a:desc, ' ')
line   13:
E121: Undefined variable: menu_command
line   15:
E121: Undefined variable: menu_command
line   26:
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
line    8:
E116: Invalid arguments for function get(['', 'comment', '&comment', '&Plugin.&comment'],
E15: Invalid expression: get(['', 'comment', '&comment', '&Plugin.&comment'],
line    9:
E10: \ should be followed by /, ? or &
line   10:
E121: Undefined variable: menuRoot
E15: Invalid expression: 'menu <silent> ' . menuRoot . '.' . escape(a:desc, ' ')
line   13:
E121: Undefined variable: menu_command
line   15:
E121: Undefined variable: menu_command
line   26:
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
line    8:
E116: Invalid arguments for function get(['', 'comment', '&comment', '&Plugin.&comment'],
E15: Invalid expression: get(['', 'comment', '&comment', '&Plugin.&comment'],
line    9:
E10: \ should be followed by /, ? or &
line   10:
E121: Undefined variable: menuRoot
E15: Invalid expression: 'menu <silent> ' . menuRoot . '.' . escape(a:desc, ' ')
line   15:
E121: Undefined variable: menu_command
line   26:
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
line    8:
E116: Invalid arguments for function get(['', 'comment', '&comment', '&Plugin.&comment'],
E15: Invalid expression: get(['', 'comment', '&comment', '&Plugin.&comment'],
line    9:
E10: \ should be followed by /, ? or &
line   10:
E121: Undefined variable: menuRoot
E15: Invalid expression: 'menu <silent> ' . menuRoot . '.' . escape(a:desc, ' ')
line   15:
E121: Undefined variable: menu_command
line   26:
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
line    8:
E116: Invalid arguments for function get(['', 'comment', '&comment', '&Plugin.&comment'],
E15: Invalid expression: get(['', 'comment', '&comment', '&Plugin.&comment'],
line    9:
E10: \ should be followed by /, ? or &
line   10:
E121: Undefined variable: menuRoot
E15: Invalid expression: 'menu <silent> ' . menuRoot . '.' . escape(a:desc, ' ')
line   15:
E121: Undefined variable: menu_command
line   26:
E121: Undefined variable: menu_command
E15: Invalid expression: mode . menu_command
Error detected while processing function <SNR>22_SetUpForNewFiletype:
line   17:
E121: Undefined variable: s:delimiterMap
E116: Invalid arguments for function has_key(s:delimiterMap, ft)
E15: Invalid expression: has_key(s:delimiterMap, ft)

Any advice?

**Comment by paulmaunders** [comment]
I was getting the same errors when running `crontab -e` but applying @forevernull's suggestions to .bashrc fixed them.
