### ISSUE TITLE
After typing $1, it's replaced with ()

### ISSUE THREAD

**Issue by willfaught** [amix/vimrc#130]
Huh?

**Comment by lioman** [comment]
I think this is absolut normal $2 will return [] Q3 stands for {}. 

It  is a short cut.
If you want to type $ ARROWRIGHT 1 $1 is not replaed

**Comment by diogovk** [comment]
As a shell scripter I also dislike very much this behaviour.
I just uncomment the bindings in .vim_runtime/vimrcs/extended.vim

**Comment by willfaught** [comment]
Thanks, I commented it out.
