### ISSUE TITLE
Fish Redirection error

### ISSUE THREAD

**Issue by lordlycastle** [amix/vimrc#132]
I just installed this by following the instructions. Now open file in Vim, it shows the following:
```
syntastic: error: your shell /usr/local/bin/fish can't handle traditional UNIX syntax for redirections
Press ENTER or type command to continue
```
After pressing Enter, vim seems to be working fine, thought I would like to know why this is caused and how to fix it.

**Comment by lxduan** [comment]
Having the same issue here on my MacBook Pro.

**Comment by mikaoj** [comment]
put this in your .vimrc
```shell
set shell=/bin/bash
```

**Comment by lordlycastle** [comment]
Using @mikaoj's suggestion seems to work, thanks!

**Comment by danielcompton** [comment]
Relates to https://github.com/scrooloose/syntastic/issues/803
