### ISSUE TITLE
Can Number Line setting be included as well?

### ISSUE THREAD

**Issue by ArturGrigio** [amix/vimrc#143]
Number Line is one of the most used features (IMHO), I was surprised that it wasn't there. If you don't have a specific reason for NOT including it in the Basic Version, would you please include it?
````javascript
    set nu
````
Thank you BTW, you have no clue how much time this saves me :)

**Comment by smbell** [comment]
Just add it to the my_configs.vim file.

**Comment by ArturGrigio** [comment]
@smbell Thank you
