### ISSUE TITLE
Can't enable syntastic java checkstyle checker.

### ISSUE THREAD

**Issue by smbell** [amix/vimrc#147]
I can't seem to enable the java checkstyle checker in syntastic.
This is on a Mac OS X 10.11.2
Using the latest version of the awesome script.
Syntastic version 3.7.0-69
Vim 703, Darwin

I've downloaded the checkstyle 'all' jar. I tried putting it in `/usr/bin/local` which is in the syntastic path.
I tried editing the `syntax_checkers/java/checkstyle.vim` file to set `g:syntastic_java_checkstyle_classpath` to the full path to the jar file.
I tried creating a `sun_checks.xml` configuration file and tried it both in `/usr/bin/local` and with a full path in the checkstyle.vim file.
I tried editing the `plugin/syntastic/registry.vim` file changing the value on line 48 from `['javac']` to `['javac', 'checkstyle']`
I tried adding a few `let g:a_few_debug_variables = 1` in the `SyntaxCheckers_java_checkstyle_IsAvailable()` function of the `syntax_checkers/java/checkstyle.vim` file to see what might be happening and it appeared that none of my debug variables were ever set, so it seems as if that function was never called.
I'm not sure what else to try or what could be wrong.

The javac checker has been working great out of the box. During all the above using `:SyntasticInfo` while in a .java file only ever showed the `Available checker: javac`.

If you have the time to help me with this I'd really appreciate it.

**Comment by amix** [comment]
Please post this in syntastic repo
