### ISSUE TITLE
Is there any auto complete plugins?

### ISSUE THREAD

**Issue by YUFENGWANG** [amix/vimrc#150]
I've seen the included plugins , but I cannot find some auto complete plugins , don't you use it? or you think It's unnecessary to use it?

**Comment by Tiande** [comment]
when you have a word you wanna auto complete, 
just type some letters of it and use ```<C-n> <C-p> ``` to complete it.

for example:
```
int OneParameter,OtherParameter;
# Type o/one/other ,use <C-n> <C-p> to select what you want.
# Not case sensitive
o...
one...
other...
```

**Comment by YUFENGWANG** [comment]
so what's the map key of moving downwards half screen <c-d>, and upwards <c-u> ....
I'm new to vim ..is it located in vimrcs?

**Comment by Tiande** [comment]
moving up/downwards half screen: ```<C-d> <C-u>```

如果你是 VIM 刚入门，基础操作学会之前，还是不要着急搞配置文件的好，这里重新映射了不少按键。
[《VIM简明教程》](http://pan.baidu.com/s/1jG3rFPs)，过一遍吧

**Comment by amix** [comment]
Check out https://github.com/Valloric/YouCompleteMe
