### ISSUE TITLE
error happened when vim met git

### ISSUE THREAD

**Issue by chenqiangzhishen** [amix/vimrc#152]
When we use git, such as `git commit --amend` to edit, it will popup error for the vim as belows:
```
Error detected while processing /root/.vim_runtime/vimrcs/basic.vim:
line  140:
E518: Unknown option: foldcolumn=1
Error detected while processing /root/.vim_runtime/vimrcs/filetypes.vim:
line   36:
E518: Unknown option: foldmethod=syntax
line   37:
E518: Unknown option: foldlevelstart=1
line   43:
E518: Unknown option: foldtext=FoldText()
line   51:
E518: Unknown option: foldmethod=indent
line   52:
E518: Unknown option: foldlevelstart=1

```

**Comment by khatchad** [comment]
What do you mean? You issue that command inside of vim?

**Comment by chenqiangzhishen** [comment]
I find the root cause now, it's not related to git, but to vi
If I use 'vi' to edit some file, above errors will occur. 'vim' works OK.
As git will use vi by default, so I met the issue.

actually, we could edit the ~/.bashrc  to add `alias vi='vim'` to avoid the issue.
