### ISSUE TITLE
system clipboard

### ISSUE THREAD

**Issue by YUFENGWANG** [amix/vimrc#159]
how to paste the content in system clipboard that i copied with ctrl+v in vim?

**Comment by mutantkeyboard** [comment]
@YUFENGWANG do you mean CTRL-C? Since CTRL+V is actually the command for pasting stuff. 
When you open VIM, you need to press letter I (capital i that stands for insert), and then do a CTRL-V.

**Comment by chenqiangzhishen** [comment]
see [!149](https://github.com/amix/vimrc/issues/149)
