### ISSUE TITLE
it asks what snippet to use

### ISSUE THREAD

**Issue by quake004** [amix/vimrc#164]
I added a snippet to the file /home/user/.vim_runtime/sources_non_forked/vim-snippets/UltiSnips/c.snippets which is
snippet inc "#include ..."
#include <${1:stdio.h}>
endsnippet

and other to /home/user/.vim_runtime/sources_non_forked/vim-snippets/UltiSnips/cpp.snippets
snippet inc "#include ..."
#include <${1:iostream}>
endsnippet

when I type inc <ctrl-j> I want it to write one of those based on the file type I'm editing but it asks me to chose between c.snippets and cpp.snippets. How can I fix this?

**Comment by amix** [comment]
Please ask this in vim-snippets repo
