### ISSUE TITLE
README.md blog links

### ISSUE THREAD

**Issue by sacres** [amix/vimrc#167]
Hi Amir,

Nice work here, thanks! 
BTW, the links:

    Vim: Annotate strings with gettext (the macro way)
    vimgrep: Searching through multiple file extensions
    Filtering through vimgrep results using regular expressions
    PeepOpen - File auto completion for Mac editors
    Vim 7.3: Persistent undo and encryption!
    Vim tips: Visual Search
    Folding in Vim
    Zen room for Vim: Focusing only on the essential

.. on the README.md page don't actually link to those articles anymore.

**Comment by so0k** [comment]
Yes, all links broke since blog was moved to medium it seems :(

**Comment by so0k** [comment]
this may help  -https://web.archive.org/web/20121125084628/http://amix.dk/blog/label/5#VIM-Editor

**Comment by amix** [comment]
Fixed, thanks guys! 👍
