### ISSUE TITLE
Problem with using with mvim

### ISSUE THREAD

**Issue by nwebz** [amix/vimrc#171]
I installed this on OSX Yosemite (10.10.5) and every time I enter the full-screen mode with mvim I have a problem that occurs when scrolling down and then back up to the top of the file. The display gets stuck on the top-most line and repeats it in the window. It doesn't actually write to the file, but it is enough to make the application unusable. Does anyone know what the cause is? 
![screenshot 2016-03-06 13 53 36](https://cloud.githubusercontent.com/assets/12226550/13556321/c344dd28-e3a4-11e5-9b48-59b7cd49efa2.png)

**Comment by amix** [comment]
This isn't related to my vimrc, but your vim installation :)

Try to update to El Captain and latest MacVim.
