### ISSUE TITLE
Issues creating git commits

### ISSUE THREAD

**Issue by joubin** [amix/vimrc#172]
`git commit -a`

always errors out because vim closes with an error

**Comment by DannyvdSluijs** [comment]
Same here, excluding vim from the process (git commit -m "Commit message here" works fine.

**Comment by DannyvdSluijs** [comment]
@joubin See https://github.com/amix/vimrc/issues/88#issuecomment-73794686 on how to resolve.

**Comment by amix** [comment]
Not something I can reproduce

**Comment by alphaCTzo7G** [comment]
This is not a problem with the `vimrc`. See this: https://stackoverflow.com/a/48481001/4752883
