### ISSUE TITLE
\ adds spaces on first hit in insert mode

### ISSUE THREAD

**Issue by konsumer** [amix/vimrc#173]
Maybe this is because I am running ssh in powershell, not sure:

![vimprob](https://cloud.githubusercontent.com/assets/83857/13713793/ac94034a-e77f-11e5-8104-7b39c37b903b.gif)

**Comment by konsumer** [comment]
It's something in basic, but I couldn't find it.

**Comment by amix** [comment]
I don't think this is an issue with my vimrc, but your setup ;-)

**Comment by konsumer** [comment]
Yeah, seems better in conemu.
