### ISSUE TITLE
issue with sphinx index.rst file

### ISSUE THREAD

**Issue by zh0uquan** [amix/vimrc#176]
After I edited the index.rst file in the sphinx folder,
I have errors as follows:
```
index.rst|11 error| Unknown directive type "toctree".                                                                                                                            
index.rst|19 error| Unknown interpreted text role "ref".
index.rst|20 error| Unknown interpreted text role "ref".
index.rst|21 error| Unknown interpreted text role "ref".
```
It seems to be the  `:SyntasticCheck rst2pseudoxml (rst)` which raise this error, and I couldn't exit it, except by `ctrl-d`, and then `:q` .

**Comment by amix** [comment]
Please report to https://github.com/scrooloose/syntastic
