### ISSUE TITLE
Weird characters in go files

### ISSUE THREAD

**Issue by sevagh** [amix/vimrc#177]
![vimrc-bug](https://cloud.githubusercontent.com/assets/8574092/14065515/f172c38e-f3fa-11e5-9440-05cd8900bbed.png)

I get this string of characters on my gofiles sometimes (ever since pulling the latest March commits). You can't navigate to the string with your cursor, its just a visual deformity.

Any ideas what could be causing it?

**Comment by amix** [comment]
Very likely it was a bug in https://github.com/fatih/vim-go
