### ISSUE TITLE
Still seeing the default status bar

### ISSUE THREAD

**Issue by udiboy1209** [amix/vimrc#183]
![screenshot from 2016-04-06 12 58 27](https://cloud.githubusercontent.com/assets/7384411/14309023/6b010fd6-fbf7-11e5-80f8-c8cee3e2448c.png)

Why is the `--INSERT--` still coming at the last line. It should be gone completely. 

PS. It could be a bug with upstream `vim-airline` but I can't see it reported.

**Comment by amix** [comment]
Not something I can reproduce.
