### ISSUE TITLE
syntastic error

### ISSUE THREAD

**Issue by arturojosejr** [amix/vimrc#185]
I get this while saving a c++ file. Is there a version of this vimrc without bugs?

Error detected while processing function <SNR>63_BufWritePostHook[3]..<SNR>63_UpdateErrors[15]..<SNR>63_CacheErrors[35]..276
[1]..275[23]..SyntaxCheckers_cpp_gcc_GetLocList[1]..syntastic#c#GetLocList[2]..<SNR>146__get_cflags[13]..<SNR>146__get_check
er_var:                                                                                                                     
line    5:                                                                                                                  
E121: Undefined variable: g                                                                                                 
E15: Invalid expression: {a:scope}:syntastic_{a:filetype}_{a:name}                                                          
Error detected while processing function <SNR>63_BufWritePostHook[3]..<SNR>63_UpdateErrors[15]..<SNR>63_CacheErrors:        
line   35:                                                                                                                  
E170: Missing :endfor                                                                                                       
Error detected while processing function <SNR>63_BufWritePostHook[3]..<SNR>63_UpdateErrors:                                 
line   15:                                                                                                                  
E171: Missing :endif

**Comment by amix** [comment]
Seems to be a `syntastic` bug. Please report it in the syntastic plugin issues: https://github.com/scrooloose/syntastic

If you still have issues, you can try to disable syntatic.
