### ISSUE TITLE
my_configs.vim file not loading

### ISSUE THREAD

**Issue by jwgoes** [amix/vimrc#186]
This may be pretty basic (new to Vim), but the my_configs.vim file I created (full path: ~/.vim_runtime/my_configs.vim) is not being incorporated into the .vimrc file.

Specifically I put in the my_configs.vim file the command

`inoremap kj <ESC>`

and seperately

`imap kj <ESC>`

saved the file and saw no effect. I restarted the computer and even tried `\e` and typing jk never brought me back into normal. To test that there was no problem with the command itself, I edited the .vimrc file to include the command, saved, and it worked like a charm.

Not sure if this is an error on my side or with a recent version of the program. Help would be greatly appreciated! You have a great .vimrc style.

**Comment by Tiande** [comment]
make sure your .vimrc file has this content:
```
try
source ~/.vim_runtime/my_configs.vim
catch
endtry
```

**Comment by jwgoes** [comment]
Thanks, that did it.

**Comment by iamrahulroy** [comment]
@Tiande Mine has the same content, but still no luck. After modifying `~/.vim_runtime/my_configs.vim` I'm using this command to source my_configs `sh ~/.vim_runtime/install_basic_vimrc.sh`. Am I missing something? Can you point me in the right direction?

**Comment by Tiande** [comment]
@iamrahulroy  
The command `sh ~/.vim_runtime/install_basic_vimrc.sh` can't source `my_configs.vim`.

Just make sure your `.vimrc` file has this content:
```
source ~/.vim_runtime/vimrcs/basic.vim 
source ~/.vim_runtime/my_configs.vim
```
It will work for you.
