### ISSUE TITLE
Advice Tracking Down Issue ...

### ISSUE THREAD

**Issue by GaryFurash** [amix/vimrc#188]
Hi. I added two packages as described in the readme

> git clone https://github.com/MattesGroeger/vim-bookmarks ~/.vim_runtime/sources_non_forked/vim-bookmarks
> git clone https://github.com/Shougo/neocomplete.vim ~/.vim_runtime/sources_non_forked/neocomplete
> 

However, they don't seem to be sourced (it's as if vim/gvim isn't seeing them). Do I need to do something else?

**Comment by amix** [comment]
Very strange. That should do the trick 😕

Can't reproduce this

**Comment by amix** [comment]
If you have more issues please report this in https://github.com/tpope/vim-pathogen
