### ISSUE TITLE
bnext mapping is clashing with coffescript syntax check

### ISSUE THREAD

**Issue by dre-hh** [amix/vimrc#192]
In the following pull request 2 buffer mapping were introduced
https://github.com/amix/vimrc/pull/136/files

Unfortiantely there is already an <leader>l mapping which overrides the buffer mappings
https://github.com/amix/vimrc/blob/5f6aa8fe095c962ebb094101767358fb81ef3383/vimrcs/plugins_config.vim#L143

When i press <leader>l on a random non-coffee file it will just create a new buffer with same content.

**Comment by Tiande** [comment]
I had this conflict even in .coffee files.
It's easy to solve if we just remapping it.

**Comment by amix** [comment]
Remapped to `<leader>c`

Thank you!
