### ISSUE TITLE
The problem when vim used in cygwin

### ISSUE THREAD

**Issue by Jleafy** [amix/vimrc#197]
hello!
     First, thank you for your project. I love it very much. But there is a bug when I use it in cygwin on Windows -- the Chinese characters garbled. When I commented the " set encoding=utf-8" in the file "basic.vim" and added the code:
  " set fileencoding=utf-8 " 
  "set fileencodings=ucs-bom,utf-8,cp936,gb18030,gbk,gb2312,big5,euc-jp,euc-kr,latin1" 
, a bug came out. It showed like this:
" 处理 /home/Jleafy/.vim_runtime/sources_non_forked/nerdtree/plugin/NERD_tree.vim 时发生错误:
第   71 行:
E114: 缺少引号: "鈻▒")
E116: Invalid arguments for function <SNR>37_initVariable
请按 ENTER 或其它命令继续
 "
So I dont't know how to solve this problem, can you give me some advice?

Thank you!

**Comment by Tiande** [comment]
Try to set Cygwin's character encoding to 'gb2312'.
