### ISSUE TITLE
Show line numbers

### ISSUE THREAD

**Issue by Chofoteddy** [amix/vimrc#200]
I know that this requires putting in vim configuration file, the command:

    set number

But this becomes tedious after installing on multiple servers require. It is strange that this very useful application has not enabled this option, it is indispensable.

Please consider adding it. It is no coincidence that several people propose this change.

Reference:

- [Can Number Line setting be included as well? #143](https://github.com/amix/vimrc/issues/143)
- [turn on line numbers and column by default #131](https://github.com/amix/vimrc/pull/131)
- [show line number #105](https://github.com/amix/vimrc/pull/105)
- [Show line number #104](https://github.com/amix/vimrc/pull/104)
- [Show line numbers #45](https://github.com/amix/vimrc/pull/45)
- [Added showing line number feture(set nu) under =>General in vimrcs/basic... #41](https://github.com/amix/vimrc/pull/41)
- [Add Line Numbers #18](https://github.com/amix/vimrc/issues/18)

**Comment by Faryshta** [comment]
How about a github poll? would @amix be ok by making 2 comments here (or somewhere else) and letting users vote using git reactions?

**Comment by Faryshta** [comment]
Reactions **in favor** of adding

`set number`

by default.

**Comment by Faryshta** [comment]
Reactions **against** adding

`set number`

by default.

**Comment by carlosvite07** [comment]
You should consider show line numbers, just like others had tell you.

**Comment by antoniodemora** [comment]
I think @amix  has made his point arguing showing all the numbers at the time is a distraction. Beside, IMHO it push the user to get involved in his vim configuration by asking him to add the setting to his my_configs.vim

**Comment by amix** [comment]
You are welcome to create a fork where you have this set or update `my_configs.vim`. Reasons I dislike line numbers:

* I find it distracting, especially since you have the line number at bottom right
* You can also use `101gg` to quickly jump to line 101
