### ISSUE TITLE
issue with installing plugging "YouCompleteMe"

### ISSUE THREAD

**Issue by oldregan** [amix/vimrc#201]
I used 
"git clone https://github.com/Valloric/YouCompleteMe.git sources_non_forked/YouCompleteMe"
command to install the YouCompleteMe plugging. However, when I launch the vim, I got error messages like below: "YouCompleteMe unavailable: No module named ycmd".
I tried to install the package ycmd by the same method. However I still got the same message.
Can anyone help?

**Comment by antoniodemora** [comment]
I think you are missunderstanding YCM.
check the [`installation guide`](https://github.com/Valloric/YouCompleteMe#full-installation-guide) for YCM

**Comment by amix** [comment]
Please post this for YouCompleteMe.

**Comment by kermitbu** [comment]
@oldregan I meet the same issue. could you tell me how to fix it?

**Comment by asleea** [comment]
git submodule update --init --recursive in cloned git dir.

**Comment by deodesumitsingh** [comment]
If you are just cloning the repository, it wont install submodules(P.S. :- if you are not using vundle, I am using pathogen).
Then in cloned directory you just need to run "git submodule update --init --recursive" it will do the magic that you require.
