### ISSUE TITLE
:shell and Umlauts

### ISSUE THREAD

**Issue by criztovyl** [amix/vimrc#204]
Hello,

with this `.vimrc` enabled I can't use Umlauts like äöü when using `:shell`.
For ä nothing happens and ö fires `ALT+-` (alt and dash).
I have no issue when disabling the `vimrc`.

[vim --version](http://pastebin.com/uM2Eh73b)

Can report more details if required :)

Thx.

**Comment by amix** [comment]
Not something I can reproduce (maybe it's one of the plugins that does this). Ref:
http://cl.ly/2x060w2w0u0q

**Comment by criztovyl** [comment]
Hello,

`:ü` works for me too, but when I've launched a shell via `:shell` (in
my case Bash), there ö does not work.

Am Sonntag, den 03.07.2016, 04:51 -0700 schrieb Amir Salihefendic:
> Closed #204.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
-- 

Visit me:
https://twitter.com/criztovyl
https://criztovyl.joinout.de
https://github.com/criztovyl

**Comment by criztovyl** [comment]
https://joinout.de/out-7.ogv

**Comment by amix** [comment]
@criztovyl You might want to check which shell vim is using.

You can redefine the shell like so:
```
set shell=zsh\ -i
```

**Comment by criztovyl** [comment]
It's bash, `:set shell` tells `shell=/bin/bash`. But strange thing is, with `:shell` with `sh -i` umlauts work.

**Comment by criztovyl** [comment]
So I did a some back-tracking. The problem seems to be in [`basic.vim`, L76](https://github.com/amix/vimrc/blob/master/vimrcs/basic.vim#L76):

    lang $LANG='en'

When I comment it out, umlauts work again :)
