### ISSUE TITLE
[REQUEST] vimrc match with powerline

### ISSUE THREAD

**Issue by atendedor-de-boludos** [amix/vimrc#208]
vimrc match with powerline
[ http://askubuntu.com/questions/283908/how-can-i-install-and-use-powerline-plugin
](url)

With extended vimrc
![Imgur](http://i.imgur.com/Pd4cm6v.png)
With my own vimrc
![Imgur](http://i.imgur.com/WjwjHR7.png)

How do I make it compatible with my setup powerline?

Sorry for my bad english

**Comment by amix** [comment]
I don't know :)

But I do't recommend powerline (had used it before and it had perfomance issues and leaks).

**Comment by amix** [comment]
For help on the powerline config please ask them.
