### ISSUE TITLE
Multiple cursors doesn't work

### ISSUE THREAD

**Issue by ashishtibrewal** [amix/vimrc#211]
Ctrl-S doesn't seem to work for the [vim-multiple-cursors](https://github.com/amix/vimrc#included-plugins) plugin. I tried figuring out why it wasn't working but wasn't able to find a solution. Any help would be much appreciated.

Thanks. :)

Ashish

**Comment by tdehaeze** [comment]
Same for me

**Comment by Tiande** [comment]
I remapping it to default in "my_configs.vim" file, and it works.

```
" multi_cursor
" Default mapping
let g:multi_cursor_next_key='<C-n>'
let g:multi_cursor_prev_key='<C-p>'
let g:multi_cursor_skip_key='<C-x>'
let g:multi_cursor_quit_key='<Esc>'
let g:multi_cursor_start_key='<C-n>'
let g:multi_cursor_start_word_key='g<C-n>'
```

**Comment by amix** [comment]
Not something I can reproduce
