### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by amilajack** [amix/vimrc#213]
When installing on linux, I get a bunch of syntax errors:

ex:
```
E10: \ should be followed by /, ? or &
line  120:
```

Is there a solution for this?

**Comment by rodobodolfo** [comment]
I just got the same error and apparently my system was missing vim-runtime .

`
 sudo apt-get install vim
`

It update vim and vim-runtime packages That fixed all the errors for me.

**Comment by amilajack** [comment]
I see. I'll give that a go.

**Comment by amilajack** [comment]
@rodobodolfo Works like a charm. Thanks!

**Comment by amilajack** [comment]
Previously, I had vim installed as `vi`, not `vim`. `alias vi=vim` should elegantly fix that issue.
