### ISSUE TITLE
Theme is abnormal when use vim in tmux.

### ISSUE THREAD

**Issue by lipanXJ** [amix/vimrc#215]
![screenshot_20160723_095957](https://cloud.githubusercontent.com/assets/15389690/17075141/1823be88-50bd-11e6-8159-f7da079d462a.png)
![screenshot_20160723_095858](https://cloud.githubusercontent.com/assets/15389690/17075142/1ae4312a-50bd-11e6-9a5e-379dca1490b4.png)

As you can see,theme is abnormal in the first picture,only a small code could solve it,why not consider add it?

Code:
`if exists('$TMUX')
  set term=screen-256color
endif`

**Comment by nerd010** [comment]
Hi,How can I add wakaTime in vim?
