### ISSUE TITLE
Awesome vim does not support C++11 syntax

### ISSUE THREAD

**Issue by reminisce** [amix/vimrc#216]
The following errors would be falsely reported in vim opening C++ code files:

1. vector<int> nums = {1, 2};
non-aggregate type 'vector<int>' cannot be initialized with an initializer list

2. vector<vector<int>> matrix;
a space is required between consecutive right angle brackets (use '> >')

**Comment by amix** [comment]
I am not a C++ programmer. You are welcome to provide a pull request with proper support 👍
