### ISSUE TITLE
i get some error where i user crontab -e as root 

### ISSUE THREAD

**Issue by luohoufu** [amix/vimrc#220]
sh ~/.vim_runtime/install_awesome_vimrc.sh

#crontab -e
Error detected while processing /root/.vim_runtime/vimrcs/basic.vim:
line  135:
E518: Unknown option: foldcolumn=1
Error detected while processing /root/.vim_runtime/vimrcs/filetypes.vim:
line   36:
E518: Unknown option: foldmethod=syntax
line   37:
E518: Unknown option: foldlevelstart=1
line   43:
E518: Unknown option: foldtext=FoldText()
line   51:
E518: Unknown option: foldmethod=indent
line   52:
E518: Unknown option: foldlevelstart=1
Error detected while processing /root/.vim_runtime/vimrcs/extended.vim:
line   38:
E185: Cannot find color scheme 'peaksea'
Error detected while processing /root/.vimrc:
line    9:
E484: Can't open file /root/.vim_runtime/my_configs.vim
Press ENTER or type command to continue

**Comment by amix** [comment]
Most likely it's using an outdated `vi` instead of `vim`. Please check and ensure that cron is using vim
