### ISSUE TITLE
Indents when using #

### ISSUE THREAD

**Issue by cynicXer** [amix/vimrc#221]
The hash symbol (#) is always inserted at the left-most column of a file, which can cause some headaches when hacking out a Python script.  I turned off smartindent (si) and set cindent instead, following the instructions here: http://vim.wikia.com/wiki/Restoring_indent_after_typing_hash.

set ci
set cinkeys-=0#
set indentkeys-=0#

This seemed to fix the issue.

**Comment by amix** [comment]
Nice one @cynicXer. Merged this in 👏
