### ISSUE TITLE
What about auto adding file header?

### ISSUE THREAD

**Issue by eromoe** [amix/vimrc#223]
It is common to add header like :

file header by ext
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
```
auther info
```
# @Author: mithril
# @Date:   2015-12-08 13:17:04
# @Last Modified by:   mithril
# @Last Modified time: 2015-12-08 13:17:04
```

It would be much more convenient if you provide such function.

Accutally I rarely use command line and mainlly use a ide, I just try to learn how to use vim and try to find a substitude of sublime in command mode.

**Comment by amix** [comment]
@eromoe you could probably setup vim-snippets to do this trick, ref:
https://github.com/honza/vim-snippets
