### ISSUE TITLE
Cannot see tabs when using the list and listchars options

### ISSUE THREAD

**Issue by junmin** [amix/vimrc#224]
Hello, I need to check some error related to tabs/space in VIM, I am trying to use list and listchars options, but it appears not working with tabs, only can see EOL $ in blue, please help. thank you.

http://vim.wikia.com/wiki/Highlight_unwanted_spaces#Using_the_list_and_listchars_options

**Comment by amix** [comment]
Please ask this in a Vim related mailing list -- not very related to this vimrc
