### ISSUE TITLE
installation issues [easy]

### ISSUE THREAD

**Issue by hunt-son** [amix/vimrc#228]
I tried to install this out of the box and got a whole bunch of errors. I was hoping for some clarity on how to resolve them. Basically, they all start with "Sorry, this command is not available in this version." So I did :version and this is my output:

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 16 2016 10:50:38)
Included patches: 1-1689
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Small version without GUI.  Features included (+) or not (-):
+acl             -cursorshape     +iconv           -mouse_netterm   -rightleft       -user_commands
-arabic          -dialog          -insert_expand   -mouse_sgr       -ruby            +vertsplit
-autocmd         -diff            -job             -mouse_sysmouse  -scrollbind      -virtualedit
-balloon_eval    -digraphs        +jumplist        -mouse_urxvt     -signs           +visual
-browse          -dnd             -keymap          -mouse_xterm     -smartindent     -visualextra
+builtin_terms   -ebcdic          -langmap         +multi_byte      -startuptime     -viminfo
-byte_offset     -emacs_tags      -libcall         -multi_lang      -statusline      -vreplace
-channel         -eval            -linebreak       -mzscheme        -sun_workshop    +wildignore
-cindent         +ex_extra        -lispindent      -netbeans_intg   -syntax          -wildmenu
-clientserver    -extra_search    -listcmds        +packages        -tag_binary      +windows
-clipboard       -farsi           -localmap        -path_extra      -tag_old_static  +writebackup
-cmdline_compl   -file_in_path    -lua             -perl            -tag_any_white   -X11
+cmdline_hist    -find_in_path    -menu            -persistent_undo -tcl             +xfontset
-cmdline_info    -float           -mksession       -printer         +terminfo        -xim
-comments        -folding         -modify_fname    -profile         -termresponse    -xsmp
-conceal         -footer          -mouse           -python          -textobjects     -xterm_clipboard
-cryptv          +fork()          -mouse_dec       -python3         -timers          -xterm_save
-cscope          -gettext         -mouse_gpm       -quickfix        -title           -xpm
-cursorbind      -hangul_input    -mouse_jsbterm   -reltime         -toolbar
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fPIE -fstack-protector-strong
-Wformat -Werror=format-security -DTINY_VIMRC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim
-lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo  -lselinux -lacl -lattr -ldl

Any ideas?

**Comment by amix** [comment]
No ideas. Try to upgrade to v8.0
