### ISSUE TITLE
Can not do page forward and backward, they are remapped to the CtrlP plugin.

### ISSUE THREAD

**Issue by teki** [amix/vimrc#229]
My keyboard does not have page up and down, so this hurts.

**Comment by rcdosado** [comment]
i too thinks ctrl-f should be restore to original functionality & how do i disable this so it wont map to CtrlP, ctrl P also seem to hanged when it is executed. i am using windows gvim

**Comment by amix** [comment]
Please see http://superuser.com/questions/610975/un-mapping-commands-in-vim

You can unmap stuff from `my_configs.vim´

**Comment by rcdosado** [comment]
Thanks @amix
