### ISSUE TITLE
no color under shellinabox

### ISSUE THREAD

**Issue by ruiruige** [amix/vimrc#236]
when I use vim via physical machine or xshell ,the vim is OK
But when I use it in the shellinabox.
Things changed

This can prove shellinabox has color terminal:  (ls -al )

![image](https://cloud.githubusercontent.com/assets/8370100/18735340/abef7f68-80af-11e6-99a7-03c153f408c5.png)

But when I enter vim,  no color  **even  no line number**
![image](https://cloud.githubusercontent.com/assets/8370100/18735186/8b64ec48-80ae-11e6-9abd-2afadf02a18a.png)

and in the mid of the vim of a null file , it is this:
![image](https://cloud.githubusercontent.com/assets/8370100/18735238/f599ce62-80ae-11e6-9f5c-abb991803e5b.png)

I guess when I open vim in shellinabox , it is in other open mode??
But the plugins are ok ,because I can still enter ',nn' or ',o' to open them, but they are also no color:

![image](https://cloud.githubusercontent.com/assets/8370100/18735283/41912540-80af-11e6-8161-95f0cc626167.png)

![image](https://cloud.githubusercontent.com/assets/8370100/18735297/5ba28cda-80af-11e6-8c66-ebe7e3aa778d.png)

anyone who knows how to solve it?

**Comment by ruiruige** [comment]
If I do:


if [ "$TERM" == "xterm" ]; then
    export TERM=xterm-256color
fi



then it will occur

**Comment by amix** [comment]
Please put this in your `my_configs.vim` - this seems to be specific to the xterm terminal
