### ISSUE TITLE
How to remove C compiler warnings/errors inside vim

### ISSUE THREAD

**Issue by AdiRishi** [amix/vimrc#237]
Hi, I am a new to vim. Thanks for making this awesome vim config

If you could just tell me which plugin is causing vim to display compiler warnings when I write a file using :w (See picture)

Thanks !
![screen shot 2016-09-22 at 2 05 18 pm](https://cloud.githubusercontent.com/assets/8351234/18736764/b6da84e0-80cd-11e6-95d1-cbd0aac49ed7.png)

**Comment by chaos5958** [comment]
@AdiRishi
 It it the plugin called "Syntasic". (https://github.com/scrooloose/syntastichttps://github.com/scrooloose/syntastic See the link :))
There are two options to handle this issue. 
First, If you don't need this plugin, just remove this file in vim_runtime/sources_not_forked.
Second, You can adjust some options in Syntastic to not show this warning when you type :w. (See help: Syntastic)

**Comment by AdiRishi** [comment]
Thanks so much for the help :) I removed the plugin
