### ISSUE TITLE
How to disaable auto fold feature?

### ISSUE THREAD

**Issue by thelou1s** [amix/vimrc#241]

**Comment by amix** [comment]
In your `my_configs.vim` try to set `set nofoldenable`

**Comment by thelou1s** [comment]
thx

**Comment by amio** [comment]
And for js files [this line](https://github.com/amix/vimrc/blob/993ed5530408f0d737ee37b152c0e6c0cd1211ef/vimrcs/filetypes.vim#L28) should be comment out:
```
au FileType javascript call JavaScriptFold()
```
