### ISSUE TITLE
Remove unused submodule from index

### ISSUE THREAD

**Issue by alexnguyen91** [amix/vimrc#243]
Hi Amix, thank you for the really cool config, I use them at my work and home and really enjoy them.

When I checked the source I find out that there are some unused submodule in sources_non_forked directory and and produce this error when I run `git submodule status`
`fatal: no submodule mapping found in .gitmodules for path 'sources_non_forked/gruvbox'`

If you're not going to use them them, could you remove them from the index using `git rm --cached` ?

**Comment by mastacontrola** [comment]
I, too, experienced the same and would recommend the same as @alexnguyen91 has requested.

There were 3 submodules that returned (after running a self cleanup).  These submodules are:

gruvbox, vim-colorschemes, and vim-gitgutter if it's of any help.
