### ISSUE TITLE
incorrect auto indent python code if pasting in vi

### ISSUE THREAD

**Issue by sali98** [amix/vimrc#244]
I create a new python file, and paste codes. Every line has relative indent to the last line:-)

**Comment by shyovn** [comment]
:set paste will help while copy-pasting stuff.

**Comment by antoniodemora** [comment]
El 15/10/2016 09:41 a.m., "shyovn" <notifications@github.com> escribió:
>
> :set paste will help while copy-pasting stuff.

What about adding this to the default config?

**Comment by mastacontrola** [comment]
Adding `set paste` to the default config, or your my_configs.vim is not a viable solution.

Paste mode is a special thing that most often is not what you want.  In "paste" mode, you're typically not adding indentations, and any indentations that are present in the copied text will typically be converted into spaces.

You might want to map a shortcut, though.  One that you press a key and it puts VIM into paste mode.  When done with paste mode, have a mapping that runs through and re-indents for you?

More info on the idea here:

https://blog.ayaz.pk/paste-mode-pasting-text-and-indenting-it-in-vim-3b9091891038#.59ccyll4l

**Comment by amix** [comment]
You can also use `<leader>p` to toggle the paste mode
