### ISSUE TITLE
ag.vim is deprecated - ack.vim supports ag as its backend

### ISSUE THREAD

**Issue by ZviRackover** [amix/vimrc#246]
According to this comment:
https://github.com/rking/ag.vim/issues/124#issuecomment-227038003
ag.vim is deprecated.

There are instructions on how to make ack.vim run using ag as its backend.
Perhaps the install script should try to detect the presence of 'ag' and if found will make it the default backed for ack.vim?

**Comment by amix** [comment]
The Drama 😳
