### ISSUE TITLE
[Basic file] Position after reopen problem

### ISSUE THREAD

**Issue by vamo89** [amix/vimrc#248]
I really need vim to remember last cursor position when I reopen the file.
I uncommented the last 3 lines, which should do that.

When I reopen a file, the last line is at the middle, and the cursor is shown at the bottom of the screen, but any arrow key that I press make it back to the right line. It does not get back to the right line position thought, it get back to the beginning of the right line.

**Comment by amix** [comment]
Position should already be saved 👀
