### ISSUE TITLE
How to install my own plugin like YouCompleteMe?

### ISSUE THREAD

**Issue by mp5557** [amix/vimrc#255]
This configuration is awesome. However, it seems like some vim's default behaviors have been changed. So I can't figure out how to install other plugin after install this configuration. I try to install YouCompleteMe following some web's steps who also have pathogen. It doesn't work. So is anybody can tell me how to install my own plugins especially YouCompleteMe?

**Comment by off99555** [comment]
@mp5557 I forked this repository and install any plugins I want manually. Just fork this and make it yours.
How to install plugins? Just clone the git repository of your plugins into sources_non_forked or sources_forked folder.

Currently, I don't know why @amix named these folders differently. What are their purposes? Can anyone clarify?

**Comment by joemcmahon** [comment]
sources_forked contains plugins that have been altered to work better with this setup; sources_non_forked are as-delivered originally.

**Comment by amix** [comment]
Please see https://github.com/amix/vimrc#how-to-include-your-own-stuff
