### ISSUE TITLE
I am just wondering why not set nu default?

### ISSUE THREAD

**Issue by hylepo** [amix/vimrc#257]
Can we have this one set nu to show line number in default

**Comment by saantiaguilera** [comment]
Why not add it in your default configs ? For example I myself dont use it (prefer to just see the number below right), and if need to go to a line just use /g or offset yourself like :number+J/K..

I think this is more of a aesthetic thing than a tool isnt it ?

**Comment by amix** [comment]
You can also see them at bottom right.

For me `nu` is a huge distraction.

Please see https://github.com/amix/vimrc/issues/200
