### ISSUE TITLE
Why my own installed plugin doesn't work? 

### ISSUE THREAD

**Issue by saeidalidadi** [amix/vimrc#260]
I installed [vim-markdown-previe](https://github.com/JamshedVesuna/vim-markdown-preview)w which is a plugin for viewing markdown in browser. 
so when I press `Ctrl-p` which is the key for it the vim terminal just shows me `:call Vim_Markdown_Preview()`

**Comment by amix** [comment]
Please report this on vim-markdown-preview's issues
