### ISSUE TITLE
Use gvim need to press the Enter key

### ISSUE THREAD

**Issue by aixiaoxiaoyu** [amix/vimrc#269]
Hello!When I use gvim to open a file, always need to press the Enter key to enter the editing interface.However, the use of vim not.
（gvim：version 7.4.52 ； system：ubuntu14.04）
![default](https://cloud.githubusercontent.com/assets/14014477/21231879/c485dc7c-c324-11e6-9d57-3dc0c436a797.png)

**Comment by amix** [comment]
I don't think this is related to this vimrc
