### ISSUE TITLE
Error detected while processing function AlignMaps#MakeMap

### ISSUE THREAD

**Issue by KorvinSilver** [amix/vimrc#271]
After setting up the Awesome version I get this error message both in vim and gvim:

```
Error detected while processing function AlignMaps#MakeMap:
line    8:
E227: mapping already exists for ,t,
Press ENTER or type command to continue
```

I've found one solution by commenting line 247 in _.vim_runtime/vimrcs/basic.vim_ but I'm not sure where's the actual problem, the error message is very vague and manually I couldn't find it.

**Comment by amix** [comment]
This isn't an issue. I am unsure why you are getting this problem.

**Comment by MarkoHoe** [comment]
The error appears in Arch Linux after installing the _vim plugins_ group in Arch Linux
The error disappears after uninstalling the vim-align package
http://www.vim.org/scripts/script.php?script_id=294
