### ISSUE TITLE
Issue with root user

### ISSUE THREAD

**Issue by fakrul** [amix/vimrc#275]
I am getting following error when try to use vi for root user:

```
# vi /etc/network/interfaces
syntastic: error: exception running system('uname'): Vim(let):E484: Cannot open file /tmp/vNHo9Ic/0
Error detected while processing function syntastic#util#system:
line   19:
E121: Undefined variable: g:_SYNTASTIC_DEBUG_CHECKERS
E116: Invalid arguments for function syntastic#log#debug
```
It's ok with non privilege users.

**Comment by jshearer** [comment]
Any update on this? I am also getting the same exact issue.

**Comment by ranosoft** [comment]
Me too. I'm getting the same, from some days ago.

**Comment by amix** [comment]
Please report this on https://github.com/vim-syntastic/syntastic

**Comment by agarzon** [comment]
I'm having the same issue. Tested in all my centos 7 servers.

```bash
syntastic: error: exception running system('uname'): Vim(let):E484: Can't open file /tmp/v0jsoLf/0
Error detected while processing function syntastic#util#system:
line   19:
E121: Undefined variable: g:_SYNTASTIC_DEBUG_CHECKERS
E116: Invalid arguments for function syntastic#log#debug
Press ENTER or type command to continue

```
The problem is with syntastic, but vimrc should not ship broken code anyways. This plugin should be removed temporarily until syntastic fix the issue.

**Comment by lukasschwab** [comment]
If you're using fish as your shell, this is a relevant (documented) issue in the syntastic repo: https://github.com/vim-syntastic/syntastic/issues/2013

**Comment by agarzon** [comment]
@lukasschwab You got me, that's right I use fish as shell. Thank you.

So based on that, my permanent solution is just to add this line into my config file:

~/.vim_runtime/my_configs.vim

```bash
let g:syntastic_shell = "/usr/bin/bash"
```

:+1:

**Comment by taninaim** [comment]
I had this problem earlier. I tried fixing it by updating vim. But somehow it said I had no space left in /var/cache/apt/archives. I even tried downloading ncdu to figure out what was eating up memory, but I didn't have enough space to install ncdu (even after removing some files on Desktop). So then I removed a few conda virtual environments, and this fixed the problem.
