### ISSUE TITLE
Auto Indentation in ruby files and erb template files (tab instead of 2 space)

### ISSUE THREAD

**Issue by brkkyk** [amix/vimrc#282]
Hello everyone,
Auto indentation (=G) looks like work wrong in ruby (.rb) files and rails default view template (.erb) files.  This should be 2 spaces instead of tab. Thanks.

**Comment by amix** [comment]
Please see http://stackoverflow.com/questions/158968/changing-vim-indentation-behavior-by-file-type

**Comment by brkkyk** [comment]
Can't we do it dynamic by detecting current file's programming language?

**Comment by amix** [comment]
@brkkyk You can do `au FileType ruby setl sw=2 sts=2 et`
