### ISSUE TITLE
ctrl+f and ctrl+b doesn't work

### ISSUE THREAD

**Issue by sudarshansudarshan** [amix/vimrc#283]
I am using it on my mac air (mac os sierra) and page up and page down commands (ctrl+f and ctrl+b) don't seem to be working. Any help will be appreciated :-)

**Comment by Tiande** [comment]
C-f c-b have other functions

just use C-d C-u for page up/down

**Comment by sudarshansudarshan** [comment]
Great. Thank you very much :-)

**Comment by sudarshansudarshan** [comment]
Is there anyway I can disable all the custom shortcuts? I am so used to them that I can't unlearn :-)

The love the highlighting and other facilities that your code provides 👍

**Comment by xanoni** [comment]
> just use C-d C-u for page up/down

This is not the same as pageup/pagedown ... these only go up/down half a page.
