### ISSUE TITLE
Can not find color scheme

### ISSUE THREAD

**Issue by sandangel** [amix/vimrc#284]
I changed color scheem in extended.vim file like this

    colorscheme vim-irblack-forked

but there was a problem E185: Cannot find color scheme 'vim-irblack-forked'
I found it in .vim_runtime/sources_forked/vim-irblack-forked
How can I change color scheme?

**Comment by Tiande** [comment]
why don't you read the "README" file in that folder
you should use this command:
```
:colorscheme ir_black
```

**Comment by sandangel** [comment]
oh my fault, sorry about that

**Comment by sjytker** [comment]
> oh my fault, sorry about that

Did you solve that? I change colorscheme in extend.vim like you two said, but still got the error.
