### ISSUE TITLE
how to scroll?

### ISSUE THREAD

**Issue by zinwalin** [amix/vimrc#285]
The default scrolling key mappings is Ctrl + F and Ctrl + B, how to implement in this vimrc config?

**Comment by sivaramsk** [comment]
I have the same question. It is default in vim and it has been overwritten by one of the configs i suppose.

**Comment by Tiande** [comment]
Ctrl + D and Ctrl + U for a half scroll

**Comment by amix** [comment]
You can put following in your `my_configs.vim`
```vim
nunmap <c-f>
nunmap <c-b>
```

**Comment by xanoni** [comment]
> You can put following in your `my_configs.vim`
> 
> ```viml
> nunmap <c-f>
> nunmap <c-b>
> ```

On my computer, this doesn't do anything. Is there a better way than removing line 50 in `~/.vim_runtime/vimrcs/plugins_config.vim` ?
