### ISSUE TITLE
How to reabase with stuff you've added to sources non forked

### ISSUE THREAD

**Issue by GaryFurash** [amix/vimrc#290]
If we add items to Sources Non Forked (e.g., a new plugin), how do we get the latest version (git rebase)?

**Comment by amix** [comment]
By running `python update_plugins.py`

**Comment by Kudlaty01** [comment]
@amix  There would be no more need to update via git any more?

**Comment by smbell** [comment]
Just do a git pull. I have additional plugins in non_forked and git pull works just fine. Worst case do a git stash;git pull;git pop

**Comment by Kudlaty01** [comment]
Did you mean git _stash_ pop?
What about excluding @amix 's plugins from _.gitignore_?
