### ISSUE TITLE
vim-multiple-cursors not work

### ISSUE THREAD

**Issue by walkerwzy** [amix/vimrc#297]
in plugins_config.vim, I found the multiple cursor plugin configuration like this:
```
 let g:multi_cursor_next_key="\<C-s>"
```
what `"\<C-s>"` is?
I tried `ctrl+s`, `\+ctrl~s`, none of these works.

**Comment by amix** [comment]
`C-s` is `CTRL+S`. And vim-multiple-cursors does work.

if you have any issues please report to https://github.com/terryma/vim-multiple-cursors -- as the version shipped with the vimrc isn't forked or changed.
