### ISSUE TITLE
Source Code Pro font from Adobe is not free

### ISSUE THREAD

**Issue by between2spaces** [amix/vimrc#299]
You mention in the README that Source Code Pro font from Adobe is free. I tried to obtain it, first having to give up information like name, age, email address, country, etc... and then after completing the form with bogus information got a blank white page and no further towards obtaining the font because Ghostery did its job and block trackers from running. 

This is not a "free" experience.

**Comment by lioman** [comment]
That's why I am using [Hack](https://sourcefoundry.org/hack/). It's open source libre and designed for code.

**Comment by stralsi** [comment]
I's on GitHub under an open font license. https://github.com/adobe-fonts/source-code-pro

**Comment by amix** [comment]
I have now replaced this with [Hack](http://sourcefoundry.org/hack/)
