### ISSUE TITLE
green line on left edge of terminal when using vim

### ISSUE THREAD

**Issue by nihiluis** [amix/vimrc#305]
what is this?

didn't do anything besides installing awesome config

![vimerror](https://cloud.githubusercontent.com/assets/24858082/24801206/7cd9886a-1ba3-11e7-9418-a136df202a06.jpg)

**Comment by iantabolt** [comment]
There is a section in basic.vim:

```
" Add a bit extra margin to the left
set foldcolumn=1
```

I commented this out to get rid of it. #311 is complaining about the same thing.

**Comment by manish-baghel** [comment]
This is because some linter is analyzing your file and on completion, it colors a column in the beginning of correct lines with green color.
You can turn it if using `set signcolumn=no`
