### ISSUE TITLE
Commit 4b2dafc26ab82df790bef6a4ae1c2ad5c5ca06c3 breaks font on gvim in Ubuntu 16.04

### ISSUE THREAD

**Issue by khatchad** [amix/vimrc#309]
The font of gvim on my Ubuntu 16.04 machine is extremely wide. Reverting 4b2dafc26ab82df790bef6a4ae1c2ad5c5ca06c3 seems to fix the problem.

**Comment by amix** [comment]
Please do a PR, I don't have access to an Ubuntu machine 👍
