### ISSUE TITLE
help: every line has a space before the content

### ISSUE THREAD

**Issue by ysymi** [amix/vimrc#311]
#### software I'm using:
#zsh 5.2 (x86_64-apple-darwin16.0)

#### problem:
when copy out content from vim, every line has a space in the copied-text. 

see picture:
![wechatimg285](https://cloud.githubusercontent.com/assets/7665355/25734803/2e3c5e24-3199-11e7-9e8b-b9eac5a64cba.jpeg)

the cursor's position is 1,1 , but there is a space left 
and I choose some text to copy , it's clear to see every line has a leading space which is not in content.

please tell me why this space exist and how to remove it ?
thanks :)

**Comment by amix** [comment]
I would advice to copy stuff from Vim using a Vim selection.

Check out https://stackoverflow.com/questions/3961859/how-to-copy-to-clipboard-in-vim
