### ISSUE TITLE
How can I add github colorscheme repo?

### ISSUE THREAD

**Issue by MattSom** [amix/vimrc#312]
I don't really understand how could I change the colorscheme. Let's say I have the theme's github repo. How should I proceed from that?

**Comment by giddygitau** [comment]
Hey @MattSom All you need to do is to clone the repo into the `~/.vim_runtime/sources_non_forked` directory.

For example to install the awesome onedark theme:
```
$ cd ~/.vim_runtime/sources_non_forked && git clone https://github.com/joshdick/onedark.vim.git
```
Then to avoid polluting the base installation, create your own config file `my_config.vim` in the `~/.vim_runtime` directory.
Inside `my_config.vim` add your preferred settings to override the default ones that come installed. e.g to use `onedark`  just add the line:
```
colorscheme onedark
```
I think that this method of extension applies to any plugin that is contained in a github repo
