### ISSUE TITLE
Cannot open '.go' file in awesome version

### ISSUE THREAD

**Issue by Ayke** [amix/vimrc#315]
After I installed the awesome version, if I want to open a '.go' file, like 'vim a.go', it automatically redirect me to "~/.vim_runtime/sources_non_forked/vim-go/templates/hello_world.go". Is anyone facing the same issue with me?
By the way, the basic version works well for me.

**Comment by kincaid520** [comment]
I've tried my awesome version.
When I entered _**vim test.go**_ in terminal,
it'll open ~/.vim_runtime/sources_non_forked/vim-go/templates/hello_world.go file
Same as Ayke.

**Comment by amix** [comment]
This seems to be a feature of vim-go. Please report it to https://github.com/fatih/vim-go

(It's using a template for a new Go file)
