### ISSUE TITLE
Awesome version on mac

### ISSUE THREAD

**Issue by Mercurial1101** [amix/vimrc#319]
When I use c++11 features, like ‘auto’, when I type ':w' on the vim, it consistently reports an warning 
 auto' type specifier is a C++11 extension [-        Wc++11-extensions]  

Do you have ways to fix that? Thanks!  (BTW, I already specify alias on the bashrc file.)

**Comment by amix** [comment]
Please see the configuration options of https://github.com/vim-syntastic/syntastic and my_configs.vim 👍
