### ISSUE TITLE
The Basic version can't call function VisualSelection

### ISSUE THREAD

**Issue by 7anshuai** [amix/vimrc#321]
I just copy the [basic.vim](https://github.com/amix/vimrc/blob/master/vimrcs/basic.vim) to `~/.vimrc`. 
When pressing * or # searchs in visual mode,  error happened:  `E117: Unknown function : VisualSelection`.

It's better to move the VisualSelection function from `extended.vim` to `basic.vim`?

**Comment by amix** [comment]
Fixed, thanks for the report
