### ISSUE TITLE
Errors in basic version with vim 8.0.606

### ISSUE THREAD

**Issue by hamzatrq** [amix/vimrc#323]
Getting the following error.
`Error detected while processing /home/zeus/.vimrc:
line   54:
E484: Can't open file /usr/share/vim/vim80/delmenu.vim
line   55:
E484: Can't open file /usr/share/vim/vim80/menu.vim
line  124:
E484: Can't open file /usr/share/vim/vim80/syntax/syntax.vim
Press ENTER or type command to continue
`
I am using Ubuntu 16.04 and have compiled vim from source.

**Comment by amix** [comment]
Please report to Vim maintainers. I don't think this error is related to this installation.
