### ISSUE TITLE
mru.vim open in tab doesn't work

### ISSUE THREAD

**Issue by dwaxe** [amix/vimrc#325]
This is an issue with mru.vim, but their Github page lacks an Issues tab.

Reproduction steps: 
1. Open mru.vim with <leader+f> `,f`
2. Try to open a file in a new tab with `t`

<img width="1078" alt="screen shot 2017-06-21 at 12 30 23 pm" src="https://user-images.githubusercontent.com/3530333/27402948-6f54eb7a-567d-11e7-91d3-919d01619263.png">

**Comment by amix** [comment]
Fixed [here](https://github.com/amix/vimrc/commit/71ca6d0ec8259ba87e6015344efda891f8da7e98)
