### ISSUE TITLE
vim-abolish lost in recent update

### ISSUE THREAD

**Issue by smbell** [amix/vimrc#326]
In the May-28th commit vim-abolish was added as a non_forked plugin. In the most recent July 6th commit the comment was simply 'Update vim plugins' but abolish was removed.

Was the removal of abolish intentional, or was there some merge issue?

**Comment by amix** [comment]
This was an error. Fixed [here](https://github.com/amix/vimrc/commit/2ef74326f064c17f2309e1e2b5930e67c0fefc3c)
