### ISSUE TITLE
indent not correct

### ISSUE THREAD

**Issue by zchrissirhcz** [amix/vimrc#328]
I'm in awesome mode. In my own config file, I set tab length to be 4 spaces.
However when I open a python file,  the tab's length is still 8 spaces. By editing `basic.vim`, uncomment this line:

```
filetype plugin on
```

the tab space is 4.

My question is: can we disable `filetype` plugin's tab setting? Thanks?

**Comment by wming126** [comment]
You can！

**Comment by amix** [comment]
Check out https://github.com/amix/vimrc#how-to-include-your-own-stuff

**Comment by zchrissirhcz** [comment]
@amix  Thanks, but I have actually put my config in `~/.vim_runtime/my_configs.vim`:
```bash
set nu

set tags=tags;
set autochdir

set smartindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set showmode
set autoindent
set noexpandtab
set cindent
```
