### ISSUE TITLE
Vim syntax highlighting/syntax checking for .scala files not working by default

### ISSUE THREAD

**Issue by shan23** [amix/vimrc#330]
It seems there is Syntastic support for .scala files, but when I open a .scala file, I don't see *any* highlighting at all. Do I have to enable support for .scala files separately? I'm using the awesome version btw.

**Comment by shan23** [comment]
I'm guessing this is not going to be looked at by the author? If so, please close this issue.

**Comment by joe-el-khoury** [comment]
I'm having the same issue. Did you ever figure this out?

**Comment by shan23** [comment]
@joe-el-khoury I had pushed a PR (https://github.com/amix/vimrc/pull/339) with the needed plugin, but @amix had declined it as he doesnt use Scala.
Feel free to use my fork - I've kept it updated with the trunk, and added a few things you may find useful: https://github.com/shan23/vimrc

**Comment by joe-el-khoury** [comment]
@shan23 thank you! Seems to work well. I noticed your README contains references to amix (in the "How to install the Awesome version" section and the basic counterpart), so you might want to change that to reference your username instead.

Thanks again.

**Comment by shan23** [comment]
@joe-el-khoury Thanks for pointing that out, just fixed it - I honestly never thought someone would be using my fork, hence never paid attention to the README :).

**Comment by amix** [comment]
I'm glad you figured it out :)

Btw. you can include your own mappings and plugins without forking. Please see:
https://github.com/amix/vimrc#how-to-include-your-own-stuff
