### ISSUE TITLE
How to config <tab> to python?

### ISSUE THREAD

**Issue by Hanzhizheng** [amix/vimrc#331]
HI,
    Sorry to take your time. I type letters 'pr' and want keyword 'print' by pressing 'tab', but got 'property' instead, how to config <tab> to python?

**Comment by trotsky1997** [comment]
au BufNewFile,BufRead *.py
\ set tabstop=4
\ set softtabstop=4
\ set shiftwidth=4
\ set textwidth=79
\ set expandtab
\ set autoindent
\ set fileformat=unix



VIA:https://segmentfault.com/a/1190000003962806#articleHeader12

**Comment by amix** [comment]
Please see here how to include your own configs:
https://github.com/amix/vimrc#how-to-include-your-own-stuff
