### ISSUE TITLE
http://amix.dk/ availability affects some of the docs

### ISSUE THREAD

**Issue by Norbinsh** [amix/vimrc#334]
Nothing crucial but I noticed your site (http://amix.dk/) is not available, while some of the docs reference to it with some hyper links that are N/A, and sometimes images that gets broken, such as: 
https://github.com/amix/vimrc/tree/master/sources_non_forked/vim-zenroom2
See bottom part: '#How it looks in action'.

Thanks.

**Comment by amix** [comment]
Thanks, will fix this
