### ISSUE TITLE
Vim via Ubuntu Bash on Windows 10

### ISSUE THREAD

**Issue by sus007** [amix/vimrc#335]
I'm using Vim via Ubuntu Bash on **Windows 10's subsystem for Linux**, which process shall I follow to install the **Awesome Version** ?

> When I tried installing via Linux way, I got Input/Output error for this command:
`sh ~/.vim_runtime/install_awesome_vimrc.sh`

**Comment by trotsky1997** [comment]
bro，this is the second raw of the command that the author have gave you，you just need to hit your “ENTER” key and the installastion will going on and come to successesful！ @sus007

**Comment by sus007** [comment]
Thank you, @trotsky1997 , btw, could you help me to install the **Hack** font into my Vim ?

**Comment by trotsky1997** [comment]
i am also a new guy for linux

**Comment by sus007** [comment]
So, what got you into Linux all of a sudden ? Or, are you a **WSL** guy like myself ? _(**W**indows **S**ubsystem for **L**inux)_

**Comment by amix** [comment]
I am closing this down as it seems more OS/Vim related than to this vimrc 😊

I am glad you could help each other out.
