### ISSUE TITLE
Take too much time to save a file

### ISSUE THREAD

**Issue by vishichoudhary** [amix/vimrc#336]
after installing awesome version vim take too much time to save file though fast in exiting without saving file. Any improvements?

**Comment by deathnot3** [comment]
So what do u expected for? There are a lot of plugins, of course it could have some speed issues.

**Comment by vishichoudhary1** [comment]
I expected some speed enhancement tricks.

**Comment by ingwinlu** [comment]
i only notice slowdowns when editing large projects. probably because of syntastic doing a build in the background that blocks `:w` from returning.

**Comment by amix** [comment]
I would recommend trying to disable [Ale](https://github.com/dense-analysis/ale), e.g.
https://github.com/dense-analysis/ale#faq-disable-linters

Another option is to use the basic version.
