### ISSUE TITLE
How to page up and down as a replacement for <c-f> and <c-b>?

### ISSUE THREAD

**Issue by hangjitrai** [amix/vimrc#338]
<c-f> and <c-b> have been mapped to ctrlp commands.

What keys can be used for navigating the page with page up and page down? I know I can map it to anything but I want to know the 'standard' way to map the keys to these functionalities.

**Comment by cheng10** [comment]
@hangjitrai I have this exact question as you. I just wonder why the author assign c-f, c-b to ctrlp. How do you pagedown or pageup then? I think the standard way of page down, page up should not be replaced easily.

**Comment by Razor-13** [comment]
See https://github.com/amix/vimrc/issues/119#issuecomment-151835510 for a fix

But this doesn't work for C-f, it remains on the plugin, so in total you need to add

```
let g:ctrlp_map = '<c-p>'
nnoremap <C-f> <PageUp>
nnoremap <C-b> <PageDown>
```

to ~/.vim_runtime/my_configs.vim

**Comment by joeyslack** [comment]
@Razor-13 Great tip, works great. I'd like to point out though, that C-f and C-b are backwards, should be:

```
let g:ctrlp_map = '<c-p>'
nnoremap <C-f> <PageDown>
nnoremap <C-b> <PageUp>
```

Based on the vim docs(http://vimdoc.sourceforge.net/htmldoc/scroll.html): 

> "Ctrl-F: Scroll window [count] pages Forwards (downwards) in the buffer.  See also 'startofline' option. When there is only one window the 'window' option might be used."

**Comment by Razor-13** [comment]
Correct, edited my comment above so anyone pasting it don't get confused

**Comment by amix** [comment]
I'm glad you resolved this 👍

**Comment by bsotelo** [comment]
I'm glad I found the answer to my issue here. I can now do ctrl+f and ctrl+b to navigate pages.
