### ISSUE TITLE
$ appears as end of line characters and it's unremovable please help

### ISSUE THREAD

**Issue by ericntd-legacy** [amix/vimrc#34]
Thanks a lot for your helpful .vimrc.

The issue with the $ character is driving me insane though. When I try to execute my script I got "^M" is an invalid character but in Vim, I see $ upon entering ":set list"

I tried :%s/^V^M//g but it says "^M" pattern is not found. I'm really stuck

Please help, I can't lose this particular script

**Comment by alphaCTzo7G** [comment]
You can do this with `<leader>m` with this `vimrc`: https://github.com/amix/vimrc/blob/993ed5530408f0d737ee37b152c0e6c0cd1211ef/vimrcs/basic.vim#L318
