### ISSUE TITLE
vim-multiple-cursors shortcut C-s does not work?

### ISSUE THREAD

**Issue by dwildmark** [amix/vimrc#340]
I'm trying to use the multiple cursor plugin, and as the vimrc README states, it should be bound to C-s. I do not get it to work with that shortcut.

**Comment by kohearon** [comment]
Any solution to this?

**Comment by zhangyuygss** [comment]
Same here, and when I type C-s, vim died and won't response.

**Comment by xiaodong-xie** [comment]
Same here. So I just changed 
`let g:multi_cursor_next_key="\<C-s>"` to `let g:multi_cursor_next_key="\<C-d>"` (remap ctrl-s to ctrl-d) in `vimrcs/plugins_config.vim`, it worked fine.

**Comment by xiaodong-xie** [comment]
And I think I know the solution: https://unix.stackexchange.com/questions/72086/ctrl-s-hang-terminal-emulator

I added `stty -ixon` to my `.zshrc`, `ctrl-s` worked. 😄

**Comment by dwildmark** [comment]
> I added stty -ixon to my .zshrc, ctrl-s worked.
I can confirm that this will fix it in bash aswell (Ubuntu 16.04)

**Comment by jayrexacilo** [comment]
> And I think I know the solution: https://unix.stackexchange.com/questions/72086/ctrl-s-hang-terminal-emulator
> 
> I added `stty -ixon` to my `.zshrc`, `ctrl-s` worked. 😄

this works but freezes the vim session
