### ISSUE TITLE
Vim is not creating .swp files

### ISSUE THREAD

**Issue by levivm** [amix/vimrc#342]
I was working in vim and my OS(Mac OS X El Capitan) crashed.

I tried to recover from .swp files created by vim (usually). But, I noticed that vim is not creating them. I already setup swap/backup directories but not luck.

**Comment by levivm** [comment]
I found the issue, IDK why but by default backups and swap mode are disabled. 

So, I needed to add `set swapfile` and `set backup` manually to my vim config file.

**Comment by amix** [comment]
Note that you can include your configs in the my_configs.vim [Ref](https://github.com/amix/vimrc#how-to-include-your-own-stuff). I find the swap files quite annoying.

Like @alphaCTzo7G mentions persistent-undo is turned on and the swap/backup isn't very necessary.
