### ISSUE TITLE
Pasting tabbed lines messes up formattign

### ISSUE THREAD

**Issue by willieowens** [amix/vimrc#344]
Seems that the auto-tab functionality to keep you at the same tab width on a newline is applying to pasted text, which messes up formatting.

For instance, if I paste:

```
hi
    there
    sir
```

into a section looking like:

```
hi
    there
    sir
<---- and try to paste it here
```

I end up with:
```
 hi
     there
     sir
 hi  
      there
           sir
```

**Comment by samclayj** [comment]
You can use `:set paste` before pasting the text and then use ':set nopaste' when you are finished pasting.

**Comment by willieowens** [comment]
Ah ok, thanks! I guess this is a known issue (or perhaps just how it works). It'd be nice, IMO, to do this automatically when pasting, but I don't know enough about the tool to know if that's possible or sensible.
