### ISSUE TITLE
How to disable features?

### ISSUE THREAD

**Issue by BackOrder** [amix/vimrc#345]
I used vim without any fancy scripts for the longest time but the ultimate vim configuration is awesome. So far very enjoyable.

There is a slight problem when I edit some C files in a projet where there are missing headers that are linked at compile time (pkg-config), cairo in the example below. Vim warns me each time I save a file, making it rather annoying to quit twice. 

How could I disable this feature?

Generally speaking I don't know how to configure ultimate vim.

![capture du 2017-09-24 08-09-10](https://user-images.githubusercontent.com/8844578/30784292-8f4bd96e-a120-11e7-9aef-a3d9579b5897.png)

**Comment by will-shaw** [comment]
I had something similar with C++.
You can add some options in: `~/.vim_runtime/vimrcs/plugins_config.vim`
The options for the syntastic plugin can be found here: https://github.com/vim-syntastic/syntastic/wiki/C:---gcc

Hope this helps!

**Comment by BackOrder** [comment]
Works like a charm! Thanks Will.
