### ISSUE TITLE
color theme

### ISSUE THREAD

**Issue by PraflyGod** [amix/vimrc#347]
I like this project, and want to use it in my work. But the peaksea theme is not good enough for c++, I want to use solarized. But change the theme in extend.vim, it doesn't work. I use Xshell 5 in windows, Xshell theme is solarized dark. Can anyone solve this problem for me?
![Uploading image.png…]()

peaksee in cpp file.

**Comment by will-shaw** [comment]
Changing that value in extended works for me. Maybe it's the theme.  
Just in case you haven't tried already, try to run `:colorscheme solarized` from vim.  
If it doesn't change, then I'd check if `~/.vim/colors/solarized.vim` exists.

You might have done both these already, but it can't hurt to suggest it :smile:

**Comment by PraflyGod** [comment]
![before](https://user-images.githubusercontent.com/13954697/31477877-cfb8bce2-af3f-11e7-9698-3410598c19ba.PNG)
it is weird。。。
![after](https://user-images.githubusercontent.com/13954697/31477907-e6ed60b6-af3f-11e7-8e5b-1217f4da9114.PNG)

**Comment by PraflyGod** [comment]
it seems like its color doesn't work in xshell. Its looks weird as you can see from above.

**Comment by PraflyGod** [comment]
Do I need to change the color theme of xshell to get it work? I don't know how to do.

**Comment by alphaCTzo7G** [comment]
@PraflyGod , I use putty.. and it works really well. However, I did have to tweak my putty setting a bit. I use the default peaksea and the colors work fine.

**Comment by amix** [comment]
Please see here how to include your own configs and color schemes:
https://github.com/amix/vimrc#how-to-include-your-own-stuff
