### ISSUE TITLE
Variables started with $e are replace to ""

### ISSUE THREAD

**Issue by hugleo** [amix/vimrc#348]
Types like  Exception($e)
Or simply: 
$e

Are replaced to "".

The problem is caused if I copy paste text too. 

Just work if after I type $ char I wait a long time to type the char e.

**Comment by ingwinlu** [comment]
see https://github.com/amix/vimrc#insert-mode-mappings

**Comment by hugleo** [comment]
Maybe for php language would be better to be disabled by default since php variables starts with $.

**Comment by amix** [comment]
In your [my_configs.vim](https://github.com/amix/vimrc#how-to-include-your-own-stuff) you can add this to unmap $e

    unmap $e

**Comment by liyishuai** [comment]
> In your [my_configs.vim](https://github.com/amix/vimrc#how-to-include-your-own-stuff) you can add this to unmap $e
> 
> ```
> unmap $e
> ```

The documentation is titled "How to include your own stuff?" while the purpose is actually "excluding some stuff you don't want". Took me quite a while to search for this solution. Maybe worth making it more visible somewhere.
