### ISSUE TITLE
E174: Command already exists: add ! to replace it

### ISSUE THREAD

**Issue by 4Z4T4R** [amix/vimrc#350]
When sourcing the .vimrc from within vim using the following command:

```
:source ~/.vimrc
```

I get the following error:

```
Error detected while processing /Users/sjcbsolo/.vim_runtime/vimrcs/basic.vim:
line   66:
E174: Command already exists: add ! to replace it
Press ENTER or type command to continue
```

Looking at the source of the error inside basic.vim, I suspect that this:

```
command W w !sudo tee % > /dev/null
```

would be better off as this instead:

```
command! W w !sudo tee % > /dev/null
```

In fact, after the change, I no longer get the error.

**Comment by xclidongbo** [comment]
God job.

**Comment by amix** [comment]
This is already fixed. Thank you for the report 🙏
