### ISSUE TITLE
Windows MinGW with vim not reading ~/.vim/vimrc

### ISSUE THREAD

**Issue by KyleScharnhorst** [amix/vimrc#352]
Hey guys,

I installed the awesome version and wasn't getting line numbers. Looked into it and found that the ~/.vim/vimrc wasn't getting loaded.

I'm running Windows 10, MinGW-W64-builds-4.3.0 with vim version version 8.0 (2016 Sep 12, compiled Jan 25 2017 09:05:56).

Once I added: ` source ~/.vim/vimrc`
To my ~/.vimrc
I started getting line numbers.

Not sure if you guys are trying to support the Windows side of things. Just wanted to point this out. Or if there is something that isn't setup properly on my system, I would love to know.

**Comment by alphaCTzo7G** [comment]
In Ubuntu.. I also have the following lines..

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim

I installed this a long time back.. but most likely you should have these lines installed by default in your ~/.vimrc from the awesome version itself.

**Comment by amix** [comment]
This is more an OS/Vim issue, than a problem with this configuration.
