### ISSUE TITLE
  How do I remove the white edge at the bottom of the screen?

### ISSUE THREAD

**Issue by wming126** [amix/vimrc#353]
Hi,  How do I remove the white edge at the bottom of the screen? 
As shown in the figure:
https://raw.githubusercontent.com/wming126/MarkDownImage/master/edge.png
Thanks!

你好，请问如何去除vim屏幕底部的白边？如下图所示：
https://raw.githubusercontent.com/wming126/MarkDownImage/master/edge.png
非常感谢！

**Comment by wming126** [comment]
When I full screen the vim , there is a white edge at the bottom of the screen.

**Comment by alphaCTzo7G** [comment]
I have the same issue.. Did you find anything out? Probably have narrow down what variable is causing this change..

**Comment by fanofxiaofeng** [comment]
What system are you using? I didn't see the "white edge" on my mac (MacBook Pro (Retina, 15-inch, Mid 2015))
![image](https://user-images.githubusercontent.com/3983683/32814244-16f6eaf2-c9e9-11e7-8c3b-b3b654db20e4.png)

**Comment by wming126** [comment]
My system is Ubuntu 16.04.3.

**Comment by zzeroo** [comment]
@wming126 it looks like the borders you show us are from your terminal emulator. Please have a look at the settings of your "gnome-terminal', look for "show scrollbars" or if you use another terminal emulator for settings like these. Disable the scrollbars should fix it.

**Comment by AxelBohm** [comment]
It is definitely a terminal emulator issue. I experience the same problem when running eiter gnome-terminal or st(suckless terminal), but not with lxterminal. (Note that I have scrollbars disabled in all of these). 

I am also on Ubuntu 16.04.03

**Comment by amix** [comment]
This is more an OS/Vim issue, than a problem with this configuration.
