### ISSUE TITLE
vimrc causing git rebase 'Could not execute editor'

### ISSUE THREAD

**Issue by chrissinclair** [amix/vimrc#355]
Hello! 

Firstly - thank you for putting all this together. Only discovered it yesterday and it's awesome!

I've installed the default awesome vimrc (attached is the one from my machine), and am running in iterm using zsh. Since using that vimrc I'm now finding that if I run an interactive rebase in one of my git repos (e.g. git rebase -i --root), even if I quit immediately without making any edits git complains and gives me the error 'Could not execute editor'. If I stop using the vimrc the issue goes away.

Hopefully that's enough to replicate the issue - let me know if you need more. 

Thanks again!

[vimrc.txt](https://github.com/amix/vimrc/files/1376724/vimrc.txt)
[basic.vim.txt](https://github.com/amix/vimrc/files/1376734/basic.vim.txt)
[extended.vim.txt](https://github.com/amix/vimrc/files/1376735/extended.vim.txt)
[filetypes.vim.txt](https://github.com/amix/vimrc/files/1376736/filetypes.vim.txt)
[plugins_config.vim.txt](https://github.com/amix/vimrc/files/1376737/plugins_config.vim.txt)

Edit - added other vimrc's (they should just be the default). I don't have a my_configs.vim file.

**Comment by aft-christophe** [comment]
I had and issue where i could not use git commit command

```
error: There was a problem with the editor 'vi'.
```

I removed those lines from the .vmrc file and it worked

```
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Files, backups and undo
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Turn backup off, since most stuff is in SVN, git et.c anyway...
set nobackup
set nowb
set noswapfile
```

Also did 
```
git config --global core.editor /usr/bin/vim
```

maybe that could help you ?

**Comment by chrissinclair** [comment]
Hi @aft-christophe,

You're spot on - that's sorted it out for me. 

Many thanks!

Chris
