### ISSUE TITLE
Pathogen does not work with Vim version 8

### ISSUE THREAD

**Issue by plopezmp** [amix/vimrc#356]
I have installed  Vim with homebrew in a Mac OSX

`zsh-% vim --version

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 27 2017 06:40:14)

MacOS X (unix) version

Included patches: 1-1150

Compiled by Homebrew

Huge version without GUI.  Features included (+) or not (-):

+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminal
++builtin_terms  +fork()          +multi_lang      +terminfo
+byte_offset     -gettext         -mzscheme        +termresponse
+channel         -hangul_input    +netbeans_intg   +textobjects
+cindent         +iconv           +num64           +timers
-clientserver    +insert_expand   +packages        +title
+clipboard       +job             +path_extra      -toolbar
+cmdline_compl   +jumplist        +perl            +user_commands
+cmdline_hist    +keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      +startuptime     -xpm
+eval            +mouse_dec       +statusline      -xsmp
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
+farsi           +mouse_netterm   +tag_binary

   system vimrc file: "$VIM/vimrc"

     user vimrc file: "$HOME/.vimrc"

 2nd user vimrc file: "~/.vim/vimrc"

      user exrc file: "$HOME/.exrc"

       defaults file: "$VIMRUNTIME/defaults.vim"

  fall-back for $VIM: "/usr/local/share/vim"

Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1

Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa   -mmacosx-version-min=10.11 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.26.0/lib/perl5/5.26.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/opt/python/Frameworks -framework Python   -lruby.2.4.2 -lobjc

zsh-%`

When I open any file it tells me 

`zsh-% vim kk.tex
Error detected while processing /Users/plm/.vim_runtime/vimrcs/plugins_config.vim:
line   12:
E117: Unknown function: pathogen#infect
line   13:
E117: Unknown function: pathogen#infect
line   14:
E117: Unknown function: pathogen#infect
line   15:
E117: Unknown function: pathogen#helptags
line  106:
E15: Invalid expression:
E15: Invalid expression: {
line  107:
E10: \ should be followed by /, ? or &
line  108:
E10: \ should be followed by /, ? or &
line  110:
E15: Invalid expression:
E15: Invalid expression: {
line  111:
E10: \ should be followed by /, ? or &
line  112:
E10: \ should be followed by /, ? or &
line  113:
E10: \ should be followed by /, ? or &
line  114:
E10: \ should be followed by /, ? or &
line  115:
E10: \ should be followed by /, ? or &
line  116:
E10: \ should be followed by /, ? or &
line  117:
E10: \ should be followed by /, ? or &
line  118:
E10: \ should be followed by /, ? or &
line  119:
E10: \ should be followed by /, ? or &
line  120:
E10: \ should be followed by /, ? or &
line  121:
E10: \ should be followed by /, ? or &
line  122:
E10: \ should be followed by /, ? or &
line  123:
E10: \ should be followed by /, ? or &
line  124:
E10: \ should be followed by /, ? or &
line  125:
E10: \ should be followed by /, ? or &
line  126:
E10: \ should be followed by /, ? or &
line  127:
E10: \ should be followed by /, ? or &
line  128:
E10: \ should be followed by /, ? or &
line  129:
E10: \ should be followed by /, ? or &
Error detected while processing /Users/plm/.vim_runtime/vimrcs/extended.vim:
line   32:
E185: Cannot find color scheme 'peaksea'
Press ENTER or type command to continue`

 How could I fix it?.

Best regards

**Comment by alphaCTzo7G** [comment]
Agree..

1. To debug plugins in VIM, when using Pathogen, you have to move the plugins out of the load path of Pathogen. This is more painful than when using Vundle or Neobundle, where you can just comment out your lines in the vimrc files

2. Most new people are going to start using VIM8 or NeoVIM, which has async features. Pathogen probably doesn't support these features which is why loading a lot of plugins is a bit slower.

3. Long term, we should move to better plugin managers, perhaps even the builtin plugin managers in VIM8. One of the core developers of NeoVIM told me that NeoVIM is going to be backward compatible and plul andy changes that happen with VIM8. So if we use the built in plugin manager in VIM8, perhaps that would be the best option going forward to use the async features, and if we don't have to be backward compatible with VIM7.4. But if we want to maintain backward compatibility with VIM7.4, probably we should use a third party manager such as Neobundle or Vundle.

4. Vundle is much more popular than Pathogen(https://github.com/tpope/vim-pathogen) vs (https://github.com/VundleVim/Vundle.vim). The author also seems to be always updating it. A lot more people are familiar with Vundle than Pathogen at this time.

What do you guys think?

**Comment by saifeiLee** [comment]
Agree.

**Comment by alphaCTzo7G** [comment]
I just upgraded to VIm8, by compiling VIM from source. And all plugins and my vimrc still seems to be working. So probably pathogen isn't broken in VIM8, but given that Pathogen is not that well maintained, it would still be better to move to Vundle, maybe not today or tomorrow, but maybe in a few months..
