### ISSUE TITLE
How to change cursor color

### ISSUE THREAD

**Issue by djKooks** [amix/vimrc#359]
Hello. First, thanks for great project! It makes me happy using vi.
I just installed and looking on it, and it seems cursor color on edit mode seems almost invisible for me.
<img width="738" alt="screen shot 2017-10-27 at 16 28 25" src="https://user-images.githubusercontent.com/1720209/32092620-4a3dbde6-bb34-11e7-8684-a360e4975e59.png">

Is there a way to just change this one?
Thanks.

**Comment by gauravojha** [comment]
Are you using a Mac? In my case I had to change the cursor cursor by going to my Terminal Preferences and changing the Cursor's color, which was quite dark to begin with. Could be something similar for your case as well. But then again, I don't know if you can use separate cursor colors for your terminal and a different cursor color for vim. Hope this helps.

**Comment by djKooks** [comment]
@gauravojha Thanks! I'll try on.
