### ISSUE TITLE
colorscheme set in both basic and extended.vimrc

### ISSUE THREAD

**Issue by alphaCTzo7G** [amix/vimrc#364]
Hi

I noticed that colorscheme is defined in both the extended and basic.vimrc. 

Since the "awesome" version of this vimrc already includes the basic version, perhaps the colorscheme should be only defined in the basic.vimrc.

I can do a PR. Let me know what you guys think?

**Comment by lartpang** [comment]
I think , extended file is suitable for "awesome" version... It`s efficient...

**Comment by alphaCTzo7G** [comment]
Not sure what you mean.. There is a extended.vim and basic.vim in the vimrcs.

Both define a color scheme.

The "awesome" version loads both the basic.vim and the extended.vim, so you load a colorscheme and then load another colorscheme, when vim is started. The basic. vim defines a lot of good settings, so we do need that in the "awesome" version. Whats the point of that? 

The basic. vim defines a lot of good settings, so we do need that in the "awesome" version. What I was suggesting, in case I wasnt clear is to remove the color definition from "extended.vim" and only define it in "basic.vim"

**Comment by anuragroy11** [comment]
Can you tell me how to change the color scheme, suppose I want to use the default color scheme of my terminal in vim(in my case iTerm2)?

**Comment by alphaCTzo7G** [comment]
use `:color desert` while in vim. 

Or you can put a line such as:

`color desert` in your personal .vimrc, to override the default colorscheme set by this vimrc.

**Comment by alphaCTzo7G** [comment]
Here are the 2 places color is set in this vimrc plugin:

`Basic.vim:`
https://github.com/amix/vimrc/blob/3753456a09188f78f3924820dbcac114c412c088/vimrcs/basic.vim#L156

`extended.vim:`
https://github.com/amix/vimrc/blob/3753456a09188f78f3924820dbcac114c412c088/vimrcs/extended.vim#L32

**Comment by anuragroy11** [comment]
Thank you very much! 
[I got it](https://imgur.com/DVl9htt)
But lightline is not co-operating. Do you know I can have lightline also have the color scheme of the terminal?

**Comment by amix** [comment]
@alphaCTzo7G some people just use the basic.vim (this is the basic version of the vimrc) 👍. This is why we define it twice.

**Comment by thevirtuoso1973** [comment]
@amix Is there any need to actually set it twice? We could remove it from extended.vim with no consequence. 
It took me a while to realize why my colorscheme was not changing when I just edited the basic.vim file.

@anuragroy11 A bit late but you can change the colorscheme of lightline in the plugins_config.vim file.
