### ISSUE TITLE
Upgrade repo from Pathogen to Vundle or something else

### ISSUE THREAD

**Issue by alphaCTzo7G** [amix/vimrc#365]
I wrote some arguments for upgrading from Pathogen to Vundle.

https://github.com/amix/vimrc/issues/356#issuecomment-344671341

What do you guys think?

**Comment by amix** [comment]
It seems like Tim is back maintaining Pathogen. Personally, I would not do this unless we are forced to.

This vimrc works with both NeoVim and Vim8 👍
