### ISSUE TITLE
different installation location

### ISSUE THREAD

**Issue by dimitrissch** [amix/vimrc#366]
Is it possible to relocate installation to another folder.I tried relocating the folder to $XDG_CONFIG_HOME/vim
modifying vimrc as follows
`set runtimepath+=$XDG_CONFIG_HOME/vim
source $XDG_CONFIG_HOME/vim/vimrcs/basic.vim
source $XDG_CONFIG_HOME/vim/vimrcs/filetypes.vim
source $XDG_CONFIG_HOME/vim/vimrcs/plugins_config.vim
source $XDG_CONFIG_HOME/vim/vimrcs/extended.vim
set undodir=$XDG_CACHE_HOME/vim/undo
set directory=$XDG_CACHE_HOME/vim/swap
set backupdir=$XDG_CACHE_HOME/vim/backup
set viminfo+='1000,n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME
try
source $XDG_CONFIG_HOME/vim/my_configs.vim
catch
endtry`
but vim seems to fail to load plugins like syntastic or the color scheme.Is this supported or any standard way to do it?

**Comment by amix** [comment]
This plugin relies on https://github.com/tpope/vim-pathogen — please see their documentation if this is possible (unsure if it is).
