### ISSUE TITLE
How can I install Pydiction in vim  base on your vimrc?

### ISSUE THREAD

**Issue by JerryZheng89** [amix/vimrc#367]
I want use the key "TAB"  to achieve the function of "Tab-complete Python code", but I don't konw how add python_pydiction.vim into the extended.vim.
python_pydiction: [https://github.com/vim-scripts/Pydiction](url)

**Comment by celsopneto** [comment]
Try to use Pydiction's instructions to install via Pathogen.
Just change the 
]`cd ~/.vim/bundle` 
to 
`cd ~/.vim_runtime`
and
`git clone https://github.com/rkulla/pydiction.git`
to
`git clone https://github.com/rkulla/pydiction.git sources_non_forked/Pydiction`

As instructed on https://github.com/amix/vimrc#how-to-include-your-own-stuff

**Comment by JerryZheng89** [comment]
Dear amix:

    thanks for your answer.  With your suggestion:

       I add three statements in my 'my_configs.vim', which shows below:

             filetype plugin on
             let g:pydiction_location = '/home/jerry/.vim_runtime/sources_non_forked/Pydiction/complete-dict'
             let g:pydiction_menu_height = 3

        but when I open a 'c' file,for exmaple 'main.c'，It  shows warning:

            Loading libclang failed, completion won't be available. Consider setting g:clang_library_path.

       So, I add two statements in my 'my_configs.vim', which shows below:

             let g:clang_use_library = 1
             let g:clang_library_path = '/usr/lib/llvm-3.8/lib/libclang.so'

       Final, it won't show the warning anymore, But it is useless to the function of code-completion for the C file
       some blogs  shows that  the plugin clang_complete  is  very greatful, but it has to recompile the VIM to add the ability of  support the plugin written with the python language.  Does it will calls any negative effect on the whole system of the vim baed on your vimrc, when I install the clang_complete?

**Comment by amix** [comment]
@JerryZheng89 please ask in Pydiction
