### ISSUE TITLE
update_plugins.py broken in Python 3.x, now requires Python 2.x

### ISSUE THREAD

**Issue by jokeyrhyme** [amix/vimrc#368]
Hi, thanks so much for sharing this configuration!

I've been using this for quite a while now, and I've always used Python 3.x to execute update_plugins.py

However, there was a recent change, and now it only works with Python 2.x

```
  File "/Users/rwaldon/.vim_runtime/update_plugins.py", line 92
    print zip_path
                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int zip_path)?
```

https://github.com/amix/vimrc/blob/master/update_plugins.py#L92

The workaround (switching back to Python 2.x) isn't a big deal for me, just thought you'd like to know :)

**Comment by amix** [comment]
Should already be fixed
