### ISSUE TITLE
After upgrade of macOS High Sierra, I found "gv" doesn't work in visual mode

### ISSUE THREAD

**Issue by hellodudu** [amix/vimrc#370]
ITerm2 3.1
vim 8.0

**Comment by RameshSippy** [comment]
@hellodudu since you are using macOS High Sierra, aren't you facing any error asking you to restart the server - the `YcmRestartServer` error?

**Comment by amix** [comment]
Have the same issue, will take a look 👍

**Comment by RameshSippy** [comment]
I wonder why you closed this issue if you too are facing the same?!
