### ISSUE TITLE
Multiple Files Listing

### ISSUE THREAD

**Issue by gauravojha** [amix/vimrc#372]
On the main page, the README shows that if multiple files are open, they are shown in a bar on the top. However, I cant seem to see any when I installed the awesome version.

![image](https://user-images.githubusercontent.com/10114860/33701602-8299fcc6-daed-11e7-968e-11566e6bdbfe.png)

Can someone please help. I see the same issue on both a Mac and Ubuntu. Listing the multiple files below using **:args**

**Comment by amix** [comment]
Please see this: http://vim.wikia.com/wiki/Using_tab_pages
