### ISSUE TITLE
None of my plugins are working

### ISSUE THREAD

**Issue by nix1947** [amix/vimrc#373]
~/.vim_runtime on master [?]
➔ sh install_awesome_vimrc.sh    

I install the awesome_vimrc.sh, but when trying to work none of the plugins are working. do i need to install plugin

**Comment by Esslamb** [comment]
Plugins are handled via https://github.com/tpope/vim-pathogen. I would suggest giving this a read and maybe providing some more details in regards to your exact problem and the hardware you are using.

**Comment by nix1947** [comment]
Fixed
