### ISSUE TITLE
no cursor when substitute

### ISSUE THREAD

**Issue by despagito** [amix/vimrc#374]
how can I configure substitute cursor back? it's hard to know which occurrence i'm substituting.

**Comment by amix** [comment]
I am unsure which feature this refers to?

**Comment by FTOD-LAB** [comment]
I have the same issue : the cursor is not visible when doing like 
`:%s/a/b/gc`
when we want to choose if the current match should be substituted, we don't know which one is.

**Comment by amix** [comment]
I still don't understand the problem :-/ Please reopen with a screencast if possible.
