### ISSUE TITLE
Error messages take up ~30% of my workspace. Some of them (file not found) are just due to my project file structure and thus aren't relevant and yet pop up every time I save. How can I configure errors/warnings?

### ISSUE THREAD

**Issue by BrianJMRogers** [amix/vimrc#377]
Howw can I either A) suppress certain warnings/errors B) tell the error message to use the minimum number of lines possible C) disable error tracking?

Attatched is an example image. Every time I save the file, this message takes up about 30% of my workspace (~8 lines of blank space!). 

![img_4439](https://user-images.githubusercontent.com/16455932/34216027-16484216-e575-11e7-9787-39c3c5dfdfa9.JPG)

**Comment by seanM29** [comment]
#237 
maybe this will help you
