### ISSUE TITLE
Commenting in Matlab script uses wrong character

### ISSUE THREAD

**Issue by elmerehbi** [amix/vimrc#382]
I am not sure if this is an issue with your vimrc or vim in general. Commenting code in a Matlab script (i.i. `.m`) uses the wrong commenting character `/*` instead of `%`.

**Comment by amix** [comment]
@elmerehbi `.m` is usually regarded as objective c files. You would need to Vim to treat the file as a `Matlab` script.

E.g. adding this to you my_configs.vim: `au BufNewFile,BufRead *.m set ft=matlab` (haven't tested this out)

**Comment by elmerehbi** [comment]
According to this [filetype file](https://github.com/vim/vim/blob/master/runtime/filetype.vim) (line 953) it is already set, isn't it?

**Comment by amix** [comment]
It seems to call `dist#ft#FTm()`, I would recommend that you override it or figure out how Vim autodetects matlab files.
