### ISSUE TITLE
entering / leaving goyo doesn't restore dark background

### ISSUE THREAD

**Issue by ntom** [amix/vimrc#385]
Hi,

To reproduce: 
Ubuntu 16.04 server clean install
Install amix/vimrc
Open file
Enter <leader>z - it looks great, the background is dark... when i try <leader>z again ... 
It returns but now the background is light grey...
You have to then :set background=dark to go back to the original state

If you then <leader>z again, Goyo is dark... and then <leader>z again and this time background is suddenly none/default terminal background..

Clearly not expected behaviour and some kind of a bug..

**Comment by amix** [comment]
Not something I can reproduce, what color scheme do you use?
