### ISSUE TITLE
Ack error, did i do something wrong?

### ISSUE THREAD

**Issue by seanM29** [amix/vimrc#387]
I use  this to install awesome vimrc, and installed it successfully.

`
git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
sh ~/.vim_runtime/install_awesome_vimrc.sh
`
but when i use ack to search "debug", it occurs an error.
it prints
`
E492: Not an editor command: Ack -i debug
`
is there something i missed?

**Comment by cnlzxin** [comment]
install ack

**Comment by amix** [comment]
You can also install other faster alternatives:
http://betterthanack.com/

I use `Ag`
