### ISSUE TITLE
How do I disable a plugin? (ex. syntastic)

### ISSUE THREAD

**Issue by adbugger** [amix/vimrc#388]
I'm working on a project where I do not need syntax checking every time I save a file. I find myself having to type :lclose every time I  save, to close the syntastic window because it can't find a few header files.

I was wondering if there's an easy way to disable just that one plugin?

**Comment by swapnil823** [comment]
Try this in ~/.vim_runtime/my_config.vim

'''
let g:syntastic_always_populate_loc_list = 0
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0
'''

**Comment by alphaCTzo7G** [comment]
This is easier to do if you have Vundle. Where you can comment out the plugins, in your vimrc. 

If you are using `Pathogen`, you will have to manually convert this plugin so its compatible with Vundle/Vimplug. 

Or if you want to stick with Pathogen, you can move the syntastic plugin out of the load path. 

Also, usually a lot of plugins have an option to switch it off by setting a parameter to 0. You can take a look at the docs.

**Comment by pv1551973** [comment]
@swapnil823 I tried the solution that you proposed in the context of issue [393](https://github.com/amix/vimrc/issues/393) . But I get the following errors:

> let g:syntastic_check_on_wq = 0
> : command not found
> bash: catch: command not found
> bash: endtry: command not found

Any suggestions on how to get rid of these errors?
