### ISSUE TITLE
Can't disable tabline showing

### ISSUE THREAD

**Issue by haroldrandom** [amix/vimrc#392]
Hi, guys.

I am using the lastest version of this vimrc. I want to remove the top tabline from my vim, but anyhow I just can't do it after I have tried many ways to set.

I think putting ```set showtabline=0``` in my `.vimrc` is the ultimate mean to do it, but it didn't work.

```
" my .vimrc
set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim

try
source ~/.vim_runtime/my_configs.vim
catch
endtry

set showtabline=0
```

Any suggestions will be appreciated. Thx!

**Comment by amix** [comment]
Can reproduce this, but have no idea why it happens. Most likely it's one of the plugins that override it 👀

**Comment by harry75369** [comment]
Also don't know why. But there is a workaround by adding the following line to your vimrc
```
autocmd FileType * set showtabline=0
```

**Comment by harry75369** [comment]
Further investigation shows the problem probably lies in
https://github.com/amix/vimrc/blame/master/sources_forked/set_tabline/plugin/set_tabline.vim#L29

Comment out this line, and add `set showtabline=0` into your vimrc will solve this problem.
