### ISSUE TITLE
issue with saving main.cpp

### ISSUE THREAD

**Issue by pv1551973** [amix/vimrc#393]
<img width="610" alt="screen shot 2018-02-26 at 2 30 02 pm" src="https://user-images.githubusercontent.com/35186366/36652242-ac5633aa-1b01-11e8-9c96-ed17c85e73f3.png">
When the file main.cpp (in a C++ file system) is saved after even a trivial change, a bunch of errors are generated, which curtail the scrollable screen space to almost 50%. Not sure what is the logic according to which this is happening. To replicate this, just create two files, one main.cpp and another code.hpp with a template declaration/definition. When you save changes to the .hpp file, nothing happens. But when you make any change to the main.cpp, you immediately start noticing the above issue. Often the file has to closed and reopened to get the entire scrollable screen window in vim.

Screenshot attached to this post.

Also curious to know whether this issue can be addressed by commenting out any line in a relevant .vimrc file, if this is an intended feature and not a defect.

**Comment by fbunt** [comment]
I don't think think this has anything to do with this project.

It looks like you have some sort of plugin installed that tries to compile your project when main.cpp is changed. The error messages seem to indicate that the plugin isn't turning on your compiler's C++11 extensions and maybe more so when the plugin tries to compile, it gets errors. It's just showing you the errors. Try reconfiguring the plugin you are using, turn it off, or remove it.

**Comment by pv1551973** [comment]
I have not made any change to the files that I have downloaded from this site. Inside the vimrcs directory, there is a plugins_config.vim file. Based on your reply, I checked the file for any section related to C++, but couldn't find any. I am attaching the file for your reference. It would be of help if you could point out to me the source of this issue based on plugins_config.vim, since you believe that it is due to some plugins that might have been installed and invoked from within the context of vim.


[plugins_config.vim.txt](https://github.com/amix/vimrc/files/1773418/plugins_config.vim.txt)

**Comment by fbunt** [comment]
Whoops, I was wrong. This is caused by the syntastic plugin running a check after writing the file. Somehow the auto check has been turned on for you. Check out this issue: #388.

**Comment by pv1551973** [comment]
Thanks. I have followed the steps outlined in the previous issue. If that works for me, I would close this issue.

**Comment by pv1551973** [comment]
An update is that is the solution suggested by swapnil823 in response to issue [388](https://github.com/amix/vimrc/issues/388) didn't work for me. I am trying the other option wherein the plugins could be selectively disabled using Vundle. Ran into some issues with the installation of Vundle and have a raised a ticket for the same ([859](https://github.com/VundleVim/Vundle.vim/issues/859).

**Comment by amix** [comment]
We ship with an almost vanilla version of syntastic. Please read the documentation / ask on their project page: https://github.com/vim-syntastic/syntastic
