### ISSUE TITLE
Errors while sourcing .vimrc

### ISSUE THREAD

**Issue by pv1551973** [amix/vimrc#395]
I get a bunch of errors (apparently syntax related) while trying to source the .vimrc file. Attached is a log of the errors. Also attached is the .vimrc file.
[vimrc.txt](https://github.com/amix/vimrc/files/1778008/vimrc.txt)
[errors_source_vimrc.txt](https://github.com/amix/vimrc/files/1778010/errors_source_vimrc.txt)

**Comment by amix** [comment]
Looks like you have your vim badly configured. Please ensure that you run Vim 7/8 (and not regular Vi)
