### ISSUE TITLE
How to avoid unexpected indent at the start of each line in Vim?

### ISSUE THREAD

**Issue by huangmozhilv** [amix/vimrc#396]
The awesome version was installed on my Mac.

I copied several lines from Vim to clipboard using "Cmd+C" and pasted in python from terminal. It returned "IndentationError: unexpected indent". Below's a screenshot of multi-lines selection in Vim:
![image](https://user-images.githubusercontent.com/26662685/36943072-726fcb90-1fbd-11e8-8250-0bb251ef5c87.png)

From the image, we can see one-space ident at the start of each line. But when I move the cursor, no space would be highlighted by the cursor.

Question: how to delete these unexpected indents? Is there any way to set the .vimrc file?

Thanks.

**Comment by amix** [comment]
You can go into the visual mode (`CTRL+V`), select all the white-space and press `x`.
