### ISSUE TITLE
Marged

### ISSUE THREAD

**Issue by Seliniux777** [amix/vimrc#398]
" 'master' of https://github.com/amix/vimrc: (35 commits)
  Updated plugins
  Fixed a conflict between yankstack and surround
  Fixed amix#321
  Fixed amix#325
  Fixed https://github.com/tpope/tpope-vim-abolish
  Updated plugins
  Updated vim plugins
  Speed up download ~4x
  Updated plugins and added vim-abolish
  Allow to install custom plugins
  Updated plugins
  Fixed amix#246
  Fixed amix#263
  Updated screenshots
  Updated the readme (a cleanup)
  Updated the logo
  Fixed amix#278
  Fixed amix#279
  Updated vim plugins
  Removed ack.vim
  ...`

**Comment by Seliniux777** [comment]
`resolve conflicts `

**Comment by amix** [comment]
I am unsure what the issue is here. You might want to try to reinstall the installation.
