### ISSUE TITLE
[PROPOSAL] Snipmate doesn't play well with YouCompleteMe - switch to UltiSnip?

### ISSUE THREAD

**Issue by borowskiio** [amix/vimrc#400]
The awesome configuration includes snipmate as the go to snippets plugin. Unfortunately it doesn't play well with YouCompleteMe.

Should it be replaced with UltiSnip which development is way more active and it works as a charm right away with YouCompleteMe?

**Comment by amix** [comment]
I'll check out UltiSnip, thanks for the recommendation.

**Comment by amix** [comment]
I've checked out UltiSnip, but the +python requirement is a hard sell.
