### ISSUE TITLE
starting vim takes 3 seconds to load when using the awesome version

### ISSUE THREAD

**Issue by mbuyco** [amix/vimrc#401]
when you install:
`sh ~/.vim_runtime/install_awesome_vimrc.sh`

starting vim takes 3 seconds to load

**Comment by alphaCTzo7G** [comment]
The awesome version does load a number of plugins.. frankly for the amazing plugins and the settings that @amix has tested and built into this.. 3 secs is nothing.

My guess is most people using this plugin only have 1 vim session running and they open multiple files in the same sessions. 

Other editors with similar configs will take a lot more time to load.

**Comment by amix** [comment]
If speed is important, I would recommend using the basic version 👍

Or upgrading your hardware 😄
