### ISSUE TITLE
If I wanted to download  a new color scheme (Dracula) where would I save it so that I could change my vim color scheme

### ISSUE THREAD

**Issue by KevinBaileyCrum** [amix/vimrc#404]
I wanted to add Dracula https://draculatheme.com/vim/
I noticed extended.vim has the color scheme set. Where should I save the above theme so that I could use that color scheme instead

**Comment by Akusem** [comment]
I think it's in the `~/.vim_runtime/sources_forked/ ` folder that you should save the colorscheme if I remember well
