### ISSUE TITLE
fatal error: haha.h: No such file or directory

### ISSUE THREAD

**Issue by SheilaLundin** [amix/vimrc#407]
When I save a c file which has "#include <haha.h>"
How to disable this check

**Comment by KevinBaileyCrum** [comment]
you may be getting a syntastic warning.  You may have to use
`:SyntasticToggleMode`
to set it to passive

**Comment by amix** [comment]
We have switched to Ale, and you can see here how to disable it for various file types:
https://github.com/dense-analysis/ale#faq-disable-linters
