### ISSUE TITLE
nerdtree set tree on left not work（mac 10.13.4）

### ISSUE THREAD

**Issue by fyeeme** [amix/vimrc#409]
edit  plugins_config.vim   and then update the blew variable not work , always tab show on right and window width can not changed 

```
 let g:NERDTreeWinPos = "left"  //not work
 let g:NERDTreeWinSize=35 .  // also not work
```
anyone how how solve it？ 
![image](https://user-images.githubusercontent.com/6078758/38405196-41df3102-39a1-11e8-9f29-bc7a8632b3b6.png)
![image](https://user-images.githubusercontent.com/6078758/38405292-c30732ac-39a1-11e8-96eb-49dbe023d8c4.png)

**Comment by flavioribeiro** [comment]
I removed https://github.com/amix/vimrc/blob/master/vimrcs/plugins_config.vim#L80 and it's fine now but I'm wondering if the stuff on `my_configs.vim` shouldn't overwrite this one?

**Comment by alphaCTzo7G** [comment]
@fyeeme , @flavioribeiro , if you want to redefine the variable you should redefine it after the `plugins_config.vim` has been loaded.

Are you doing that?

**Comment by adampei** [comment]
I have the same problem.

**Comment by amix** [comment]
From your `.vimrc` try to remove the try catch clause:
From:
```
try
source ~/.vim_runtime/my_configs.vim
catch
endtry
```
To:
```
source ~/.vim_runtime/my_configs.vim
```

It's not something I can reproduce.
