### ISSUE TITLE
ALE commands not working

### ISSUE THREAD

**Issue by amjltc295** [amix/vimrc#411]
I'm not familiar with ALE (I used the Syntastic plugin), but it does not seem to work after installing the latest vimrc. 
I could do `:help ale-go-to-definition`, but `:A` \<tab\> only returns `Abolish  AddTabularPattern  AddTabularPipeline`, no ALEToggle, ALEGoToDefinition, ALEFix, etc. The sytax checkers do not seem to work as well. 
Do I need to set up anything for ALE? Flake8 is already installed for python.

**Comment by DeGuitard** [comment]
I'm getting the same issue as you. Doc is working, but no ALE* command is available.

**Comment by jiguanglizipao** [comment]
I also meet this issue. `:help ale` seems good but ALE* commands are disable.

**Comment by prathameshnetake** [comment]
Facing same issue

**Comment by prathameshnetake** [comment]
ALE is supported only in vim 8 so install vim 8 first [http://tipsonubuntu.com/2016/09/13/vim-8-0-released-install-ubuntu-16-04/](url). 
Make sure you install linter globally in case with eslint or something

**Comment by DeGuitard** [comment]
@prathameshnetake Nice catch, I indeed am using vim 7.4

I don't know if it would be useful to add on the README page that Vim 8.0 is required, since Vim 8.0 is the latest stable version. Yet three of us had this issue without understanding why.

**Comment by amjltc295** [comment]
@prathameshnetake thanks, updating Vim to 8.0 works for me. `sudo apt-get install vim` would say vim 7.4 is the latest version in my environment though. I agree with @DeGuitard  that adding Vim 8.0 to the requirement would be nice.

**Comment by Weilor** [comment]
I am using vim 8.0.1283, but the ale plugin is still working

**Comment by hushicai** [comment]
In my case, i map `<leader>gd` to `<Plug>ale_go_to_completion`, but not working.

But `:ALEGoToDefinition` works.

**Comment by rennelou** [comment]
i'm using vim 8.1 from official arch respos and still not working for me too

**Comment by amix** [comment]
Yep, Ale requires Vim 8 👍

**Comment by Shellcat-Zero** [comment]
I was unable to get ALE working with Vim 8 and switched to [coc.nvim](https://github.com/neoclide/coc.nvim), where coc or its plugins complained that it needed a more recent version of Vim 8. It is likely here that ALE is failing silently. The solution for me was compiling and installing vim from source, but I have not tested anything with ALE, and frankly, such silent failures indicate to me that ALE is not mature enough to rely upon.
