### ISSUE TITLE
colorscheme issues

### ISSUE THREAD

**Issue by HansSJTU** [amix/vimrc#416]
If there are two colorschemes with same name in both sources_non_forked and sources_forked, it will load one in sources_non_forked.

More specifically,

I am using gruvbox as the colorschemes, I have one gruvbox in sources_forked and one gruvbox in sources_non_forked, and vim will load the configure of gruvbox in sources_non_forked.

**Comment by Arnie97** [comment]
Maybe you could just put your own gruvbox in `my_plugins`?

**Comment by amix** [comment]
I would recommend trying @Arnie97 solutions.
