### ISSUE TITLE
A little suggestions

### ISSUE THREAD

**Issue by TillLindemann** [amix/vimrc#417]
The fuzzy file finder,which in this vimrc is the ctrlp.vim, is not actually a good one,it's very slow,when your files are too many. I recommend you guys use the Leaderf, which can be found  in github by typing on it.It's  actually ten times faster than ctrlp, and it can be even faster by adding C-extensions.

**Comment by alphaCTzo7G** [comment]
Some other tips for speeding up Ctrlp are here: https://stackoverflow.com/a/22784889/4752883

**Comment by amix** [comment]
You are welcome to configure this on your own installation. With my computer hardware, ctrlp.vim is very fast.
