### ISSUE TITLE
multi-cursor does not work

### ISSUE THREAD

**Issue by sidazhang** [amix/vimrc#42]
The only way I could get it to work was to delete yankring and revert the key mapping back to ``` '<C-n>' ``` (Rather than what you mapped to ``` '<C-s>' ```)

I am using 
```
MacOS 10.9.1
iTerm2
vim version 7.3
I pull the repo and did an awesome install and made no other changes
```

**Comment by liangguohuan** [comment]
the same here, my system is ubuntu 14.04
\<C-s\> is nothing to do when i use the default config
change with `let g:multi_cursor_next_key="<F6>"` then it will always trigger error:
>
and sometimes it cause `endless loop`

```
Key '(multiple-cursors-apply)<80><fd>S(multiple-cursors-detect)' cannot be replayed at 1 cursor location
```
