### ISSUE TITLE
set clipboard^=unnamed as default

### ISSUE THREAD

**Issue by alphaCTzo7G** [amix/vimrc#421]
I have seen this in a lot of vimrc:

`set clipboard^=unnamed`

https://github.com/mhinz/vim-galore#clipboard-usage-linux-bsd-

This will enable user to copy and paste using the `primary` clipboard and not have to type "*p". While the `*` registers is great, my guess is most people using vim, dont care too much about it.

Do you guys think this should be implemented as default?

**Comment by Arnie97** [comment]
One major drawback is that, delete operations `x` or `d` will override the system clipboard unexpectedly. So you have to use the blackhole register or a named register for safe delete operations, and thus probably not saving key strokes.

**Comment by amix** [comment]
Personally, I never found this super useful — most of my Vim usage happens in MacVim, where the global clipboard is supported via CMD+C / CMD+V.

Like @Arnie97 I also don't want to see Vim's clipboard pollute the system clipboard.

Anyhow, something to ponder about 😊
