### ISSUE TITLE
How do I gracefully remove certain plug-ins when I don't need them.

### ISSUE THREAD

**Issue by Abson** [amix/vimrc#422]

**Comment by alphaCTzo7G** [comment]
If you are using `Pathogen`, just delete them from the `sources*` folder..

And remove any associated plugin related settings from the different `vimrcs`..

**Comment by Abson** [comment]
@alphaCTzo7G I did try this way, but it just ungracefully, when I want to re-pull the latest version of amix/vimrc, those plug-ins will be reinstalled with this operation that's what I don't want to see.

**Comment by amix** [comment]
What @alphaCTzo7G stated. Unfortunately, every time you pull from my version you'll need to delete them again.

In the future, I'll see if there is an elegant way to resolve this.
