### ISSUE TITLE
Remove MRU.vim

### ISSUE THREAD

**Issue by alphaCTzo7G** [amix/vimrc#423]
`ctrp.vim` already provides all the functionality that `MRU.vim` provides. 

Perhaps `MRU.vim` can be removed so that people are introduced and use the full power of `ctrlp`? This will also reduce the number of plugins that VIM loads and perhaps speed up VIM

**Comment by amix** [comment]
I use both of these:

* ctrlp.vim to find files, maybe some that I have never opened before
* MRU.vim to open recent files. I find the UX of MRU.vim better than ctrlp.vim
