### ISSUE TITLE
cannot find my plugin

### ISSUE THREAD

**Issue by Mod233** [amix/vimrc#424]
when i finish run
```bash
sh ~/.vim_runtime/install_awesome_vimrc.sh
```
and when I enter 
```bash
$ vim a.cpp
```
I can see dark vim, but I cannot find all my plugins installed before.Could you please tell me what should I do to find back my plugins...

**Comment by alphaCTzo7G** [comment]
What do you mean by plugins installed before?

Were you using `pathogen` or `Vundle` or something else? Depending on the installation method the location will be different.

This plugin installs the plugins from this repo into `~/.vim_runtime/sources_forked` and `~/.vim_runtime/sources_non_forked` 

Your previous plugins may be under `~/.vim/bundle`

**Comment by Mod233** [comment]
Ask for your help.
I used to use Vundle to install the plugins.
Yes , my previous plugins are under 
```bash
 ~/.vim/bundle
```
should I mv all the file in ~/.vim/bundle to 
```bash
~/.vim_runtime/sources_forked 
~/.vim_runtime/sources_non_forked
```
to get my previous plugins work well?

**Comment by Mod233** [comment]
@alphaCTzo7G should I mv all my plugins in 
```bash
~/.vim/bundle
```
to
```
~/.vim_runtime/sources_forked 
~/.vim_runtime/sources_non_forked
```
to get my previous plugins work well?

**Comment by alphaCTzo7G** [comment]
`pathogen.vim` located under `~/.vim_runtime/autoload/pathogen.vim` by default loads the plugins located under `~/.vim/bundle`. So the plugins located in `~/.vim/bundle` should be loaded fine. 

However, if you want all your plugins under one directory `~/.vim_runtime`, you can move it to the `~/.vim_runtime/my_plugins` directory. The `my_plugins` directory is for any plugins that you installed for yourself but that is not part of the `amix/vimrc`..

**Comment by Mod233** [comment]
thanks for your help :-D

**Comment by amix** [comment]
Awesome help, @alphaCTzo7G
