### ISSUE TITLE
not an issue an idea: line numbers and moving the cursor with the mouse

### ISSUE THREAD

**Issue by borayuksel1903** [amix/vimrc#435]
Just downloaded the amazing .vimrc, and I can say, it is pretty amazing :)
Couple things would make it better in my opinion are 'set number' and 'set mouse=a'. 
In my experiences, they have been very useful to me, especially when debugging, and moving the cursor with the mouse just enables another option for the user, and it would make it even more AMAZING.

**Comment by alphaCTzo7G** [comment]
I did mention something like this here.. https://github.com/amix/vimrc/pull/375#issuecomment-372684253.

I do find relative line numbers very useful.. Even more useful for moving quickly is the `easy-motion` plugin: https://github.com/easymotion/vim-easymotion. But it may be better to get used to the default vim motion commands `(, }, p, s, e, w`.. etc before moving to easy-motion.. 

Using the mouse is probably heresy in the VIM world :)

**Comment by amix** [comment]
Thanks for answering this, @alphaCTzo7G 🙏

**Comment by amix** [comment]
Generally, I would recommend that you install and configure your own things via this:
https://github.com/amix/vimrc#how-to-include-your-own-stuff

This is just how I like to use vim, and it's meant as a starting point.
