### ISSUE TITLE
Fonts not working in gui_gtk2

### ISSUE THREAD

**Issue by danielamaya** [amix/vimrc#436]
Before I submit a pull request, just want to make sure I'm not missing anything here.

I'm running Gentoo with KDE Plasma, and gVim installed. I also have IBM Plex, Hack, and Source Code Pro installed. When opening gVim, the fonts were spaced out and generally looked terrible.

Looking in `extended.vim` I found the following gfn format under `gui_gtk2`:

```
elseif has("gui_gtk2")
    set gfn=IBM\ Plex\ Mono:h14,:Hack\ 14,Source\ Code\ Pro\ 12,Bitstream\ Vera\ Sans\ Mono\ 11
```

I changed that line to the following, and everything worked:

```
set gfn=IBM\ Plex\ Mono\ Semi-Bold\ 10,Hack\ Bold\ 10,Source\ Code\ Pro\ Semi-Bold\ 10
```

Reopened gVim and the font looked great. Before I submit a pull request, I just want to make sure that I am not wrong in my assumption, which is that gui_gtk2 does not support the format `<font name>:h<font size>`. Since IBM Plex Mono is on my system, it applied the first font in `set gfn=`, which has the incorrect format.

**Comment by bdefore** [comment]
I'm unable to get Plex (or Hack) to render on debian with either the existing way or your suggestion.

**Comment by alphaCTzo7G** [comment]
`gui_gtk2` seems to have the following format:

```
if has("gui_gtk2") || has("gui_gtk3")
    set guifont=Courier\ New\ 11
```

So, it mush be a typo in the `extended.vim`

Ref: 
1. http://vim.wikia.com/wiki/Setting_the_font_in_the_GUI
2. https://gist.github.com/Zardoz89/9546383#file-vimrc-L111
