### ISSUE TITLE
Vim the ultimate vim configuration

### ISSUE THREAD

**Issue by gearchild** [amix/vimrc#438]
I've been trying to install this configuration for a minute now, and I'm typing what's been posted i.e: 

git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtimesh ~/.vim_runtime/install_awesome_vimrc.sh 

but when I do, all I get back is fatal: too many arguments.  

Any suggestions?  Am I doing something wrong?

**Comment by sbr0** [comment]
Those are 2 separate commands. First clone the git repo with:
git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
Then run the setup script:
sh ~/.vim_runtime/install_awesome_vimrc.sh
