### ISSUE TITLE
How to add a new plug in?

### ISSUE THREAD

**Issue by Yvonne-Ng** [amix/vimrc#439]
Hi, I tried following the instruction in the README.md to add a new plugin by git cloning, https://github.com/bartman/git-wip but after a couple of trials it seems like vim-awesome is not able to pick up the plugin. Do I need to set some configuration somewhere? Thanks

**Comment by akiraandy** [comment]
I'm also confused by this.

**Comment by alphaCTzo7G** [comment]
do `cd ~/.vim_runtime/my_plugins git clone https://github.com/bartman/git-wip.git`

This plugin assumes that your personal plugins will be located in the `my_plugins` directory under `vim_runtime`. 

This is how I use it.

**Comment by Yvonne-Ng** [comment]
Do I need to add lines in any of the config files? I tried that but I still couldn't use the functionality in there. I am debating removing awesomevim and switching to another vim plugin manager

**Comment by alphaCTzo7G** [comment]
No you don't. It works perfectly for me, as long as you have followed the instructions. Because of the customizability of VIM, its kindof assumed that you will have to google around and figure some things for yourself.. and will happen regardless of what vim plugin manager or plugin you use..

**Comment by Radiocolectivo** [comment]
I'm having the exact same problem, I'm trying to use emmet-vim and followed this instructions, it just doesn't work, I will keep working on it to find out why is not working. Please if anybody had the same issue maybe is just the plugin.

**Comment by setoelkahfi** [comment]
> I'm having the exact same problem, I'm trying to use emmet-vim and followed this instructions, it just doesn't work, I will keep working on it to find out why is not working. Please if anybody had the same issue maybe is just the plugin.

It just the plugin I guess. I installed this plugin `https://github.com/keith/swift.vim` inside `my_plugins` and it works.

**Comment by nicholasdixon** [comment]
I managed to get youcompleteme working, but not emmet-vim, is the emmet-vim plugin dependant on anything,

**Comment by Asia9847** [comment]
> I'm having the exact same problem, I'm trying to use emmet-vim and followed this instructions, it just doesn't work, I will keep working on it to find out why is not working. Please if anybody had the same issue maybe is just the plugin.

In fact, I met the same problem. Is there a solution?

**Comment by Asia9847** [comment]
I'm sure Emmet is working properly. Its shortcut requires Ctrl + y to press quickly, release and press comma.    Emmet是正常工作的，我最终发现是我操作的方式有问题，事实上应该ctrl+y同时按下，松开后按下逗号，模板成功被打印出来。
