### ISSUE TITLE
Move a line up and down with Alt[jk] key is not working.

### ISSUE THREAD

**Issue by aasril** [amix/vimrc#442]
This part

> " Move a line of text using ALT+[jk] or Command+[jk] on mac
> ```
> nmap <M-j> mz:m+<cr>`z
> nmap <M-k> mz:m-2<cr>`z
> vmap <M-j> :m'>+<cr>`<my`>mzgv`yo`z
> vmap <M-k> :m'<-2<cr>`>my`<mzgv`yo`z
> ```
> 
> ```
> if has("mac") || has("macunix")
>   nmap <D-j> <M-j>
>   nmap <D-k> <M-k>
>   vmap <D-j> <M-j>
>   vmap <D-k> <M-k>
> endif
> ```

I test the keys on vim and they're working but the shortcuts Alt+j or Alt+k are not.

```
vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
```

**Comment by aasril** [comment]
This is the output of :map for related keys.

```
v  ë             :m'<-2<CR>`>my`<mzgv`yo`z
v  ê             :m'>+<CR>`<my`>mzgv`yo`z
n  ë             mz:m-2<CR>`z
n  ê             mz:m+<CR>`z
```

I don't understand why the ë and ê characters instead of <M-j> and <M-k>.

**Comment by felixcra** [comment]
I didn't work for me either. I did not have the chance so far to try it out, but I guess you did also not install your vim with scheme support:
https://gist.github.com/jebberjeb/21711bcac6c883b3d3de

Furthermore it may be that your keystrokes are not perfectly forwarded to vim. Try to do `:<C-k><some_key>`. For example with CMD as <some_key> or alt and look if it shows you something.

**Comment by sadakmed** [comment]
ALT+[jk] is not working

**Comment by siahuat0727** [comment]
ALT+[jk] is not working too.
`:map`:
```
v  <M-k>         :m'<-2<CR>`>my`<mzgv`yo`z
v  <M-j>         :m'>+<CR>`<my`>mzgv`yo`z
n  <M-k>         mz:m-2<CR>`z
n  <M-j>         mz:m+<CR>`z
```
