### ISSUE TITLE
tabstop=4 settings inside the .vimrc are being overridden

### ISSUE THREAD

**Issue by 00h-i-r-a00** [amix/vimrc#443]
Hello,

I would like to add set `tabstop=4 ` to my .vimrc but somehow they are being overriden, that is 8 spaces are appearing instead of the desired 4. I am guessing this is being done by some plugin inside the vim configuration. Could anyone please help how to solve this? Thanks!

**Comment by amix** [comment]
Please read this how-to include your own configs and plugins:
https://github.com/amix/vimrc#how-to-include-your-own-stuff
