### ISSUE TITLE
Auto folding in markdown

### ISSUE THREAD

**Issue by Anudorannador** [amix/vimrc#445]
follow these steps:
1. touch test.md && vim test.md
2. insert some contents, must have 3 level, `# Level 1`, `## Level 2`, `### Level 3`
3. in the level 3, add json code like:
````
```json
 {
	"filed": "ddd",             // comments
	"ddd": "dde",             // comments
 }
```
````
4. edit the json, add fileds, modify or delete, or just using tab indent, and finally, codes will be auto folded.

![peek 2018-07-24 15-32](https://user-images.githubusercontent.com/7517242/43123481-e7ae8208-8f56-11e8-8f0d-41385c900ee6.gif)

**Comment by alphaCTzo7G** [comment]
Do you not like the autofolding?

This is probably happening because you are using `fenced-block` : https://github.com/tpope/vim-markdown

**Comment by Anudorannador** [comment]
@alphaCTzo7G No, I mean when I'm typing the  text, or say, insert mode,  autofolding happened....

**Comment by cmhe** [comment]
The default setting is pretty unusable and crazy for me.

Just recorded [this](https://asciinema.org/a/LrsD72DMNS9hkAIByTtrlpbgO).

**Comment by amix** [comment]
I'll include this in the official version 👍

**Comment by davidrossdegroot** [comment]
Thank you. I found the behavior quite annoying as well.
