### ISSUE TITLE
Ctrl+U returns : undefined variable: s:timer_id

### ISSUE THREAD

**Issue by ArvsIndrarys** [amix/vimrc#447]
Hi, 

whenever I am trying to use the ctrl-u shortcut (revert last change), I got that error that loops each time I make an input on my keyboard : 

```
Error detected while processing function <SNR>117_tick
line   34:
E121: Undefined variable: s:timer_id
E116: Invalid arguments for function timer_stop
line   35:
E108: No such variable: "s:timer_id"
```

The only other installed except amix/vimrc is [vim-go from fatih](https://github.com/fatih/vim-go) , installed from Vundle.

Vim version : `2:7.4.1689-3ubuntu1.2` . 
Has someone any idea on that issue?

**Comment by lkonga** [comment]
If I'm not mistaking it's related to the newly added smooth scroll plugin. Try updating to vim 8 as ubuntu ships with vim 7

**Comment by ArvsIndrarys** [comment]
You are right, it solved the problem. Thanks ! 
I tried an `sudo apt upgrade vim` before asking here but I didn't know another repository was needed to get the vim8 . 
It is also worth noticing that the undo went from `ctrl-u` to `u` on the new vim.
