### ISSUE TITLE
clang_complete is not working

### ISSUE THREAD

**Issue by 4Z4T4R** [amix/vimrc#450]
Installed a vanilla copy of clang_complete. `:omnifunc`, `:completefunc` and `:messages` report that `ClangComplete` is loading up just fine. Although, I am not getting any suggestions when editing cpp files... No other suggestion or code completion is installed except what's standard here.

Really want https://github.com/Rip-Rip/clang_complete to work here. What could be interfering?

**Comment by amix** [comment]
Please report in their repository. I don't think this is related to this vimrc.
