### ISSUE TITLE
scroll half page is slow

### ISSUE THREAD

**Issue by jnreynoso** [amix/vimrc#452]
They are very slow ` CTRL + U` and `CTRL + D`.

**Comment by geoboom** [comment]
I'm having the same issue

**Comment by Tiande** [comment]
just add this in your **my_configs.vim** file to disable it:
```vim
let g:loaded_comfortable_motion = 0
```

**Comment by wang-nima** [comment]
thanks @Tiande

**Comment by amix** [comment]
Thanks for answering, @Tiande
