### ISSUE TITLE
Use plasticboy's vim-markdown instead of tpope's vim-markdown

### ISSUE THREAD

**Issue by alphaCTzo7G** [amix/vimrc#453]
Plasticboy's vim-markdown (https://github.com/plasticboy/vim-markdown) is much more popular and has more features (folding included) compared to Tpope's vim-markdown (https://github.com/tpope/vim-markdown). 

Plasticboy's plugin is also more updated.

I recently switched to it and find it much more useful. As this plugin aims to provide the best plugins for new vim-users to get up to speed on VIM and its possible features quickly, it would good for others to have these features as well, by including it as the default markdown plugin.

**Comment by amix** [comment]
Thanks, @alphaCTzo7G. This is now done.

**Comment by AAlakkad** [comment]
@amix You might want to update the readme link as well :)
