### ISSUE TITLE
problems with accented characters (á,é,í,ó,ú...)

### ISSUE THREAD

**Issue by rt3norio** [amix/vimrc#454]
Hello!
I just installed and realized that acts in a strange behavior when typing these characters.

to achieve such characters, we should type '+a, and it gives á, in normal conditions.

now i have to press:
```

' + a + (any key) + (any key) = á

```

looks like to me some kind of buffer problem.
i use arch linux with larbs. don't know if might be some compatibility issue (i'm kinda noob)

Thanks in advance!

**Comment by amix** [comment]
@rt3norio I don't think my vimrc does anything to block this. Did you try with just the basic.vim setup?
