### ISSUE TITLE
Stupid question - what is c-space?

### ISSUE THREAD

**Issue by cboecking** [amix/vimrc#459]
Sorry to bother!!! however, after lots of searching did not uncover.

What is lowercase c dash space (c-space)?

C-space is control+space, however, I cannot find out what the lowercase c means.

**Comment by fbunt** [comment]
Lowercase c also means control, so c-space is control + space.

**Comment by cboecking** [comment]
Thank you. I think that part of my confusion is that control-space does not
work. It simply beeps at me. Everything else works as expected. Any hints
how to debug?


Regards,


Chuck Boecking
512.850.6068 (office and cell)
chuck@chuboe.com
ChuckBoecking.com
chuck.boecking (skype)
@ChuckBoecking
http://www.linkedin.com/pub/chuck-boecking/10/970/17b
