### ISSUE TITLE
Visual Block mode by pressing Ctrl-V doesn't work.

### ISSUE THREAD

**Issue by nayabbashasayed** [amix/vimrc#461]
Earlier I used to press Ctrl-V to go into visual mode and then do operations on multiple lines. After installing this plugin this somehow not working. Now this operation is pasting the buffer content into vim.

Except this, this plugin helped me a lot. Any idea how to fix this?

**Comment by nayabbashasayed** [comment]
The plugin works.. Must be some misconfiguration.:)

**Comment by SamuelBailey** [comment]
Same issue. How did you fix it?

**Comment by SamuelBailey** [comment]
Found a solution and described here https://github.com/amix/vimrc/issues/732#issuecomment-1592763095
