### ISSUE TITLE
vim-multiple-cursors not working

### ISSUE THREAD

**Issue by sdtemp** [amix/vimrc#462]
The plugin does not seem to be working,..

I tried installing the plugin manually as well, and did not succeed. I am not getting any errors so I don't know how to proceed.

**Comment by frzkn** [comment]
Can confirm, <Ctr l+ S> hangs the vim session

**Comment by Yeboster** [comment]
`Ctrl+S` is a shell shortcut to freeze the buffer (for fast input, for example). To unfreeze it there is the shortcut `Ctrl+Q`.

There is a closed issue where there is a comment to disable this functionality and use the default mapping for multiple cursors:

[issuecomment-349465982](https://github.com/amix/vimrc/issues/340#issuecomment-349465982)

**Comment by jayrexacilo** [comment]
> Can confirm, <Ctr l+ S> hangs the vim session

same here

**Comment by dessalines** [comment]
Same.

**Comment by terbb** [comment]
It might be a good idea to change this shortcut to something else instead of CTRL+S, or at least add a note in the README that CTRL+S is a shell shortcut to freeze the buffer.

**Comment by majamin** [comment]
> If you're on Ubuntu, you can add `stty -ixo` to the end of your `~/.bashrc` file. That will disable the buffer freezing functionality and allow you to use CTRL+S for multiple cursors again.

I tried to add `stty -ixo` but it throws an error (Bionic Beaver 18.04). The options now seem to be `stty -ixon` and `stty -ixoff` (see `man stty`).

After trying both options, `ssty -ixon` worked.

**Comment by amix** [comment]
This seems to be more an issue of the environment than of this vimrc.

Like @terbb notes, you can remap keys to resolve this issue.
