### ISSUE TITLE
Restoring mapping of C-f and C-b for page up and down

### ISSUE THREAD

**Issue by ericbarnhill** [amix/vimrc#466]
Hey man, love your vim setup! I want to return Ctrl-f to page down, and Ctrl-b to page up, as these standard key combinations are deeply embedded in my usage. But, I can't figure out where in your config files these are overridden? Can you do me a solid and tell me where, so I can comment those out. Thank you!

**Comment by chinuy** [comment]
refer #285 to see the answer
