### ISSUE TITLE
Issues on key remaping

### ISSUE THREAD

**Issue by BowenWang** [amix/vimrc#469]
Hi,
I have been using your configuration for some time, you configuration is very awesome. I think there is an issue on remapping, because I am using Programmer Dvorak keyboard layout, so I have to do some remapping in Vim like the following(these are copied from my my_configs.vim):
noremap [ 7
noremap { 5
noremap } 3
noremap ( 1
noremap = 9
noremap * 0
noremap ) 2
noremap + 4
noremap ] 6
noremap ! 8
noremap 7 [
noremap 5 {
noremap 3 }
noremap 1 (
noremap 9 =
noremap 0 *
noremap 2 )
noremap 4 +
noremap 6 ]
noremap 8 !

noremap t j
noremap n k
noremap s l

noremap j t
noremap k n
noremap l s

noremap ; :
noremap : ;

set textwidth=80
set number
filetype indent off

But the thing is that when I tried to press the key 4 in normal mode, it suddenly enters visual mode and select some sentences, I am not sure what happened, do you have any ideas where it can go wrong in my remapping configuration?

**Comment by amix** [comment]
@BowenWang you can do something like `noremap 4` from the command line to figure out what conflicts with your mappings.

It seems like it's yankstack — you could try to remove yankstrack from your configuration.
