### ISSUE TITLE
<c-b> to CtrlPBuffer is override by comfortable_motion

### ISSUE THREAD

**Issue by chinuy** [amix/vimrc#470]
**\<c-b\>**, which is assigned to open the CtrlPBuffer, is override by the setting in the *comfortable_motion.vim*
So far, the only is to comment it out in the *comfortable_motion.vim*

**Comment by chengyi** [comment]
just disable comfortable_motion.vim default keybinding
```vim
let g:comfortable_motion_no_default_key_mappings = 1
```

**Comment by amix** [comment]
I just removed comfortable-motion.vim  again — it seems like it creates more issues than it solves.
