### ISSUE TITLE
Fedora 28 KDE gives bunch of errors when vimrc is loading

### ISSUE THREAD

**Issue by nayabbashasayed** [amix/vimrc#471]
I copied vimrc file in home folder as _.vimrc_

When I try to load the file using the command `. ~/.vimrc`, bunch of errors popped up. I am using fedora 28 with KDE.
Here is the output I got,

> me@linux: $ . ~/.vimrc
> bash: $'\n': command not found
> bash: $'       Amir Salihefendic — @amix3k\n': command not found
> bash: $' Awesome_version:\n': command not found
> bash: $'\n': command not found
> bash: $'\n': command not found
> bash: $'\n': command not found
> bash: $'    -> General\n': command not found
> bash: $'    -> Colors and Fonts\n': command not found
> bash: $'    -> Text, tab and indent related\n': command not found
> bash: $'    -> Moving around, tabs and buffers\n': command not found
> bash: $'    -> Editing mappings\n': command not found
> bash: $'    -> Spell checking\n': command not found
> bash: $'    -> Helper functions\n': command not found
> bash: $'\n\n\n': command not found
> bash: $' => General\n': command not found
> bash: $' Sets how many lines of history VIM has to remember\nset history=500\n\n': command not found
> bash: filetype: command not found
> bash: filetype: command not found
> bash: /home/nayabsd/.vimrc: line 103: syntax error near unexpected token `('
> bash: /home/nayabsd/.vimrc: line 103: `" Don't redraw while executing macros (good performance config)'

Could anybody tell me how to fix it? Thank you.

**Comment by marafa** [comment]
.vimrc is for vim .. its automatically loaded when u run vim 
its not for bash

u can close this issue now

**Comment by nayabbashasayed** [comment]
I know vimrc is for Vim. I wanted you check why it's giving errors on Fedora..:)

**Comment by shan23** [comment]
@nayabbashasayed If you know its for vim, then you wouldn't try to execute it from a shell. Please readup on the documentation of VIM to see how to use a vimrc.
