### ISSUE TITLE
When pressed <c-d> ，dispaly "Undefined variable: s:timer_id"

### ISSUE THREAD

**Issue by sswanv** [amix/vimrc#472]
![image](https://user-images.githubusercontent.com/19299137/46953853-93b24700-d0c1-11e8-9bb0-0b88c89ccb71.png)

**Comment by Els-y** [comment]
I met the same problem, have you solved the problem?

**Comment by FlyClover** [comment]
Disable the comfortable motion plugin:

`let g:loaded_comfortable_motion = 1`

**Comment by amix** [comment]
Thanks for answering, @FlyClover 👍
