### ISSUE TITLE
How to page down?

### ISSUE THREAD

**Issue by aihy** [amix/vimrc#476]
I used <C-f> <C-b> for page down and up, how to do that now? Thank you very much!

**Comment by shan23** [comment]
`Ctrl + D`, `Ctrl + U`

**Comment by al03** [comment]
How to disable the scroll animation?

**Comment by stoneboy100200** [comment]
how to disable the scroll animation??????????????????

**Comment by Arnie97** [comment]
See #452 @al03 @stoneboy100200

**Comment by amix** [comment]
A duplicate of https://github.com/amix/vimrc/issues/452
