### ISSUE TITLE
How to disable command continuation on a new line

### ISSUE THREAD

**Issue by intrepidsilence** [amix/vimrc#481]
When on a single line and you do something like 80x in cmd mode in default vim it will delete to the end of the line (yes I know there is a better way to do that command this is just an example to illustrate what I am talking about) but with even just vimrc basic installed it will continue deleting on the next line and so on until it can satisfy the full 80x.  I tried setting nowrap in my config to overwrite and nowrap was set but that did not fix the behavior.  I also tried changing whichwrap back to default but that did not fix this either.

What is the setting or plugin causing it to act this way?

**Comment by amix** [comment]
You might want to check out:
* `help lbr`
* `help tw`
* `help wrap`

With these 3 you can configure this in my_configs.vim, so it fits your style 👍

**Comment by intrepidsilence** [comment]
Thanks much!
