### ISSUE TITLE
can't use spelling check

### ISSUE THREAD

**Issue by Xiaozekun** [amix/vimrc#488]
Spell checking
```
Pressing <leader>ss will toggle spell checking:

map <leader>ss :setlocal spell!<cr>
```
input` ,ss `
then type `i` into insert mode
type `aewsome`, no use
also try to input `:set spell`
still no use can't spell check
anyone have same issue?

Use original vim and only installed `install_awesome_vimrc.sh`

**Comment by rmFlynn** [comment]
Looks like the spell check works but highlighting is broken, so you can't see it. Try to use the navigation and correction shortcuts, see if they work. Or add your own highlighting to the my_configs.vim,  like I have  "hi SpellBad cterm=underline ctermfg=red".
