### ISSUE TITLE
Save old configuration before overwriting

### ISSUE THREAD

**Issue by floriama** [amix/vimrc#491]
Saving the old .vimrc in .vimrc.old or something would be good.
Just overwriting everything without warning is very unexpected behavior and leaves me piecing together my old vimrc after just wanting to give this a quick try.

**Comment by Tiande** [comment]
you should place your configuration in **my_configs.vim** file.
in this project, you can use **",(prefix)+e"** to quickly open this file.

or just create it: **~/.vim_runtime/my_configs.vim**

**Comment by amix** [comment]
Thanks for answering, @Tiande
