### ISSUE TITLE
Error detected while processing function <SNR>42_MRU_LoadList:

### ISSUE THREAD

**Issue by lrlewis** [amix/vimrc#494]
New in stall on RedHat 7.3 

ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=d6bc1a602548daa278a00bcede8502eb3489a612, stripped

Get this each time I open a new file
Error detected while processing function <SNR>42_MRU_LoadList:
line    5:
E684: list index out of range: 0
Press ENTER or type command to continue

**Comment by amix** [comment]
This looks more like a vim issue than an issue with this config 😕
