### ISSUE TITLE
gitgutter '+' sign color is not green

### ISSUE THREAD

**Issue by cgbahk** [amix/vimrc#495]
gitgutter shows `git diff` information on gutter, which I love to use.
## Symptom
Before f50b214 '+' sign (which means `git diff` found new line added) was shown as green, but after that commit, '+' sign becomes white, which is same color with plain text.

This is not critical but irritating... 

## How to regenerate
`git checkout ` to before and after f50b214. You can check difference.

## My best guess for solution
I guess vim-gitgutter plugin patch in f50b214 makes this issue, but cannot dig in more.

Any helps welcome 😃

**Comment by amix** [comment]
@cgbahk could you please try and see if this happens with another color scheme? I will close this down, but please reopen if you provide more info 👍
