### ISSUE TITLE
NonText (listchars) invisible unless directly under cursor

### ISSUE THREAD

**Issue by jetzerb** [amix/vimrc#496]
When using a dark background, your [modifications to peaksea "NonText" colors](https://github.com/amix/vimrc/commit/08a64d943dab56ca8b5896a150531487ac0fa1c6#diff-2968224659184acc0df79e3ed34364e4) render them invisible unless they are directly under the cursor. This may or may not be related to issue #224 reported a few years ago.

Here's a direct comparison between your modified version (top) and the original value (bottom). Note how in the top session, only the tab character directly under the cursor is visible, but in the bottom session, _all_ non-text is visible:
![image](https://user-images.githubusercontent.com/36859020/54933634-07ffda80-4eeb-11e9-90aa-4c3269d77e9c.png)

Was this change intentional?  I couldn't tell what the motivation was from the commit comment. I _personally_ find it convenient to see all non-text all the time, so I had assumed this was a mistake.  But since that change was made over five years ago, it seems more likely that this is your personal preference (or it would have been changed by now).

If this is your desired behavior, I override it in `my_configs.vim` to add visibility to the non-text characters.

And in case it's some environmental thing, my setup is as follows:
- Ubuntu 18.10
- rxvt-unicode 9.22-4
- neovim v0.3.1
- tmux 2.7.1 with [Oh My Tmux!](https://github.com/gpakosz/.tmux) config
- `set listchars=tab:>-,nbsp:_,eol:$,trail:!,extends:},precedes:{`

**Comment by amix** [comment]
It was so long time ago this is set, I have reverted this tho' as it does not make sense to do such an overwrite.
