### ISSUE TITLE
how to launch vim in windows 7 ?

### ISSUE THREAD

**Issue by pennli** [amix/vimrc#497]
Hello,
I have installed it successfully in Win 7 but found no place to launch it. 
Could you help me out ?
tks

**Comment by xcl666** [comment]
In the cmd, type vim
Kind Regards,

Xue Chuangli



Website: https://www.oootwo.com

GitHub: https://github.com/xcl666

Facebook: https://www.facebook.com/oootwo

Twitter: https://twitter.com/xuechuangli666
