### ISSUE TITLE
crontab output prepends extra characters

### ISSUE THREAD

**Issue by raphattack** [amix/vimrc#498]
I have a crontab set up to run a bash script. The output from my cron job prepends `?(B?[m`. Trying to track down where this is coming from.

**test.sh**
```
#!/bin/bash

echo "Hello"
```

```
$ crontab -l

MAILTO=myemail@host.com

* * * * * . ${HOME}/.bash_profile; ${HOME}/test.sh
```

**Output from cron:**
`?(B?[mHello`

I added the following to my `~/.bash_profile` file to ensure that `cron` is using `vim` instead of `vi`:

```
export EDITOR=vim
alias vi="vim"
```

**Comment by amix** [comment]
I don't think this configuration does anything to this. AFAIK I am not aware.
