### ISSUE TITLE
Font won't change

### ISSUE THREAD

**Issue by FraserEmbrey** [amix/vimrc#500]
I am using iterm2 on macOS. When I try to change the font by: <code>set gfn=<i>my\ font</i></code> I get no change. I have tried a few fonts and setting the guifont in the editor too. I'm not sure what the issue is 🤷‍♂️

**Comment by TYZRPVX** [comment]
me too

**Comment by JingChunzhen** [comment]
me too

**Comment by amix** [comment]
AFAIK `gfn` is only for the GUI mode (e.g. desktop apps) and not the terminal. I don't think it's possible to override the terminal.
