### ISSUE TITLE
Can we consider to change plug management tool from "pathogen" to "vim-plug" ?

### ISSUE THREAD

**Issue by johnnyjpixy** [amix/vimrc#503]
Can we consider to change plug management tool from "pathogen" to "vim-plug" ?
Thank you.

-- Accroding to VIM8, maybe we can use the default "package manager".

**Comment by AJeo0526** [comment]
I have the same expactation.

**Comment by amix** [comment]
For now, I think pathogen works quite well. But eventually, it would be nice to move to Vim8 package manager.

If somebody wants to support this, please feel free to provide a PR 😊
