### ISSUE TITLE
how to complete c family code?

### ISSUE THREAD

**Issue by AJeo0526** [amix/vimrc#506]

**Comment by FlashDaggerX** [comment]
[YouCompleteMe](https://github.com/Valloric/YouCompleteMe) Is a really nice plugin for auto-completion. However, it requires the UTF-8 encoding. I had issues using it with the `xterm` terminal emulator, because it wouldn't show characters deleting.

Otherwise, go for it.

**Comment by amix** [comment]
Thanks for answering, @FlashDaggerX 

@AJeo0526 you might also want to check out jedi-vim https://github.com/davidhalter/jedi-vim
