### ISSUE TITLE
How to disable/uninstall a plugin/mode? (eg. vim-go)

### ISSUE THREAD

**Issue by KANGOD** [amix/vimrc#508]
In README.md, we have [Included Plugins](https://github.com/amix/vimrc#included-plugins) and [Included modes](https://github.com/amix/vimrc#included-modes), but how to disable one of them?

For example, I want to disable `vim-go` mode in "Included modes".

I found https://github.com/amix/vimrc/issues/388 , but it isn't a general method. And there is [someone](https://github.com/amix/vimrc/issues/388#issuecomment-370120722) complains that it doesn't work.

**Comment by Arnie97** [comment]
Not an elegant solution, but `$ rm -r sources_non_forked/vim-go` should always work :-)

**Comment by amix** [comment]
I have already removed `vim-go` given how heavy it is 👍
