### ISSUE TITLE
i have the promblem with Anaconda

### ISSUE THREAD

**Issue by ArvinShaffer** [amix/vimrc#510]
Cannot be automatically completed in the anadonda environment，Who has the experience of configuring autocomplete under anaconda, seeking guidance

**Comment by Arnie97** [comment]
There should be many different options. Currently I'm using jedi-vim.
`git clone --recursive https://github.com/davidhalter/jedi-vim` into `my_plugins/` and it would work out of the box.

Chinese users might want to `let g:jedi#completions_command =` something else to avoid conflicts with the IME switching hotkey `<c-space>`.

**Comment by amix** [comment]
Thanks for answering, @Arnie97 🙏
