### ISSUE TITLE
Error detected while processing /usr/share/vim/vim81/colors/desert.vim:

### ISSUE THREAD

**Issue by abdyek** [amix/vimrc#512]
I use linux mint 19.1
I installed vim using offical ubuntu repos
I have installed awesome version with 
`git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
sh ~/.vim_runtime/install_awesome_vimrc.sh`

when I start vim on terminal, I have these errors:

> ~$ vim
> 
> Error detected while processing /usr/share/vim/vim81/colors/desert.vim: 
> 
> line   48:
> E254: Cannot allocate color indianred
> line   62:
> E254: Cannot allocate color indianred
> line   48:
> E254: Cannot allocate color indianred
> line   62:
> E254: Cannot allocate color indianred
> Press ENTER or type command to continue
>

**Comment by amix** [comment]
This looks like an issue with your Vim setup, and not this setup. 
Note, `desert.vim` isn't part of this configuration.
