### ISSUE TITLE
plugins_config.vim caused the basic.vim to stop showing CWD

### ISSUE THREAD

**Issue by xianshuli** [amix/vimrc#514]
I installed `The Awesome` and found `source ~/.vim_runtime/vimrcs/plugins_config.vim` in `~/.vimrc` caused the line `set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l\ \ Column:\ %c` in `basic.vim` to stop working. `The Awesome` can't show CWD in the status line. Is it possible to show CWD in the status line for `The Awesome`? Thanks.

**Comment by amix** [comment]
@xianshuli what OS and Vim version are you using?

**Comment by xianshuli** [comment]
macOs Catalina 10.15.1, Vim version is 8.1

**Comment by amix** [comment]
@xianshuli note that I use https://github.com/itchyny/lightline.vim — this status line setting is only used in the basic configuration.

You can either disable this or see how to configure lightline to include the CWD 👍
