### ISSUE TITLE
smart parenthesis drives me crazy how to turn it off?

### ISSUE THREAD

**Issue by cederom** [amix/vimrc#515]
Hello world, the new VIM plugins collection is very nice, however now it statrts to write and format code for me, which is quite irritating, especially when it does not allow me to close the parenthesis..

How can I disable this particular function? I want to open and close parenthesis by hand on my own ;-)

So far I have commented out one or two main lines from the `~/.vimrc` loosing also some other nice functinalities..

Any hints appreciated :-)

**Comment by pablodo** [comment]
After doing a lot of research found out this installed plugin `auto-pairs`. Looking inside it found the solution:

Add this to your vimrc (`<leader> e`, or `~/.vim_runtime/my_configs.vim`)
```
let b:autopairs_enabled=0
```

**Comment by amix** [comment]
Thanks for answering, @pablodo 🙏

**Comment by kid1412z** [comment]
Sometimes if we don't want to disable all the auto pair function. we can add line: 
`let g:AutoPairs = {'{':'}'}` in .vim_runtime/my_configs.vim
for example, this only enable auto complete "{}"
