### ISSUE TITLE
vim-racer not work

### ISSUE THREAD

**Issue by SharpKnifer** [amix/vimrc#516]
I start to use vim writing Rust. I installed racer by following [https://github.com/racer-rust/racer](url), and the test racer complete std::io::B works well on my iterm2. Then I follow [https://github.com/racer-rust/vim-racer](url) to setup my vim-racer.But  it not works when I use vim to write rust code. I have no idea what is going wrong.

**Comment by dessalines** [comment]
I suggest using `coc.nvim` and `coc-rls` . It works really well for rust in vim.

**Comment by amix** [comment]
Please post this as a vim-racer issue. I don't think this is related to this vimrc.
