### ISSUE TITLE
How could I disable the red block with vimrc?

### ISSUE THREAD

**Issue by MikeLing** [amix/vimrc#517]
![Capture](https://user-images.githubusercontent.com/2166227/59187980-3a93a800-8ba9-11e9-88c9-d3100f1cd991.JPG)

How could I disable this kind of block? Thank you!

**Comment by iamsea** [comment]
my vim broken too,after update win10 to the version of 1903

**Comment by fragrans** [comment]
```
:redraw!
```

**Comment by amix** [comment]
Please try to update both Vim and the latest version of this vimrc. I hope it fixes it; if not, please reopen this issue.
