### ISSUE TITLE
Error detected while processing function <SNR>79_GoInstallBinaries[103]..<SNR>81_remove: line    1: E488: Trailing characters

### ISSUE THREAD

**Issue by bbiao** [amix/vimrc#520]
Platform: macOS version 10.14.5
VIM: version 8.0.1283

Run :GoInstallBinaries

And the error will reproduced.

Download vim-go v1.2.0 and replace it will fix this

**Comment by amix** [comment]
I have now removed vim-go from my distribution. Please ask this directly in the vim-go repository 👍
