### ISSUE TITLE
Folding in python

### ISSUE THREAD

**Issue by sabian2008** [amix/vimrc#521]
How can I fold function definitions in a Python document?

I've done it before with plugins, but I wanted to know if there is anything included in this bundle.

Cheers and thanks for your work!

**Comment by Arnie97** [comment]
`:set foldmethod=indent` should work. This is mapped as F in [vimrcs/filetypes.vim#L10](https://github.com/amix/vimrc/blob/master/vimrcs/filetypes.vim#L10), so just press `shift`+`f`.
