### ISSUE TITLE
Why my macos vim-go cannot jump to definition?

### ISSUE THREAD

**Issue by g10guang** [amix/vimrc#526]
```
vim-go: [searching declaration] FAIL
```

Before I upgrade my golang version from 1.11 to 1.12, it works well. Any suggestion to solve this problem?

I have tried theses vim command:

```
:GoUpdateBinaries
:GoInstallBinaries
```

**Comment by amix** [comment]
I have now removed vim-go from my distribution. Please ask this directly in the vim-go repository 👍
