### ISSUE TITLE
Why when I press "d" and "down-arraw", It delete two lines?

### ISSUE THREAD

**Issue by Statham-stone** [amix/vimrc#529]
I am a beginner in vim.
Any help?

**Comment by Statham-stone** [comment]
Is it because <count> is defined to 2 in somewhere in the vimrc ?

**Comment by qc1iu** [comment]
This is the default behavior. You can use `:help d ` in vim for more detail.

**Comment by Statham-stone** [comment]
thanks, but can i stop this feature？------------------ 原始邮件 ------------------
发件人: "eric.1iu"<notifications@github.com>
发送时间: 2019年8月1日(星期四) 晚上11:21
收件人: "amix/vimrc"<vimrc@noreply.github.com>;
抄送: "Statham"<statham.stone@gmail.com>;"Author"<author@noreply.github.com>;
主题: Re: [amix/vimrc] Why when I press "d" and "down-arraw", It delete twolines? (#529)



This is the default behavior. You can use :help d  in vim for more detail.
 
&mdash;

**Comment by yszhang95** [comment]
what is the motivation to stop that? It is designed in such way that you can use `command <motion>` to quickly edit text. If you just mistakenly type `d` and then `down`, `u` can undo the command. If you mistakenly type `d`, `esc` helps cancel the command.

**Comment by amix** [comment]
I'm closing this down...
