### ISSUE TITLE
Cannot add new syntax with new plugin

### ISSUE THREAD

**Issue by yszhang95** [amix/vimrc#532]
Hi, experts
I installed a plugin called vim-root by `pathogen`. 
```
cd ~/.vim_runtime/my_plugins
git clone https://github.com/parnmatt/vim-root
```
and when I opened vim, I typed in `:set syntax+=.root`, the classes defined by root would be highlighted.
I want to turn on the syntax highlighting for vim-root automatically. So I add `:set syntax+=.root` to `~/.vim_runtime/my_configs.vim`. But when I opened the `.c` file. It would not automatically highlight those ROOT classes. I am wondering where I was wrong. 
It is very kind of you if you can provide some advice.
Thanks!

**Comment by amix** [comment]
Hi, please create an issue for `vim-root`. I don't think this is related to this config 👍
