### ISSUE TITLE
Suggestion for default behavior of swap files

### ISSUE THREAD

**Issue by kouchibin** [amix/vimrc#533]
Hi! I've been using this configuration for quite some time and it has saved me tons of configuration work. Now I have some suggestions and hope it might help others.

By default, the swap file is disabled. This is quite unexpected and I learned it the hard way. I think this is a dangerous default behavior because the user might be unaware of this setting and lose some important work when there is terminal crash or system crash. Version control systems are for human errors while swap machanism are more relevant to unexpected failures. Maybe it would be better to change this default behavior or at least mention it in the README page.

**Comment by Arnie97** [comment]
Personally the swap file makes me annoying, but I do agree that the change is dangerous and may cause unexpected data lost (#342). It might better be an optional setting rather than a default behavior.

**Comment by excelle08** [comment]
Agree. Disabling swap file by default is dangerous and can cause data loss.

**Comment by amix** [comment]
Note that you can include your configs in the my_configs.vim [Ref](https://github.com/amix/vimrc#how-to-include-your-own-stuff). I find the swap files quite annoying.
