### ISSUE TITLE
is it possible to change leader in my_configs.vim?

### ISSUE THREAD

**Issue by chanshing** [amix/vimrc#536]
I tried to change leader back to default in `my_configs.vim` but it doesn't seem to work. I tried adding `unlet mapleader` as well as `let mapleader = "\"`.

**Comment by Arnie97** [comment]
It's not possible at all, and I had to modify `vimrcs/basic.vim` to remove the custom leader key. The `<leader>` key was evaluated to the variable value when you created a key binding, and is not aware of later changes to the `mapleader` variable.

For example, assume you have these lines in your `.vimrc`:

```vim
let mapleader=","
map <leader>x :echo "foo"<cr>

let mapleader="\"
map <leader>y :echo "bar"<cr>
```

Then you'll have `,x` mapped to foo and `\y` mapped to bar.

**Comment by amix** [comment]
This seems like a Vim issue 😕 I am unsure what the solution is here.
