### ISSUE TITLE
E118: Too many arguments for function: function

### ISSUE THREAD

**Issue by agarzon** [amix/vimrc#537]
Just installed in a new fresh and I got this:

`Error detected while processing /root/.vim_runtime/sources_non_forked/vim-go/plugin/go.vim:
line   70:
E118: Too many arguments for function: function
E15: Invalid expression: { 'asmfmt':        ['github.com/klauspost/asmfmt/cmd/asmfmt'], 'dlv':           ['github.com/go-delve/delve/cmd/dlv'], 'errcheck':      ['github.com/kisielk/errcheck'], 'fillstruct':    ['github.com/davidrjenni/reftools/cmd/fillstruct'], 'gocode':        ['github.com/mdempsky/gocode', {'windows': ['-ldflags', '-H=windowsgui']}], 'gocode-gomod':  ['github.com/stamblerre/gocode'], 'godef':         ['github.com/rogpeppe/godef'], 'gogetdoc':      ['github.com/zmb3/gogetdoc'], 'goimports':     ['golang.org/x/tools/cmd/goimports'], 'golint':        ['golang.org/x/lint/golint'], 'gopls':         ['golang.org/x/tools/gopls@latest', {}, {'after': function('go#lsp#Restart', [])}], 'gometalinter':  ['github.com/alecthomas/gometalinter'], 'golangci-lint': ['github.com/golangci/golangci-lint/cmd/golangci-lint'], 'gomodifytags':  ['github.com/fatih/gomodifytags'], 'gorename':      ['golang.org/x/tools/cmd/gorename'], 'gotags':        ['github.com/jstemmer/gotags'], 'guru':          ['golang.org/x/t
Press ENTER or type command to continue`

**Comment by mufernando** [comment]
Same happened to me. Did you figure out how to solve this?

**Comment by agarzon** [comment]
No, the problem persist even in other new fresh machines I'm deploying.

Sadly maintainers did not show up yet. 

The only workaround I can suggest to you is to install the Basic version instead of the Awesome (wish is not awesome anymore)

**Comment by Luoti** [comment]
Same error here here. I'm on CentOS 7.

**Comment by jacinchan** [comment]
same error in Redhat 7.4

**Comment by alefisico** [comment]
same here, since I dont use go, I just remove the folder temporarily

**Comment by amix** [comment]
This is now fixed. I have removed vim-go from the standard dist (it's too heavy).

**Comment by arthurbailao** [comment]
@amix don't you need to remove vim-go from `sources_non_forked` manually?

**Comment by alefisico** [comment]
Thanks @amix, that works perfectly!

**Comment by amix** [comment]
I’ve now removed it 😊
