### ISSUE TITLE
How to turn 'auto-pairs' on?

### ISSUE THREAD

**Issue by Sar-Kerson** [amix/vimrc#542]
Hello, the auto-pairs seems to be set disable by default, because it doesn't work after the installation.  I've set `let b:autopairs_enabled=1` in my `my_configs.vim`, but the auto-pairs also seems not to work.

How can I turn it on?

Thank you.

**Comment by amix** [comment]
It works on my end. Please create an issue on auto-pairs as this config does not change the source code of this plugin (we use it as is).
