### ISSUE TITLE
somehow my pasted content got changed automatically

### ISSUE THREAD

**Issue by zyuhu** [amix/vimrc#543]
hello, first I'd like to thanks cos this configuration is really awesome. 
but recently encounter one issue, when I'm trying to paste a text, it automatically changed the text contents:
my text:
    numactl -H | grep 'size: [1-9]+*' | head -2 | tail -1 | awk '{print $2}'
changed text:
    numactl -H | grep 'size: [1-9]+*' | head -2 | tail -1 | awk '{print [}'']}'  

Any idea how to fix it?

**Comment by amix** [comment]
Please use `set paste` or `<leader>pp` for toggling the paste mode.

For more info see this: https://vim.fandom.com/wiki/Toggle_auto-indenting_for_code_paste
