### ISSUE TITLE
about python dict, list indent!

### ISSUE THREAD

**Issue by hstk30** [amix/vimrc#546]
I hope when i type `d = {<enter>`  then generate code like below: 

```
d = {
    _
}
```

but in fact the output is 

```
d = {
        _
          }
```

I see the `filetype.vim` config maybe link to this 
```
 au FileType python set cindent
 au FileType python set cinkeys-=0#
 au FileType python set indentkeys-=0#
```

but I don't know how to set the *cinkeys* ??

**Comment by amix** [comment]
Should be fixed. Thanks for the report. 👍
