### ISSUE TITLE
can't be used in  7.3.429  version 

### ISSUE THREAD

**Issue by duanjianyuooo** [amix/vimrc#55]
I't seems like that
line   50:
E319: Sorry, the command is not available in this version: filetype plugin on
line   51:
E319: Sorry, the command is not available in this version: filetype indent on
line   58:
E319: Sorry, the command is not available in this version: let mapleader = ","
line   59:
E319: Sorry, the command is not available in this version: let g:mapleader = ","
line   66:
E319: Sorry, the command is not available in this version: command W w !sudo tee % > /dev/null
line  129:
E518: Unknown option: foldcolumn=1
line  136:
E319: Sorry, the command is not available in this version: syntax enable 
line  138:
E319: Sorry, the command is not available in this version: try
line  139:
E185: Cannot find color scheme desert
line  140:
E319: Sorry, the command is not available in this version: catch
line  141:
E319: Sorry, the command is not available in this version: endtry
line  241:
E319: Sorry, the command is not available in this version: try
line  244:
E319: Sorry, the command is not available in this version: catch
line  245:
E319: Sorry, the command is not available in this version: endtry
line  248:
E319: Sorry, the command is not available in this version: autocmd BufReadPost *
line  249:
E10: \ should be followed by /, ? or &
line  250:
E10: \ should be followed by /, ? or &
line  251:
E10: \ should be followed by /, ? or &
line  286:
E319: Sorry, the command is not available in this version: func! DeleteTrailingWS()
line  287:
E319: Sorry, the command is not available in this version:   exe "normal mz"
line  289:
E319: Sorry, the command is not available in this version:   exe "normal `z"
line  290:
E319: Sorry, the command is not available in this version: endfunc
line  291:
E319: Sorry, the command is not available in this version: autocmd BufWrite *.py :call DeleteTrailingWS()
line  292:
E319: Sorry, the command is not available in this version: autocmd BufWrite *.coffee :call DeleteTrailingWS()
line  358:
E319: Sorry, the command is not available in this version: function! CmdLine(str)
line  359:
E319: Sorry, the command is not available in this version:     exe "menu Foo.Bar :" . a:str
line  360:
E319: Sorry, the command is not available in this version:     emenu Foo.Bar
line  361:
E319: Sorry, the command is not available in this version:     unmenu Foo
line  362:
E319: Sorry, the command is not available in this version: endfunction 
line  364:
E319: Sorry, the command is not available in this version: function! VisualSelection(direction, extra_filter) range
line  365:
E319: Sorry, the command is not available in this version:     let l:saved_reg = @"
line  366:
E319: Sorry, the command is not available in this version:     execute "normal! vgvy"
line  368:
E319: Sorry, the command is not available in this version:     let l:pattern = escape(@", '\\/.*$^~[]')
line  369:
E319: Sorry, the command is not available in this version:     let l:pattern = substitute(l:pattern, "\n$", "", "")
line  381:
E319: Sorry, the command is not available in this version:     let @/ = l:pattern
line  382:
E319: Sorry, the command is not available in this version:     let @" = l:saved_reg
line  383:
E319: Sorry, the command is not available in this version: endfunction
line  387:
E319: Sorry, the command is not available in this version: function! HasPaste()
line  391:
E319: Sorry, the command is not available in this version:     return ''
line  392:
E319: Sorry, the command is not available in this version: endfunction
line  395:
E319: Sorry, the command is not available in this version: command! Bclose call <SID>BufcloseCloseIt()
line  396:
E319: Sorry, the command is not available in this version: function! <SID>BufcloseCloseIt()
line  397:
E319: Sorry, the command is not available in this version:    let l:currentBufNum = bufnr("%")
line  398:
E319: Sorry, the command is not available in this version:    let l:alternateBufNum = bufnr("#")
line  413:
E319: Sorry, the command is not available in this version: endfunction
Press ENTER or type command to continue

**Comment by EwanValentine** [comment]
I get loads of errors when I run ```$source ~/.vimrc```

**Comment by mingder78** [comment]
maybe you are using vi, not vim, try to install vim
$ sudo apt-get install vim

**Comment by hv15** [comment]
I was getting a similar issue every time I did `git commit`, the error message I was getting was:
```
line  140:
E518: Unknown option: foldcolumn=1
Press ENTER or type command to continue
```
As it turns out, `git` will automatically use `vi` for editing commit messages if either the environment variable `$EDITOR` or `git config --global core.editor` are not set. For me the solution was to set `core.editor vim`.
