### ISSUE TITLE
How to switch from lightline to vim-airline completely.

### ISSUE THREAD

**Issue by Alfons0329** [amix/vimrc#551]
Hello, I really like your vimrc, it is really nice, however I would like to switch from lightline to vim-airline.
I have configured vim-airline, yet **whenever I save a file, it switch back to lightline**
And I have to type `: AirlineRefresh` for it
How to completely remove lightline?, thank you so much.

**Comment by mvrogowski** [comment]
Try adding the following to your `.vim_runtime/my_configs.vim`:

```
let g:lightline.enable = {
    \ 'statusline': 0,
    \ 'tabline': 0
    \ }
```
