### ISSUE TITLE
vim 8.1 can not source the `delmenu.vim`

### ISSUE THREAD

**Issue by AlicePorton** [amix/vimrc#554]
In `.vimrc` file 65L:
`source $VIMRUNTIME/delmenu.vim`

When I install the vim-gnome, the `vim` print the errors:
![image](https://user-images.githubusercontent.com/46804476/71642685-1d136080-2cea-11ea-9d96-d61ddd2b2709.png)

Is this a compatibility issue?

**Comment by amix** [comment]
This isn't something I can reproduce. I would recommend upgrading to vim 8.2.
