### ISSUE TITLE
It's a big error, i'm crazy

### ISSUE THREAD

**Issue by sukai-cheng** [amix/vimrc#557]
I follow your guideline from the readme.md but it's doesn' t work...it's has spend me a lot of time,
i am crazy now , i have no idea so that i beg for your help
![](https://chengsukai.oss-cn-hangzhou.aliyuncs.com/博客/图片/20200123050129.png)

**Comment by sukai-cheng** [comment]
everything is same from you, i dont change anything

**Comment by sukai-cheng** [comment]
![](https://chengsukai.oss-cn-hangzhou.aliyuncs.com/博客/图片/1.png)
![](https://chengsukai.oss-cn-hangzhou.aliyuncs.com/博客/图片/2.png)

**Comment by sukai-cheng** [comment]
![img](https://chengsukai.oss-cn-hangzhou.aliyuncs.com/博客/图片/20200123051624.png)

**Comment by maikka39** [comment]
Can you paste the error here?
