### ISSUE TITLE
Slow, Slow, Slow!

### ISSUE THREAD

**Issue by Angzz** [amix/vimrc#558]
Your awesome version is so slow to open, I can't stand this, any idea? thanks

**Comment by zeitounator** [comment]
Can you define slow ? I used it everyday for the past 3 years at least and never had to complain about it.

**Comment by maikka39** [comment]
Takes about half a second for me

**Comment by syin2** [comment]
I had the same issue via installing the runtime in a cluster with NFS.
When I try to open a file, the waiting time is between 2-5 seconds.

**Comment by amix** [comment]
It also takes a second to open for me 🙈

Anyhow, for speed, I recommend using the basic.vim as it does not include any plugins.
