### ISSUE TITLE
automatic comment deletion problem

### ISSUE THREAD

**Issue by ccxex29** [amix/vimrc#561]
The problem is when I press return/enter when it's like this
```
" set number
```
it will automatically become this
```
" set number
" 
```
Hence, I need to remove `" `, but as I backspace, the next line also gets deleted. Like this:
Before
```
" set number
" 
Hello
World
Foobar
```
After
```
" set number
Foobar
```

**Comment by dbarnett** [comment]
The first problem is from `set formatoptions+=r` (see `:help fo-table` for details). If you don't want that to happen for a particular filetype, you should do `:setlocal formatoptions-=r`.

For backspacing, I'm not aware of any setting that would do that, but check the output of `:verbose imap <Backspace>`.
