### ISSUE TITLE
Does line counter only for me looks poorly visible?

### ISSUE THREAD

**Issue by webcaptcha** [amix/vimrc#564]
I know that I can fork and modify a little the theme, but would do you think to make line counter more visible in the original theme?
![Screenshot_20200226_222124](https://user-images.githubusercontent.com/655608/75384388-b2943080-58e6-11ea-95b6-5bbbfa1dd065.png)

**Comment by amix** [comment]
In 95% of the cases, I don't care about the line number, and I can quickly go to a line by just doing `Xgg`, where X is a number.

If you want to modify this, I would recommend adding it to  `.vim_runtime/my_configs.vim`.
