### ISSUE TITLE
Improper display when the terminal is too small or too big without resizing the terminal window

### ISSUE THREAD

**Issue by qiujiangkun** [amix/vimrc#568]
If I resize my terminal window, it changes to normal.
![image](https://user-images.githubusercontent.com/33482468/75797294-eae8b280-5daf-11ea-9dc5-03fb02deccf1.png)
![image](https://user-images.githubusercontent.com/33482468/75797390-0c499e80-5db0-11ea-94a8-240c9c037047.png)

**Comment by fpgentil** [comment]
I fixed by removing the following line in the `extended.vim`  file:

```
set lines=999 columns=999
```

**Comment by amix** [comment]
You should addd this to `.vim_runtime/my_configs.vim` 👍
