### ISSUE TITLE
Why vim-go is removed from default support?

### ISSUE THREAD

**Issue by johnnyjpixy** [amix/vimrc#569]
Hi, I love it very much. but I have some questions here.

1) Why vim-go is removed, I remember that vim-go is support by default.
2) How can I check all my plug list ? Is there any commands ?
3) Is there any easy command to add / remove plug ?

Thanks .

**Comment by mvrogowski** [comment]
To add and/remove your personal plugins you just need to add/remove them into the `.vim_runtime/my_plugins/` folder.

**Comment by amix** [comment]
It's a very heavy plugin, and it's not relevant if you aren't coding in Go. I'm a big fan of vim-go, and Go in general.
