### ISSUE TITLE
Couldn't install the script for multiple users following the instructions on "Ubuntu 18.04.3" ("sh" is an alias for "dash" and ignores the shebang in the script)

### ISSUE THREAD

**Issue by fulopkovacs** [amix/vimrc#570]
> **First things first:** this config is awesome, I use it on my servers, Raspberry Pi-s and copied a lot of features from it to my personal vim config. So **thank you!** ☺️ 
## OS
`Ubuntu 18.04.3 LTS`

## The Problem
When I run the command (from the `README.md`) that should install the config for all users with home directories on my system I get the following syntax error:
```
$ sh ~/.vim_runtime/install_awesome_parameterized.sh /opt/vim_runtime --all
Installing Awesome Vim from /opt/vim_runtime
/home/some-user/.vim_runtime/install_awesome_parameterized.sh: 20: /home/some-user/.vim_runtime/install_awesome_parameterized.sh: Syntax error: "(" unexpected (expecting "fi")
```
If I run the script with `bash` it doesn't throw any errors.

### `sh` is a symlink for `dash` on Ubuntu
I checked it and `sh` seems to be a symlink for `dash` ([apparently it's the default configuration for Ubuntu (since 6.10)](https://wiki.ubuntu.com/DashAsBinSh):
```
$ which sh
/bin/sh
$ ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Aug 13  2019 /bin/sh -> dash
```

## Proposed Solutions
If the script is executable it runs fine without `sh`:
```
$ ~/.vim_runtime/install_awesome_parameterized.sh /opt/vim_runtime --all
```

Or why don't we use `bash` instead of `sh` explicitly?
```
$ bash ~.vim_runtime/install_awesome_parameterized.sh /opt/vim_runtime --all
```

I didn't create a PR, because I wasn't sure about my solutions in terms of compatibility, but If you like any of them, I'm happy to send a PR (although it's just going to be two changed lines in the `README.md` file 😆 ).

**Comment by fulopkovacs** [comment]
I just found a PR which seems to address this problem, although it modifies the script itself: https://github.com/amix/vimrc/pull/555

**Comment by amix** [comment]
I've now merged the patch in 👍 Thanks for reporting.
