### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Zw1d** [amix/vimrc#574]
Fresh debian over ssh. I run:
```
git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
sh ~/.vim_runtime/install_awesome_vimrc.sh
Installed the Ultimate Vim configuration successfully! Enjoy :-)
```

That's my vim before install:
![image](https://user-images.githubusercontent.com/11756864/80575718-4c21b080-8a04-11ea-9966-71b541a717e1.png)

After: 
![image](https://user-images.githubusercontent.com/11756864/80575819-6fe4f680-8a04-11ea-9c79-2915be32354a.png)

Plugins don't seem to work. Did I miss something?

**Comment by zeitounator** [comment]
How are you able to conclude that plugins are "not working" from those two screenshots ? What makes you think they are "not working" ?

Which action did you take / command did you type... after starting vim which involves a plug-in (which one ?) that did was "not working" ? Did you get any error message ? What result did you get ? How was it different from the one you were expecting ?

Did you read the documentation on [key mappings](https://github.com/amix/vimrc#key-mappings), more specifically the [Plugin related mappings](https://github.com/amix/vimrc#plugin-related-mappings) as well as the specific documentation for the relevant [Included plugin](https://github.com/amix/vimrc#included-plugins) you want to use ?

"Not working" is never a good and accurate description of your problem and definitely the worse title you can use for a bug report or a support request.

**Comment by amix** [comment]
Judging by these screenshots, I think you got the plugins and the config installed.

As @zeitounator said, I would recommend reading the documentation, especially regarding the plugins that you want to use.
