### ISSUE TITLE
crontab -e error

### ISSUE THREAD

**Issue by henosch** [amix/vimrc#580]
Hello,
with crontab -e I get this errors:
$ crontab -e
Error detected while processing /usr/share/vim/vim81/filetype.vim:
line   10:
E319: Sorry, the command is not available in this version: let did_load_filetypes = 1
line   13:
E319: Sorry, the command is not available in this version: let s:cpo_save = &cpo
line   45:
E319: Sorry, the command is not available in this version: func! s:StarSetf(ft)
line   49:
E319: Sorry, the command is not available in this version: endfunc
line 2163:
E319: Sorry, the command is not available in this version: func! TestFiletypeFuncs(testlist)
line 2164:
E319: Sorry, the command is not available in this version:   let output = ''
line 2165:
E319: Sorry, the command is not available in this version:   for f in a:testlist
line 2166:
E319: Sorry, the command is not available in this version:     try
line 2167:
E319: Sorry, the command is not available in this version:       exe f
line 2168:
E319: Sorry, the command is not available in this version:     catch
line 2169:
E319: Sorry, the command is not available in this version:       let output = output . "\n" . f . ": " . v:exception
line 2170:
E319: Sorry, the command is not available in this version:     endtry
line 2171:
E319: Sorry, the command is not available in this version:   endfor
line 2172:
E319: Sorry, the command is not available in this version:   return output
line 2173:
E319: Sorry, the command is not available in this version: endfunc
line 2176:
E319: Sorry, the command is not available in this version: let &cpo = s:cpo_save
line 2177:
E319: Sorry, the command is not available in this version: unlet s:cpo_save
Error detected while processing /usr/share/vim/vim81/ftplugin.vim:
line    9:
E319: Sorry, the command is not available in this version: let did_load_ftplugin = 1
line   14:
E319: Sorry, the command is not available in this version:   func! s:LoadFTPlugin()
line   20:
E319: Sorry, the command is not available in this version:     let s = expand("<amatch>")
line   34:
E319: Sorry, the command is not available in this version:   endfunc
Error detected while processing /usr/share/vim/vim81/filetype.vim:
line   10:
E319: Sorry, the command is not available in this version: let did_load_filetypes = 1
line   13:
E319: Sorry, the command is not available in this version: let s:cpo_save = &cpo
line   45:
E319: Sorry, the command is not available in this version: func! s:StarSetf(ft)
line   49:
E319: Sorry, the command is not available in this version: endfunc
line 2163:
E319: Sorry, the command is not available in this version: func! TestFiletypeFuncs(testlist)
line 2164:
E319: Sorry, the command is not available in this version:   let output = ''
line 2165:
E319: Sorry, the command is not available in this version:   for f in a:testlist
line 2166:
E319: Sorry, the command is not available in this version:     try
line 2167:
E319: Sorry, the command is not available in this version:       exe f
line 2168:
E319: Sorry, the command is not available in this version:     catch
line 2169:
E319: Sorry, the command is not available in this version:       let output = output . "\n" . f . ": " . v:exception
line 2170:
E319: Sorry, the command is not available in this version:     endtry
line 2171:
E319: Sorry, the command is not available in this version:   endfor
line 2172:
E319: Sorry, the command is not available in this version:   return output
line 2173:
E319: Sorry, the command is not available in this version: endfunc
line 2176:
E319: Sorry, the command is not available in this version: let &cpo = s:cpo_save
line 2177:
E319: Sorry, the command is not available in this version: unlet s:cpo_save
Error detected while processing /usr/share/vim/vim81/indent.vim:
line    9:
E319: Sorry, the command is not available in this version: let did_indent_on = 1
line   13:
E319: Sorry, the command is not available in this version:   func! s:LoadIndent()
line   18:
E319: Sorry, the command is not available in this version:     let s = expand("<amatch>")
line   30:
E319: Sorry, the command is not available in this version:   endfunc
Error detected while processing /home/mike/.vim_runtime/vimrcs/basic.vim:
line   46:
E319: Sorry, the command is not available in this version: let mapleader = ","
line   53:
E319: Sorry, the command is not available in this version: command! W execute 'w !sudo tee % > /dev/null' <bar> edit!
line   63:
E319: Sorry, the command is not available in this version: let $LANG='en' 
Error detected while processing /usr/share/vim/vim81/delmenu.vim:
line    7:
E319: Sorry, the command is not available in this version: aunmenu *
line    8:
E319: Sorry, the command is not available in this version: tlunmenu *
Error detected while processing /usr/share/vim/vim81/menu.vim:
line   12:
E319: Sorry, the command is not available in this version: let s:cpo_save = &cpo
line 1163:
E319: Sorry, the command is not available in this version: let &cpo = s:cpo_save
line 1164:
E319: Sorry, the command is not available in this version: unlet s:cpo_save
Error detected while processing /home/mike/.vim_runtime/vimrcs/basic.vim:
line  135:
E319: Sorry, the command is not available in this version: syntax enable 
line  142:
E319: Sorry, the command is not available in this version: try
Error detected while processing /usr/share/vim/vim81/colors/desert.vim:
line   22:
E319: Sorry, the command is not available in this version: let g:colors_name="desert"
Error detected while processing /home/mike/.vim_runtime/vimrcs/basic.vim:
line  144:
E319: Sorry, the command is not available in this version: catch
line  145:
E319: Sorry, the command is not available in this version: endtry
line  237:
E319: Sorry, the command is not available in this version: let g:lasttab = 1
line  250:
E319: Sorry, the command is not available in this version: try
line  253:
E319: Sorry, the command is not available in this version: catch
line  254:
E319: Sorry, the command is not available in this version: endtry
line  290:
E319: Sorry, the command is not available in this version: fun! CleanExtraSpaces()
line  291:
E319: Sorry, the command is not available in this version:     let save_cursor = getpos(".")
line  292:
E319: Sorry, the command is not available in this version:     let old_query = getreg('/')
line  294:
E319: Sorry, the command is not available in this version:     call setpos('.', save_cursor)
line  295:
E319: Sorry, the command is not available in this version:     call setreg('/', old_query)
line  296:
E319: Sorry, the command is not available in this version: endfun
line  336:
E319: Sorry, the command is not available in this version: function! HasPaste()
line  340:
E319: Sorry, the command is not available in this version:     return ''
line  341:
E319: Sorry, the command is not available in this version: endfunction
line  344:
E319: Sorry, the command is not available in this version: command! Bclose call <SID>BufcloseCloseIt()
line  345:
E319: Sorry, the command is not available in this version: function! <SID>BufcloseCloseIt()
line  346:
E319: Sorry, the command is not available in this version:     let l:currentBufNum = bufnr("%")
line  347:
E319: Sorry, the command is not available in this version:     let l:alternateBufNum = bufnr("#")
line  362:
E319: Sorry, the command is not available in this version: endfunction
line  364:
E319: Sorry, the command is not available in this version: function! CmdLine(str)
line  365:
E319: Sorry, the command is not available in this version:     call feedkeys(":" . a:str)
line  366:
E319: Sorry, the command is not available in this version: endfunction 
line  368:
E319: Sorry, the command is not available in this version: function! VisualSelection(direction, extra_filter) range
line  369:
E319: Sorry, the command is not available in this version:     let l:saved_reg = @"
line  370:
E319: Sorry, the command is not available in this version:     execute "normal! vgvy"
line  372:
E319: Sorry, the command is not available in this version:     let l:pattern = escape(@", "\\/.*'$^~[]")
line  373:
E319: Sorry, the command is not available in this version:     let l:pattern = substitute(l:pattern, "\n$", "", "")
line  381:
E319: Sorry, the command is not available in this version:     let @/ = l:pattern
line  382:
E319: Sorry, the command is not available in this version:     let @" = l:saved_reg
line  383:
E319: Sorry, the command is not available in this version: endfunction
Error detected while processing /home/mike/.vim_runtime/vimrcs/filetypes.vim:
line    4:
E319: Sorry, the command is not available in this version: let python_highlight_all = 1
line   35:
E319: Sorry, the command is not available in this version: function! JavaScriptFold() 
line   38:
E319: Sorry, the command is not available in this version:     syn region foldBraces start=/{/ end=/}/ transparent fold keepend extend
line   40:
E319: Sorry, the command is not available in this version:     function! FoldText()
line   41:
E319: Sorry, the command is not available in this version:         return substitute(getline(v:foldstart), '{.*', '{...}', '')
line   42:
E319: Sorry, the command is not available in this version:     endfunction
line   44:
E319: Sorry, the command is not available in this version: endfunction
line   50:
E319: Sorry, the command is not available in this version: function! CoffeeScriptFold()
line   53:
E319: Sorry, the command is not available in this version: endfunction
line   80:
E319: Sorry, the command is not available in this version: let vim_markdown_folding_disabled = 1
Error detected while processing /home/mike/.vim_runtime/vimrcs/plugins_config.vim:
line   11:
E319: Sorry, the command is not available in this version: let s:vim_runtime = expand('<sfile>:p:h')."/.."
line   12:
E319: Sorry, the command is not available in this version: call pathogen#infect(s:vim_runtime.'/sources_forked/{}')
line   13:
E319: Sorry, the command is not available in this version: call pathogen#infect(s:vim_runtime.'/sources_non_forked/{}')
line   14:
E319: Sorry, the command is not available in this version: call pathogen#infect(s:vim_runtime.'/my_plugins/{}')
line   15:
E319: Sorry, the command is not available in this version: call pathogen#helptags()
line   21:
E319: Sorry, the command is not available in this version: let g:bufExplorerDefaultHelp=0
line   22:
E319: Sorry, the command is not available in this version: let g:bufExplorerShowRelativePath=1
line   23:
E319: Sorry, the command is not available in this version: let g:bufExplorerFindActive=1
line   24:
E319: Sorry, the command is not available in this version: let g:bufExplorerSortBy='name'
line   31:
E319: Sorry, the command is not available in this version: let MRU_Max_Entries = 400
line   38:
E319: Sorry, the command is not available in this version: let g:yankstack_yank_keys = ['y', 'd']
line   47:
E319: Sorry, the command is not available in this version: let g:ctrlp_working_path_mode = 0
line   50:
E319: Sorry, the command is not available in this version: let g:ctrlp_map = '<C-f>'
line   59:
E319: Sorry, the command is not available in this version: let g:ctrlp_max_height = 20
line   60:
E319: Sorry, the command is not available in this version: let g:ctrlp_custom_ignore = 'node_modules\|^\.DS_Store\|^\.git\|^\.coffee'
line   67:
E319: Sorry, the command is not available in this version: let g:user_zen_mode='a'
line   80:
E319: Sorry, the command is not available in this version: let Grep_Skip_Dirs = 'RCS CVS SCCS .svn generated'
line   87:
E319: Sorry, the command is not available in this version: let g:NERDTreeWinPos = "right"
line   88:
E319: Sorry, the command is not available in this version: let NERDTreeShowHidden=0
line   89:
E319: Sorry, the command is not available in this version: let NERDTreeIgnore = ['\.pyc$', '__pycache__']
line   90:
E319: Sorry, the command is not available in this version: let g:NERDTreeWinSize=35
line   99:
E319: Sorry, the command is not available in this version: let g:multi_cursor_use_default_mapping=0
line  102:
E319: Sorry, the command is not available in this version: let g:multi_cursor_start_word_key      = '<C-s>'
line  103:
E319: Sorry, the command is not available in this version: let g:multi_cursor_select_all_word_key = '<A-s>'
line  104:
E319: Sorry, the command is not available in this version: let g:multi_cursor_start_key           = 'g<C-s>'
line  105:
E319: Sorry, the command is not available in this version: let g:multi_cursor_select_all_key      = 'g<A-s>'
line  106:
E319: Sorry, the command is not available in this version: let g:multi_cursor_next_key            = '<C-s>'
line  107:
E319: Sorry, the command is not available in this version: let g:multi_cursor_prev_key            = '<C-p>'
line  108:
E319: Sorry, the command is not available in this version: let g:multi_cursor_skip_key            = '<C-x>'
line  109:
E319: Sorry, the command is not available in this version: let g:multi_cursor_quit_key            = '<Esc>'
line  142:
E319: Sorry, the command is not available in this version: let g:lightline = { 'colorscheme': 'wombat', 'active': {   'left': [ ['mode', 'paste'],             ['fugitive', 'readonly', 'filename', 'modified'] ],   'right': [ [ 'lineinfo' ], ['percent'] ] }, 'component': {   'readonly': '%{&filetype=="help"?"":&readonly?"🔒":""}',   'modified': '%{&filetype=="help"?"":&modified?"+":&modifiable?"":"-"}',   'fugitive': '%{exists("*FugitiveHead")?FugitiveHead():""}' }, 'component_visible_condition': {   'readonly': '(&filetype!="help"&& &readonly)',   'modified': '(&filetype!="help"&&(&modified||!&modifiable))',   'fugitive': '(exists("*FugitiveHead") && ""!=FugitiveHead())' }, 'separator': { 'left': ' ', 'right': ' ' }, 'subseparator': { 'left': ' ', 'right': ' ' } }
line  147:
E319: Sorry, the command is not available in this version: let g:goyo_width=100
line  148:
E319: Sorry, the command is not available in this version: let g:goyo_margin_top = 2
line  149:
E319: Sorry, the command is not available in this version: let g:goyo_margin_bottom = 2
line  160:
E319: Sorry, the command is not available in this version: let g:ale_linters = {   'javascript': ['jshint'],   'python': ['flake8'],   'go': ['go', 'golint', 'errcheck']}
line  165:
E319: Sorry, the command is not available in this version: let g:ale_set_highlights = 0
line  168:
E319: Sorry, the command is not available in this version: let g:ale_lint_on_text_changed = 'never'
line  169:
E319: Sorry, the command is not available in this version: let g:ale_lint_on_enter = 0
line  175:
E319: Sorry, the command is not available in this version: let g:gitgutter_enabled=0
Error detected while processing /home/mike/.vim_runtime/vimrcs/extended.vim:
line   32:
E185: Cannot find color scheme 'peaksea'
line   46:
E319: Sorry, the command is not available in this version: try
line   49:
E319: Sorry, the command is not available in this version: catch
line   50:
E319: Sorry, the command is not available in this version: endtry
line  152:
E319: Sorry, the command is not available in this version: func! DeleteTillSlash()
line  153:
E319: Sorry, the command is not available in this version:     let g:cmd = getcmdline()
line  169:
E319: Sorry, the command is not available in this version:     return g:cmd_edited
line  170:
E319: Sorry, the command is not available in this version: endfunc
line  172:
E319: Sorry, the command is not available in this version: func! CurrentFileDir(cmd)
line  173:
E319: Sorry, the command is not available in this version:     return a:cmd . " " . expand("%:p:h") . "/"
line  174:
E319: Sorry, the command is not available in this version: endfunc
Error detected while processing /home/mike/.vimrc:
line    8:
E319: Sorry, the command is not available in this version: try
line    9:
E484: Can't open file /home/mike/.vim_runtime/my_configs.vim
line   10:
E319: Sorry, the command is not available in this version: catch
line   11:
E319: Sorry, the command is not available in this version: endtry
Press ENTER or type command to continue

edit:
I can't select vi.
This is the menu:
$ select-editor

Select an editor.  To change later, run 'select-editor'.
  1. /bin/nano        <---- easiest
  2. /usr/bin/vim.basic
  3. /usr/bin/vim.tiny
  4. /bin/ed

Choose 1-4 [1]: 3

I select 3 an fixes the error with:
sudo mv /usr/bin/vim.tiny /usr/bin/vim.tiny_org
sudo ln -s /usr/bin/vi /usr/bin/vim.tiny

**Comment by amix** [comment]
I think this is related to your vim setup. Please make sure you are running the latest version of Vim 8.

**Comment by BigSully** [comment]
Selecting editor with command `select-editor` after reinstallation of vim works for my `crontab -e` erorr. There might be several vim listed, do select the right one.
