### ISSUE TITLE
/usr/share/vim/vim82/colors/desert.vim An error was detected while processing:

### ISSUE THREAD

**Issue by azamet90** [amix/vimrc#583]
line 48:
E254: indianred color cannot be separated
line 62:
E254: indianred color cannot be separated
line 48:
E254: indianred color cannot be separated
line 62:
E254: indianred color cannot be separated

**Comment by amix** [comment]
I think this is related to your vim setup. Please make sure you are running the latest version of Vim 8.

**Comment by azamet90** [comment]
no it wasnt but i fixed it

**Comment by BerkantOdevci** [comment]
how did you do
