### ISSUE TITLE
The plugin "open_file_under_cursor.vim" has problem

### ISSUE THREAD

**Issue by ChrisChou2018** [amix/vimrc#584]
**issues description:**
most time this plugin is not useful, when I use NerdTree open a file in second level directory, it's can not open target path.

**error message :**
`Error detected while processing function GotoFile:`
`line   31:`
`E345: Can't find file "../lib/index.js" in path`
`Press ENTER or type command to continue`

I had to remove this plugin to make the original ‘gf’ command work properly

**condition**
my os is MacOS, my VIM versions is 8.1

Thank you friend, I'm really enjoy your vim configs, it's big help for me, I just want tell you I find problem in plugin. if this is my own problem, please let me know

**Comment by ChrisChou2018** [comment]
my os is MacOS, my VIM versions is 8.1

**Comment by ChrisChou2018** [comment]
Thank you friend, I'm really enjoy your vim configs, it's big help for me, I just want tell you I find problem in plugin. if this is my own problem, let me know

**Comment by patovala** [comment]
How you removed it safely? I'm having the same issue, or there is a way to make it works?

**Comment by stevepolitodesign** [comment]
I found this didn't play nicely with vim-rails, so I also needed to remove it. To do so, I just removed the plugin like so: `rm -rf ~/.vim_runtime/sources_non_forked/open_file_under_cursor.vim`
