### ISSUE TITLE
Does the basic version support "set mouse=a"?

### ISSUE THREAD

**Issue by lanranranM** [amix/vimrc#591]
I have added  `set mouse=a`, `set mouse-=a`... and so on into .vimrc to enable my mouse in vim. But none of them works. What should I do? Thanks~

**Comment by Longoon12000** [comment]
I have had the issue that I can't disable the mouse by adding `set mouse-=a` to the `/opt/vim_runtime/my_configs.vim` file. Putting it in a users `~/.vimrc` file has worked.

**Comment by amix** [comment]
This isn't something I can reproduce, but I would recommend trying @Longoon12000's fix.
