### ISSUE TITLE
Inverting touchpad scroll

### ISSUE THREAD

**Issue by han-so1omon** [amix/vimrc#601]
Running Microsoft Surface Book 2/Manjaro20/KDE Plasma 5/Linux5.8 (linux-surface variant)

This config is inverting my touchpad scroll, as in it is the opposite of the system setting for scroll direction. I like to use touchpad to scroll sometimes. With this config the touchpad scroll is also slow.

**Comment by amix** [comment]
I am unsure how you would do this, or if it's possible. I think this should be an OS setting, and probably not VIM 👀
