### ISSUE TITLE
vim-multiple-cursors deprecation

### ISSUE THREAD

**Issue by Aledosim** [amix/vimrc#604]
Since 30 July vim-multiple-cursors is officially deprecated, as stated in their [git page](https://github.com/terryma/vim-multiple-cursors). They indicate to use [vim-visual-multi](https://github.com/mg979/vim-visual-multi).

**Comment by amix** [comment]
Do any of you use vim-visual-multi? 

The issue I have is that `vim-multiple-cursors` is working very fine. I see no reason to migrate to something else.
