### ISSUE TITLE
Better than spacevim?

### ISSUE THREAD

**Issue by sisrfeng** [amix/vimrc#607]
Thank you for your cool work!
Is it like spacevim?
Which one is better?

**Comment by Thrimbda** [comment]
have a try and you'll find it out, 'Tis a topic too personal

**Comment by zeitounator** [comment]
The answer is 42.

**Comment by amix** [comment]
vimrc is indeed very personal 😂

I would recommend working on your own vimrc and using these as an inspiration source 👍
