### ISSUE TITLE
How can i install colorschemes

### ISSUE THREAD

**Issue by crydotsnake** [amix/vimrc#609]
How can i install new colorschemes?. Because if i move a colorscheme folder too `.vim_runtime/sources_non_forked` the colorscheme is not found.

**Comment by mhd53** [comment]
> How can i install new colorschemes?. Because if i move a colorscheme folder too `.vim_runtime/sources_non_forked` the colorscheme is not found.

Hi crydotsnake,

You can add a new colorscheme by simply making a .vim_runtime/colors/ directory and add your new colorschemes there.

**Comment by crydotsnake** [comment]
Hello !.

If i clone the Dracula Vim Theme to .vim_runtime/colors/ i get those error message:

```
Error when executing "/home/expl0it/.vimrc":
Line 9:
E185: Cannot find color scheme 'dracula
Line 11:
E919: directory not found in 'packpath': "pack/*/opt/dracula".
Press the ENTER key or enter a command

```

**Comment by mhd53** [comment]
Can you see if you can follow https://github.com/dracula/vim/blob/master/INSTALL.md by replacing mkdir -p ~/.vim/pack/themes/start with **mkdir -p ~/.vim_runtime/pack/themes/start** and touch ~/.vimrc with **vim ~/.vim_runtime/my_config.vim** and see if it works?  

Another option would be to use pathogen. See [amix/vimrc/include-own-stuff](https://github.com/amix/vimrc#how-to-include-your-own-stuff) and [dracula/Install-using-other-plugin-managers](https://github.com/amix/vimrc#how-to-include-your-own-stuff).

**Comment by crydotsnake** [comment]
> Can you see if you can follow https://github.com/dracula/vim/blob/master/INSTALL.md by replacing mkdir -p ~/.vim/pack/themes/start with mkdir -p ~/.vim_runtime/pack/themes/start and touch ~/.vimrc with vim ~/.vim_runtime/my_config.vim and see if it works?

Still the same error.

But what do you mean with `vim ~/.vim_runtime/my_config.vim` ?

**Comment by mhd53** [comment]
yeah so in the dracula's setup guide on step #4 it states to run `touch ~/.vimrc`. Instead of doing that try `touch ~/.vim_runtime/my_config.vim` since that's where you need to add your own settings to modify **amix/vimrc**'s behavior. 

Basically, add: 
```bash
packadd! dracula
syntax enable
colorscheme dracula
``` 
to `~/.vim_runtime/my_config.vim` in addition to `mkdir -p ~/.vim_runtime/pack/themes/start` and see if it works.

Note that you would need to run `git clone https://github.com/dracula/vim.git dracula` in `~/.vim_runtime/pack/themes/start` before all of the above.

**Comment by guianselmo** [comment]
> yeah so in the dracula's setup guide on step 4 it states to run `touch ~/.vimrc`. Instead of doing that try `touch ~/.vim_runtime/my_config.vim` since that's where you need to add your own settings to modify **amix/vimrc**'s behavior.
> 
> Basically, add:
> 
> ```shell
> packadd! dracula
> syntax enable
> colorscheme dracula
> ```
> 
> to `~/.vim_runtime/my_config.vim` in addition to `mkdir -p ~/.vim_runtime/pack/themes/start` and see if it works.
> 
> Note that you would need to run `git clone https://github.com/dracula/vim.git dracula` in `~/.vim_runtime/pack/themes/start` before all of the above.

Thanks for the steps. Just a small correction: make sure the file name is in plural, as `~/.vim_runtime/my_configs.vim`.
