### ISSUE TITLE
pasted text is auto-indented when in tmux

### ISSUE THREAD

**Issue by tekumara** [amix/vimrc#611]
When using tmux with amix/vimrc, pasted lines are incorrectly auto-indented.

eg: pasting this
```
if [[ ! -d ~/.vim_runtime ]]; then
    git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
    sh ~/.vim_runtime/install_awesome_vimrc.sh
fi
```

becomes
```
if [[ ! -d ~/.vim_runtime  ]]; then
         git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
             sh ~/.vim_runtime/install_awesome_vimrc.sh
             fi
```

Doesn't happen outside tmux.

**Comment by tekumara** [comment]
As a workaround, if I disable both of the following lines in _~/.vim_runtime/vimrcs/basic.vim_ the issue goes away:
```
set ai "Auto indent
set si "Smart indent
```

**Comment by tekumara** [comment]
Auto ident is enabled in _~/.vim_runtime/vimrcs/basic.vim_:
```
set ai "Auto indent
set si "Smart indent
```

Setting paste mode (`:,pp`) fixes this issue, but I'd rather this was automatic.

**Comment by tekumara** [comment]
Found a hint here: https://vi.stackexchange.com/questions/15722/vim-tmux-and-xterm-bracketed-paste

For me `TERM=screen-256color` so I've added this to ~/.vim_runtime/my_configs.vim:
```
 if &term =~ '^screen'
   let &t_BE="\<Esc>[?2004h"
   let &t_BD="\<Esc>[?2004l"
   let &t_PS="\<Esc>[200~"
   let &t_PE="\<Esc>[201~"
 endif
```

Possibly something that could be added to amix/vimrc?

**Comment by tekumara** [comment]
Found a hint here: https://vi.stackexchange.com/questions/15722/vim-tmux-and-xterm-bracketed-paste

For me `TERM=screen-256color` so I've added this to _~/.vim_runtime/my_configs.vim_:
```
 if &term =~ '^screen'
   let &t_BE="\<Esc>[?2004h"
   let &t_BD="\<Esc>[?2004l"
   let &t_PS="\<Esc>[200~"
   let &t_PE="\<Esc>[201~"
 endif
```

And it fixes the issue!

Could this possibly be something that's added to amix/vimrc?

**Comment by tekumara** [comment]
Found a hint here: https://vi.stackexchange.com/questions/15722/vim-tmux-and-xterm-bracketed-paste

For me `TERM=screen-256color` so I've added this to _~/.vim_runtime/my_configs.vim_:
```
if &term =~ '^screen'
  let &t_BE="\<Esc>[?2004h"
  let &t_BD="\<Esc>[?2004l"
  let &t_PS="\<Esc>[200~"
  let &t_PE="\<Esc>[201~"
endif
```

And it fixes the issue!

Could this possibly be something that's added to amix/vimrc?

**Comment by tekumara** [comment]
Found a hint here: https://vi.stackexchange.com/questions/15722/vim-tmux-and-xterm-bracketed-paste and mention of bracketed paste in vim's [term.txt](https://vimhelp.org/term.txt.html)

For me `TERM=screen-256color` so I've added this to _~/.vim_runtime/my_configs.vim_:
```
if &term =~ "screen"
    let &t_BE = "\e[?2004h"
    let &t_BD = "\e[?2004l"
    exec "set t_PS=\e[200~"
    exec "set t_PE=\e[201~"
endif
```

And it fixes the issue!

Could this possibly be something that's added to amix/vimrc?

**Comment by jxu** [comment]
You can have a shortcut key for pastetoggle, ex. `set pastetoggle=<F10>` 

https://stackoverflow.com/questions/13967356/vimrc-addition-to-toggle-set-paste

**Comment by amix** [comment]
The current mapping to toggle pastemode is `<leader>pp`
