### ISSUE TITLE
Error occurs after upgrading to vim 8.2.2250

### ISSUE THREAD

**Issue by syhily** [amix/vimrc#617]
```
Error detected while processing /Users/Yufan/.vimrc[5]../Users/Yufan/.vim_runtime/vimrcs/plugins_config.vim[13]..function pathogen#infect[3]..pathogen#surround
line    5:
E1004: White space required before and after ':'
E116: Invalid arguments for function pathogen#is_disabled(v:val[0:-7])
Press ENTER or type command to continue
```

**Comment by soaringk** [comment]
Same here

**Comment by soaringk** [comment]
It seems to be the problem of vim 8.2.2250, which is fixed in 8.2.2251: https://github.com/vim/vim/releases/tag/v8.2.2251

**Comment by syhily** [comment]
So I just cross my finger for the new homebrew bottle build which contains this patch release.

**Comment by soaringk** [comment]
> So I just cross my finger for the new homebrew bottle build which contains this patch release.

Just use time machine

**Comment by syhily** [comment]
Given this issue is not related to vimrc itself, I would close this issue.
