### ISSUE TITLE
Hope to add the theme of vim-one

### ISSUE THREAD

**Issue by tianyinggang** [amix/vimrc#619]
I want to used the color theme ,how to add [the theme](https://github.com/rakr/vim-one)

**Comment by burkebrunson** [comment]
I, too, am trying to work with color scheme. I can't even get vimrc to recognize other schemes that are supposed to be included (vim-colors-solarized, vim-irblack, mayansmoke, vim-pyte) when I edit the extended.vim file, line 32. Each time I open vim up again, it gives me an error that it can't find the color scheme. Is there a place someone can point to on how to update the color scheme?

**Comment by mvrogowski** [comment]
Did you already try to clone the theme in `~/.vim_runtime/my_plugins/ `and configure it in `~/.vim_runtime/my_configs.vim`?
