### ISSUE TITLE
<C-space> didn't work by Putty

### ISSUE THREAD

**Issue by mefengl** [amix/vimrc#622]
Hi!
My system is Windows10 20H2.
I use ubuntu20.01 by putty.
I found that ``<C-space>`` as well as many other keys don't work when I use Putty, Termius, Webshell or something like that.
But if I run vim locally, such as on git bash, it will work.
So it may be not the vimrc's problem, but if someone know what's going on, please tell me.
Thanks for your wonderful work!

**Comment by mrkanaly** [comment]
If what this SO says is true, this is associated with more the terminal than it is VIM. <C-space> is not an ASCII character so the terminal  https://stackoverflow.com/a/23190040

I am having trouble making <C-space> work in bash with vim or neovim.

Installing vim-gtk3 I was able to use some of the mappings like <C-space> in gvim.
