### ISSUE TITLE
vim problem when editing code

### ISSUE THREAD

**Issue by snsnsjsn** [amix/vimrc#628]
i have some display delay problem when editing code, it display stranger， could not see the really cursor position when i change the code.
https://github.com/amix/vimrc

it will occur the display problem all the paltform.
here is the screen capture recording

![tmux vim 错误](https://user-images.githubusercontent.com/11435527/112715323-7df40d80-8f1a-11eb-936a-6dec408ed6fc.gif)

**Comment by snsnsjsn** [comment]
when i search with location as keyword , there will also have display delay problem 
![vim wrong display](https://user-images.githubusercontent.com/11435527/112717517-49874e00-8f28-11eb-9f38-6abf3ea6fda0.gif)

**Comment by amix** [comment]
Try with the basic.vim version. It's most likely either a slow computer or some slow plugin that makes things very slow :(
