### ISSUE TITLE
SnipMate parser deprecated

### ISSUE THREAD

**Issue by HarrisonHemstreet** [amix/vimrc#635]
Hey I think this needs to get fixed. Here's what's happening:
`
hhemstreet@YOUNIQUE2780 rma % cd ~

hhemstreet@YOUNIQUE2780 ~ % sh ~/.vim_runtime/install_awesome_vimrc.sh
Installed the Ultimate Vim configuration successfully! Enjoy :-)

hhemstreet@YOUNIQUE2780 ~ % vim .
The legacy SnipMate parser is deprecated. Please see :h SnipMate-deprecate.
Press ENTER or type command to continue
`

**Comment by huangsam** [comment]
I'm encountering the the same thing as well:
```
The legacy SnipMate parser is deprecated. Please see :h SnipMate-deprecate.
Press ENTER or type command to continue
```
I've fixed it for now by reverting to the basic version of this repo: `sh ~/.vim_runtime/install_basic_vimrc.sh`

**Comment by comatosejones** [comment]
You an append this line to your .vimrc:

let g:snipMate = { 'snippet_version' : 1 }

**Comment by tekumara** [comment]
See resolution in https://github.com/amix/vimrc/pull/621

**Comment by amix** [comment]
This seems to be already fixed 👍
