### ISSUE TITLE
update_plugins.py remove git information of the installed plugins

### ISSUE THREAD

**Issue by wungjaelee** [amix/vimrc#636]
I tried to add YouCompleteMe plugin in the update_plugins.py.

Inside ~/.vim_runtime/sources_non_forked/YouCompleteMe, running `git remote -v` gives
```
origin	https://github.com/amix/vimrc.git (fetch)
origin	https://github.com/amix/vimrc.git (push)
```
rather than the original 
```
origin	https://github.com/ycm-core/YouCompleteMe.git (fetch)
origin	https://github.com/ycm-core/YouCompleteMe.git (push)
```

This is problematic because YouCompleteMe requires me to run
```
git submodule update --init --recursive
```
But with origin changed, the above line will take no effect.

Would it be possible to keep the git info of the installed plugins when running update_plugins.py?

**Comment by amix** [comment]
Check this section on how to include your own stuff:
https://github.com/amix/vimrc#how-to-include-your-own-stuff
