### ISSUE TITLE
Documentation for keeping `vimrc` up-to-date

### ISSUE THREAD

**Issue by atreyasha** [amix/vimrc#637]
Hi @amix and collaborators,

First off, thank you for developing and maintaining this awesome repository! I have some questions regarding the documentation for keeping `vimrc` up-to-date. As per the readme, below are the current instructions to keep this repository up-to-date:

> Just do a git rebase!
> ```
> cd ~/.vim_runtime
> git pull --rebase
> python update_plugins.py
> ```

I took a look at the `sources_non_forked` directory and noticed that most plugins there appear to be recently updated directly in this git repository.

Given this:

1. What would be the purpose of including `python update_plugins.py` as part of the update routine?

2. Would this not cause the user to have potentially different plugin versions compared to this repository's defaults, that too without warning because of the git-ignores?

3. Is `python update_plugins.py` necessary if the user just wants to mirror this repository?

**Comment by amix** [comment]
Thanks, @atreyasha. I mostly only use update_plugins.py to fetch the latest plugins. You can also use it if you want to use the latest plugins, but you don't think you need to use it. It's included, so it's easier to fork your own version.
