### ISSUE TITLE
Add documented way for plugins disabling

### ISSUE THREAD

**Issue by ofats** [amix/vimrc#640]
Hello!

I was looking for the options for a convenient plugins disabling (`auto-pairs` in particular) and found `g:pathogen_blacklist` list parameter.

However, it only works if specifying it before `pathogen#infect` calls, and so putting `let g:pathogen_blacklist = ['...']` to `~/.vim_runtime/my_configs.vim` (which, as I understand, should be the only place for user changes by design) doesn't work because by default `my_configs.vim` is evaluated after all the other configs.

Working solution is to specify `g:pathogen_blacklist` at the top of `~/.vimrc`. But it introduces another config file that should/could be modified alongside `my_configs.vim`.

Which plugins disabling approach is recommended and, if there is no such recommendation yet, should it be proposed and documented in README?

Possible solutions that I see:
1. Introduce `~/.vim_runtime/my_init_configs.vim` that will be evaluated before all the other configs (and update README);
2. Introduce `~/.vim_runtime/disabled_plugins.cfg` that will contain the list of disabled plugins and will be evaluated to the contents of `g:pathogen_blacklist` (and update README);
3. Only make addition to README saying that `~/.vimrc` is allowed to be modified and suggesting the proper use of `g:pathogen_blacklist` for plugins disabling.

**Comment by amix** [comment]
I recommend editing the `.vimrc` file directly and putting `let g:pathogen_blacklist = ...`  there. 👍
