### ISSUE TITLE
E1208 error

### ISSUE THREAD

**Issue by basheewang** [amix/vimrc#645]
Got an error as below:

Error detected while processing /home/coeus/.vim_runtime/sources_non_forked/tlib/plugin/02tlib.vim:
line   77: E1208: -complete used without -nargs
Error detected while processing /home/coeus/.vim_runtime/sources_non_forked/vim-fugitive/plugin/fugitive.vim:
line  431: E1208: -complete used without -nargs
line  432: E1208: -complete used without -nargs
line  436: E1208: -complete used without -nargs
line  440: E1208: -complete used without -nargs
Press ENTER or type command to continue

and here is my vim version:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 12 2021 12:01:34)
Included patches: 1-3154

**Comment by gbschenkel** [comment]
For me is just line 77on 02tlib.vim giving me problem. Previous I had none issue, i think i miss some python package which I had before.

I can get one more issue but with fugitive.vim if I not run the `python update_plugins.py` command.

**Comment by basheewang** [comment]
> For me is just line 77on 02tlib.vim giving me problem. Previous I had none issue, i think i miss some python package which I had before. I have just commented out the line for stop complaining, just for now.
> 
> I can get one more issue but with fugitive.vim if I not run the `python update_plugins.py` command.

I updated the whole repo, and now only one error left which is same as yours.

**Comment by qiujiangkun** [comment]
I have the same problem after upgrading my vim

**Comment by mkapiczy** [comment]
Same started happening to me today while running vim:

```
Error detected while processing /Users/michal/.vim_runtime/sources_non_forked/tlib/plugin/02tlib.vim:
line   77: E1208: -complete used without -nargsError detected while processing /Users/michal/.vim_runtime/sources_non_forked/vim-fugitive/plugin/fugitive.vim:
line  431: E1208: -complete used without -nargsline  432: E1208: -complete used without -nargsline  436: E1208: -complete used without -nargsline  440: E1208: -complete used without -nargsPress ENTER or type command to continue
```

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 11 2021 17:44:18)

**Comment by f0lg0** [comment]
Got the same error too after a system update:

```
Error detected while processing /home/f0lg0/.vim_runtime/sources_non_forked/tlib/plugin/02tlib.vim:
line   77: E1208: -complete used without -nargsError detected while processing /home/f0lg0/.vim_runtime/sources_non_forked/vim-fugitive/plugin/fugitive.vim:
line  431: E1208: -complete used without -nargsline  432: E1208: -complete used without -nargsline  436: E1208: -complete used without -nargsline  440: E1208: -complete used without -nargsPress ENTER or type command to continue
```

**Comment by shudiwsh2009** [comment]
Got the same error. The problem is caused by the tlib_vim & vim_fugitive plugins instead of .vimrc file itself. It can be solved temporarily by removing the "-complete" arg of the lines that report errors. Details can be found in the following links:
https://github.com/tpope/vim-fugitive/issues/1791
https://github.com/tpope/vim-fugitive/commit/4cdeff8c33ec2fe0686324bf1846ce158c452754
https://github.com/tomtom/tlib_vim/pull/30/files

**Comment by SofijaErkin** [comment]
Thanks @basheewang, Great!

I also met `VIM` plugins error:

    Error detected while processing /Users/yq/.vim_runtime/sources_non_forked/tlib/plugin/02tlib.vim:

    line   77: E1208: -complete used without allowing arguments

fixed with:

    cd /Users/yq/.vim_runtime/sources_non_forked/tlib/plugin/
    
    git pull --rebase

Also, thanks @qiujiangkun!

**Comment by loban** [comment]
Tried @SofijaErkin 's fix, and it worked perfectly. Thanks!

**Comment by humengyu2012** [comment]
> Thanks @basheewang, Great!
> 
> I also met `VIM` plugins error:
> 
> ```
> Error detected while processing /Users/yq/.vim_runtime/sources_non_forked/tlib/plugin/02tlib.vim:
> 
> line   77: E1208: -complete used without allowing arguments
> ```
> 
> fixed with:
> 
> ```
> cd /Users/yq/.vim_runtime/sources_non_forked/tlib/plugin/
> 
> git pull --rebase
> ```
> 
> Also, thanks @qiujiangkun!

It works for me, thanks.

**Comment by immissile** [comment]
> Thanks @basheewang, Great!
> 
> I also met `VIM` plugins error:
> 
> ```
> Error detected while processing /Users/yq/.vim_runtime/sources_non_forked/tlib/plugin/02tlib.vim:
> 
> line   77: E1208: -complete used without allowing arguments
> ```
> 
> fixed with:
> 
> ```
> cd /Users/yq/.vim_runtime/sources_non_forked/tlib/plugin/
> 
> git pull --rebase
> ```
> 
> Also, thanks @qiujiangkun!

It works for me 2, thanks.

**Comment by jameswilson** [comment]
Leaving this here, for some reason my `~/.vim_runtime/.git/config` configuration for the origin was set to `git://github.com/amix/vimrc.git`

This was causing me failures when trying to `git pull`.

I ran:

```
cd ~/.vim_runtime
git remote set-url origin git@github.com:amix/vimrc.git
git pull --rebase
```

And it all worked.

**Comment by makoshan** [comment]
Similar issue, resolved by updating tlib_vim
```
cd ~/.vim/bundle/tlib_vim/
git pull
```

**Comment by shenggaowei** [comment]
> > Thanks @basheewang, Great!
> > I also met `VIM` plugins error:
> > ```
> > Error detected while processing /Users/yq/.vim_runtime/sources_non_forked/tlib/plugin/02tlib.vim:
> > 
> > line   77: E1208: -complete used without allowing arguments
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > fixed with:
> > ```
> > cd /Users/yq/.vim_runtime/sources_non_forked/tlib/plugin/
> > 
> > git pull --rebase
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also, thanks @qiujiangkun!
> 
> It works for me, thanks.

it works,thank u
