### ISSUE TITLE
Need help: Scratch installation causes Error in02tlib.vim and fugitive.vim

### ISSUE THREAD

**Issue by loeschzwerg** [amix/vimrc#647]
Since yesterday I receive an error  when firing up vim.
I don't actually understand it quite well, so maybe someone could support me.
It doesn't seem to restrict the usage. Vim works like usual, it only shows this message on startup

```
$ vim
Error detected while processing /home/tn/.vim_runtime/sources_non_forked/tlib/plugin/02tlib.vim:
line   77: E1208: -complete used without -nargsError detected while processing /home/tn/.vim_runtime/sources_non_forked/vim-fugitive/plugin/fugitive.vim:
line  431: E1208: -complete used without -nargsline  432: E1208: -complete used without -nargsline  436: E1208: -complete used without -nargsline  440: E1208: -complete used without -nargsPress ENTER or type command to continue
```
I removed all .vim* dotfiles/folders and could start vim without any flaws (as expected).
I reinstalled this repo.
```
git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
sh ~/.vim_runtime/install_awesome_vimrc.sh
```
After that I received the exact same error message (unexpected).

So I guess it might have to do something with this config.

Fedora 34 / zsh (oh-my-zsh)

I couldn't find the error message online, only a fix  from 2015 regarding a different error and a note one would not be using vim.

**Comment by arewm** [comment]
This looks to be a duplicate of https://github.com/amix/vimrc/issues/645. A manual workaround is presented: https://github.com/amix/vimrc/issues/645#issuecomment-880528000 (i.e. delete the `-complete` clause wherever the error is thrown).

**Comment by loeschzwerg** [comment]
Thanks @arewm I'm gonna close this now and try the workaround on monday. 
I wonder why I couldn't find the issue via complete Error description.
