### ISSUE TITLE
Possible error in clone path in README.md

### ISSUE THREAD

**Issue by atreyasha** [amix/vimrc#658]
In the [`How to include your own stuff?`](https://github.com/amix/vimrc/blob/master/README.md#how-to-include-your-own-stuff) section of `README.md`, the following instructions (snippet) are mentioned:

> mkdir -p ~/.vim/pack/plugins/start
> Clone the plugin that you want in that directory, for example:
> git clone --depth=1 git://github.com/maxmellon/vim-jsx-pretty ~/.vim/pack/plugins/vim-jsx-pretty

Shouldn't any additional git repositories be cloned in `~/.vim/pack/plugins/start`?

In this case, I believe the correct path should be `~/.vim/pack/plugins/start/vim-jsx-pretty`.

**Comment by amix** [comment]
Yep! I'll fix this. Thanks for reporting, @atreyasha 🙏
