### ISSUE TITLE
Slow load of vim

### ISSUE THREAD

**Issue by zuhataslan** [amix/vimrc#662]
Vim opens very slowly

**Comment by zuhataslan** [comment]
And also, in insert mode, when pressing <TAB>, it takes quite some time before a tab is inserted in text

**Comment by email2jie** [comment]
main time eaters. very surprised that the themes takes up so much time even though none are used. 
~/.vim_runtime/sources_non_forked/ 
ale .140s
ctrlp.vim .032s
dracula .023s
gist .007s
goyo .008s
nerdtree .053s
lightline.vim .011s
mru.vim .014s
nginx.vim .02s
rust.vim .015s
tabular .01s
typescript .025s
vim-abolish .008s
vim-colors-solarized .03s
vim-commentary .014s
vim-fugitive .009s
vim-gist/ .03s
vim-gitgutter/ .01s
vim-indent-object/ .09s
vim-lastplace/ .038s
 vim-markdown/ .011s
 vim-pug/ .012s
 vim-pyte/ .025s
 vim-ruby/ .008s
 vim-snipmate .011s
 vim-surround .013s
 vim-yankstack/ .013s

**Comment by amix** [comment]
If speed is a concern, I would recommend just going with the basic version 👍

Also, you might want to try to upgrade your Vim (e.g., version 9).
