### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by wxfls** [amix/vimrc#663]
When I pressed F5 to run the"sizeof.cpp"file,it didn't work.This is the error message from terminal :

> /bin/bash: .//media/mike/archives/IT_Olympic/Yi_Ben_Tong/src/sizeof: No such file or directory
>real 0m0.001s
>user 0m0.001s
>sys 0m0.000s
>shell returned 127

PS:the"sizeof.cpp"file located in a mounted disk.

**Comment by amix** [comment]
I don't think this is vimrc realted 👍
