### ISSUE TITLE
How to permanently disable AutoPair?

### ISSUE THREAD

**Issue by WillNilges** [amix/vimrc#670]
AutoPair* isn't that great for my workflow. I found that I could disable it in tmux by spamming `<Esc>` and pressing `p`. However, this doesn't work if you use the [workaround](https://www.reddit.com/r/vim/comments/jcbhmh/vim_slow_on_tmux/) required to make vim in tmux tolerable. I looked around a bit in the configs, and couldn't find any mention of it. Can anyone help me out?

*It might not be AutoPair. What I'm talking about is the autocomplete of parenthesis, brackets, quotes, etc, that vimrc does when you use an opening pair. I find it kind of annoying.

**Comment by mvrogowski** [comment]
`let g:AutoPairsLoaded = 0` on your `my_configs.vim` should do the magic.
