### ISSUE TITLE
jedi-vim plugin not functioning?

### ISSUE THREAD

**Issue by tyrone877** [amix/vimrc#677]
New to amix,/vimrc.  Currently attempting to install the jedi-vim plugin.

I have cloned the repo into my_plugins, however still no autocompletion?

An error is generated when attempting to open python file....

jedi-vim: Error when loading the jedi python module (module 'jedi' has no attribute '__version__') Please ensure that Jedi is installed correctly.

**Comment by amix** [comment]
This isn't related to my vimrc. Please follow the guidelines here:
* https://github.com/davidhalter/jedi-vim
 
For the record, I have this working properly. Most likely, your Python<>Vim bindings are not working properly.
