### ISSUE TITLE
Syntax highlighting timeout for typescript files

### ISSUE THREAD

**Issue by disbelief** [amix/vimrc#680]
Hi there, this is a super helpful project thank you!

I recently installed the basic configuration and encountered this error when opening a typescript file:

```
'redrawtime' exceeded, syntax highlighting disabled
```

After a bit of googling I found [this blog post](https://jameschambers.co.uk/vim-typescript-slow) with the simple solution. Add the following line to `~/.vimrc`:

```
" Use new regular expression engine
set re=0
```
I added it below the `syntax enable` line in my vimrc file. Might be something to include in this package?

**Comment by amix** [comment]
@disbelief by default, it seems like `regexpengine` is set to `0` (at least on my machine). I'll make this a default tho'.
