### ISSUE TITLE
Persistant Yank history

### ISSUE THREAD

**Issue by matttbe** [amix/vimrc#683]
Hello,

First, thank you for maintaining this nice project. It helps a lot to setup a new dev env!

Recently, I switched to a laptop using an old version of vim runtime. I updated it and everything worked fine except that I no longer have a persistent "yank" history: if I edit one file, yank a line (`yy`), exit, open a file (same or different one), I can no longer paste what I copied before with `p`.

I think I was using YankRing instead of yank-stack in my old version because according to `git reflog`, I was on top of 095230d6 commit before.

Is it a normal behaviour with vim-yankstack? How can I get a persistent history like before with YankRing?

**Comment by amix** [comment]
Hi @matttbe 

AFAIK vim-yankstack does not support persistent history. YankRing isn't maintained any longer :(
