### ISSUE TITLE
How to reduce the priority of my_plugin folder ?

### ISSUE THREAD

**Issue by baimengwei** [amix/vimrc#685]
I installed a plugin in the folder my_plugin . This plugin makes the tab button unable to automatically generate the function structure.

There is a conflict between them.

except uninstalling the plugin, is there any good way?

**Comment by amix** [comment]
You could directly change the `.vimrc` file not to prioritize your plugins.

<img width="1229" alt="CleanShot 2022-10-15 at 21 32 10@2x" src="https://user-images.githubusercontent.com/184462/196004689-fb06149e-d81f-4719-aac4-534acfef75b6.png">
