### ISSUE TITLE
How to delete a blank at the first position of every line in a opened file?

### ISSUE THREAD

**Issue by meocean** [amix/vimrc#686]
When i have installed one mode of the vimrc, there is a blank at the first position of every line in a opened file. As a result, everything copied from this file in vim have these blanks also, and i couldn.t find a configure in .vimrc or .vim_runtime to solve this problem, did anyone have this problem and solved it, please help me!

**Comment by ukushisanet** [comment]
Hi,

This settings is set in the `basic.vim`:

https://github.com/amix/vimrc/blob/master/vimrcs/basic.vim#L127-L128

You can override it in your `~/.vim_runtime/my_configs.vim` with:
```
set foldcolumn=0
```
