### ISSUE TITLE
Using : covers whole window (windows 10)

### ISSUE THREAD

**Issue by VenkatVoni** [amix/vimrc#689]
Using : commands while using vim in the command prompt console covers the whole screen and renders the content needed to be edited invisible.   
For example : 

![image](https://user-images.githubusercontent.com/58286318/156512910-2d9ba05e-fc24-4e93-84be-bc4667a035a8.png)  

![image](https://user-images.githubusercontent.com/58286318/156513042-4f7cd41f-bc97-4115-98ac-ea91d205a5bb.png)

**Comment by amix** [comment]
This isn't something I can reproduce. Most likely, it's related to your Vim installation.
