### ISSUE TITLE
Cannot change the shape of cursor between modes. 

### ISSUE THREAD

**Issue by acemarco1311** [amix/vimrc#704]
Hi everyone, 

I'm using CMDer terminal emulator for Vim, previously, the cursor will be automatically switch to a thin vertical bar when entering "Insert mode". 

However, recently, I re-install  Vim and the cursor was changed to a rectangle. I've been trying various ways that I could find on Reddit/Stackoverflow but it seems that there is no way to change the shape of the cursor. 

Is there something wrong in the basic.vim or extended.vim that does not allow the cursor to be changed?

**Comment by amix** [comment]
This isn't related to my vimrc 👍 Please check your vim installation.
