### ISSUE TITLE
Whenever pasting; it auto tabs ever new-line

### ISSUE THREAD

**Issue by aharo24** [amix/vimrc#711]
<img width="1792" alt="Screen Shot 2022-08-26 at 2 58 42 PM" src="https://user-images.githubusercontent.com/52618896/186996238-afb8c67d-d5c0-4897-a2bd-64b4924c1d96.png">

I tried a couple of stack-overflow to see if there is a fix but none helped

**Comment by amix** [comment]
You need to do `:set paste` or do `<leader>pp` to toggle the paste mode. See here for more info:
https://techexplorations.com/blog/kicad/blog-how-to-copy-text-into-vim/
