### ISSUE TITLE
Use inline comments for many set commands

### ISSUE THREAD

**Issue by jxu** [amix/vimrc#713]
This makes it much easier to read in certain situations, for example

```vim
" => General
set history=1000                " Save more commands
set autoread                    " Read file when changed externally
set autowrite                   " Autosave before commands like :make
set noswapfile                  " No more .swp!
```
However there may be line length issues. And this doesn't work for map commands, at least without trailing `|` https://stackoverflow.com/questions/24716804/inline-comments-in-vimrc-mappings

**Comment by amix** [comment]
Hi @jxu 

You can always add these in `my_configs.vim` 👍
