### ISSUE TITLE
Error detected while processing BufRead Autocommands for "*.py"..FileType

### ISSUE THREAD

**Issue by deepyaman** [amix/vimrc#716]
I just installed the basic version today, and I'm getting the following error when editing Python scripts. It seems to be happening in the relatively-newly-added `jedi-vim` plugin.

FWIW I'm on an M2 Mac, in case there's some sort of issue with M2s (I'd imagine not?).

```
Error detected while processing BufRead Autocommands for "*.py"..FileType Autocommands for "*"..function <SNR>5_LoadFTPlugin[18]..script /Users/deepyaman/.vim_runtime/sources_non_forked/jedi-vim/ftplugin/pyth
on/jedi.vim[1]../Users/deepyaman/.vim_runtime/sources_non_forked/jedi-vim/autoload/jedi.vim[260]..function jedi#init_python[13]..BufRead Autocommands for "*.py"..FileType Autocommands for "*"..function <SNR>5
_LoadFTPlugin[18]..script /Users/deepyaman/.vim_runtime/sources_non_forked/jedi-vim/ftplugin/python/jedi.vim[1]../Users/deepyaman/.vim_runtime/sources_non_forked/jedi-vim/autoload/jedi.vim[260]..function jedi
#init_python[11]..<SNR>117_display_exception:
line   19:
Error: jedi-vim failed to initialize Python: jedi-vim requires Vim with support for Python 3. (in BufRead Autocommands for "*.py"..FileType Autocommands for "*"..function <SNR>5_LoadFTPlugin[18]..script /User
s/deepyaman/.vim_runtime/sources_non_forked/jedi-vim/ftplugin/python/jedi.vim[1]../Users/deepyaman/.vim_runtime/sources_non_forked/jedi-vim/autoload/jedi.vim[260]..function jedi#init_python[4]..<SNR>117_init_
python, line 4)
Error detected while processing BufRead Autocommands for "*.py"..FileType Autocommands for "*"..function <SNR>5_LoadFTPlugin[18]..script /Users/deepyaman/.vim_runtime/sources_non_forked/jedi-vim/ftplugin/pyth
on/jedi.vim:
line   36:
E117: Unknown function: jedi#configure_call_signatures
```

**Comment by charlesbo** [comment]
Seems like missing submodule 'jedi' under *.vim_runtime/sources_non_forked/jedi-vim*, and jedi-vim won't look for the one installed in virtualenv.

**Comment by zorancupic** [comment]
I'm getting the same error on M1 Mac

`Error detected while processing BufRead Autocommands for "*.py"..FileType Autocommands for "*"..function <SNR>5_LoadFTPlugin[18]..script /Users/user/.vim_run
time/sources_non_forked/jedi-vim/ftplugin/python/jedi.vim[1]../Users/user/.vim_runtime/sources_non_forked/jedi-vim/autoload/jedi.vim[260]..function jedi#init
_python[13]..BufRead Autocommands for "*.py"..FileType Autocommands for "*"..function <SNR>5_LoadFTPlugin[18]..script /Users/user/.vim_runtime/sources_non_fo
rked/jedi-vim/ftplugin/python/jedi.vim[1]../Users/user/.vim_runtime/sources_non_forked/jedi-vim/autoload/jedi.vim[260]..function jedi#init_python[11]..<SNR>1
17_display_exception:
line   19:
Error: jedi-vim failed to initialize Python: jedi-vim requires Vim with support for Python 3. (in BufRead Autocommands for "*.py"..FileType Autocommands for "*
"..function <SNR>5_LoadFTPlugin[18]..script /Users/user/.vim_runtime/sources_non_forked/jedi-vim/ftplugin/python/jedi.vim[1]../Users/user/.vim_runtime/sour
ces_non_forked/jedi-vim/autoload/jedi.vim[260]..function jedi#init_python[4]..<SNR>117_init_python, line 4)
Error detected while processing BufRead Autocommands for "*.py"..FileType Autocommands for "*"..function <SNR>5_LoadFTPlugin[18]..script /Users/user/.vim_run
time/sources_non_forked/jedi-vim/ftplugin/python/jedi.vim:
line   36:
E117: Unknown function: jedi#configure_call_signatures`

**Comment by ptpt** [comment]
Anyone knows how to disable it?

**Comment by lihaolong** [comment]
Got the same problem on ubuntu

**Comment by zbwgreen** [comment]
You need install jedi at first
```python
pip install jedi
```

**Comment by deepyaman** [comment]
> You need install jedi at first
> 
> ```python
> pip install jedi
> ```

@zbwgreen Where? I'm using Conda, and it doesn't work to install it in my Conda env (probably related to how @charlesbo said it won't look for the one in virtualenv), and it wouldn't make sense to have to install it in each env anyway.

@amix Thanks for removing! I will upgrade.
