### ISSUE TITLE
Installation script says that it installed even tho vim is not installed.

### ISSUE THREAD

**Issue by supopur** [amix/vimrc#724]
I didnt have vim installed and ran the install script for the ultimate edition the script said Installed the Ultimate Vim configuration successfully! Enjoy :-) even tho vim wasnt installed.

**Comment by Katono5** [comment]
I faced the same problem on Windows 11
![image](https://user-images.githubusercontent.com/61302913/226099802-5652d416-aed1-4dd5-bbe5-8ee62f34c803.png)

![image](https://user-images.githubusercontent.com/61302913/226099822-25482ee5-7571-4b53-8d30-332cfd5acc9f.png)

**Comment by amix** [comment]
I don't think this is a problem with this vimrc, but your vim installation 👍
