### ISSUE TITLE
my_config.vim didn't work?

### ISSUE THREAD

**Issue by simpsonetti** [amix/vimrc#725]
Hi, i'm "working" with vim for many years, but never the way it's meant to be. I used it more than a Text-gui-editor. 
Nevertheless, i wan't to increase my skills now and teaching me by viewing some yt-vids and reading (yes i do this) and so i stumbeld over vim_runtime. I try to use this on my maschines i logged into. 
I try to use a own-config and create the my_config.vim file and set there some options. 
So and thats the issue: how do i know that my_config would be used? I set this option:
set relativenumber 
but this isn't be stored and every time i start vim, i have to set it manualy. So how could i check tha my_config.vim would be used?
Thanks.

**Comment by andykrantz** [comment]
I'm having trouble with my_configs.vim as well. 

I'm trying to override the colorscheme in ~/.vim_runtime/my_configs.vim but it doesn't get applied.

**Comment by amix** [comment]
Try to ensure that your `~/.vimrc` looks like this:
```vim
set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
source ~/.vim_runtime/my_configs.vim
```

You likely have an error in your my_configs.vim file 👍
