### ISSUE TITLE
How do I turn off auto-pairs in my_configs.vim

### ISSUE THREAD

**Issue by mattskanaut** [amix/vimrc#726]
Firstly, can I say thank you!  Your vimrc is truly awesome, and very appreciated.

One thing though, I can't work with autoclosing of quotes, brackets, anything.  Is there an easy way of turning all that off in my_configs.vim without butchering the plugins directory?  I tried adding "call AutoPairsToggle()", but that didn't work.  I also tried adding

let g:pathogen_disabled = []
call add(g:pathogen_disabled, 'auto-pairs')

to my_configs.vim

I'm no vimrc expert, so sorry if this is obvious, but how can I do this easily?

**Comment by ahberg** [comment]
https://github.com/amix/vimrc/issues/670

**Comment by amix** [comment]
You could just remove the directory, e.g.,:
```bash
rm -rf ~/.vim_runtime/sources_non_forked/auto-pairs
```
