### ISSUE TITLE
did i have something wrong?

### ISSUE THREAD

**Issue by devqin** [amix/vimrc#73]
Error detected while processing /home/devqin/.vim_runtime/vimrcs/basic.vim:
line   66:
E174: Command already exists: add ! to replace it
--- Auto-Commands ---
filetypedetect  BufRead
_if !did_filetype() && expand("<amatch>") !~ g:ft_ignore_pat | runtime! scripts.vim | endif
*if !did_filetype() && expand("<amatch>") !~ g:ft_ignore_pat    && (getline(1) =~ '^#' || getline(2) =~ '^#' || getline(3) =~ '^#'^I|| getline(4) =~ '^#' || getline(5) =~ '^#') |   setf conf | endif
line  249:
E10: \ should be followed by /, ? or &
line  250:
E10: \ should be followed by /, ? or &
line  251:
E10: \ should be followed by /, ? or &
Error detected while processing /home/devqin/.vim_runtime/sources_non_forked/ctrlp.vim/plugin/ctrlp.vim:
line   13:
E475: Invalid argument: 
line   14:
E10: \ should be followed by /, ? or &
line   15:
E10: \ should be followed by /, ? or &
Error detected while processing function ctrlp#mrufiles#opts:
line    1:
E15: Invalid expression: 
E15: Invalid expression: ['g:ctrlp_mruf_', {
line    2:
E10: \ should be followed by /, ? or &
line    3:
E10: \ should be followed by /, ? or &
line    4:
E10: \ should be followed by /, ? or &
line    5:
E10: \ should be followed by /, ? or &
line    6:
E10: \ should be followed by /, ? or &
line    7:
E10: \ should be followed by /, ? or &
line    8:
E10: \ should be followed by /, ? or &
line    9:
E121: Undefined variable: opts
E116: Invalid arguments for function items(opts)
E15: Invalid expression: items(opts)
Error detected while processing /home/devqin/.vim_runtime/sources_non_forked/ctrlp.vim/plugin/ctrlp.vim:
line   46:
E10: \ should be followed by /, ? or &
line   49:
E10: \ should be followed by /, ? or &
line   56:
E10: \ should be followed by /, ? or &
line   59:
E10: \ should be followed by /, ? or &
line   66:
E10: \ should be followed by /, ? or &
Error detected while processing /home/devqin/.vim_runtime/sources_non_forked/syntastic/plugin/syntastic.vim:
line   51:
E15: Invalid expression: 
E15: Invalid expression: {
line   52:
E10: \ should be followed by /, ? or &
line   53:
E10: \ should be followed by /, ? or &
line   54:
E10: \ should be followed by /, ? or &
line   55:
E10: \ should be followed by /, ? or &
line   56:
E10: \ should be followed by /, ? or &
line   57:
E10: \ should be followed by /, ? or &
line   58:
E10: \ should be followed by /, ? or &
line   59:
E10: \ should be followed by /, ? or &
line   60:
E10: \ should be followed by /, ? or &
line   61:
E10: \ should be followed by /, ? or &
line   62:
E10: \ should be followed by /, ? or &
line   63:
E10: \ should be followed by /, ? or &
line   64:
E10: \ should be followed by /, ? or &
line   65:
E10: \ should be followed by /, ? or &
line   66:
E10: \ should be followed by /, ? or &
line   67:
E10: \ should be followed by /, ? or &
line   68:
E10: \ should be followed by /, ? or &
line   69:
E10: \ should be followed by /, ? or &
line   70:
E10: \ should be followed by /, ? or &
line   71:
E10: \ should be followed by /, ? or &
line   72:
E10: \ should be followed by /, ? or &
line   73:
E10: \ should be followed by /, ? or &
line   74:
E10: \ should be followed by /, ? or &
line   75:
E10: \ should be followed by /, ? or &
line   76:
E10: \ should be followed by /, ? or &
line   77:
E10: \ should be followed by /, ? or &
line   80:
E121: Undefined variable: g:syntastic_defaults
E116: Invalid arguments for function keys(g:syntastic_defaults)
E15: Invalid expression: keys(g:syntastic_defaults)
line  102:
E697: Missing end of List ']': 
E15: Invalid expression: [
line  103:
E10: \ should be followed by /, ? or &
line  104:
E10: \ should be followed by /, ? or &
line  105:
E10: \ should be followed by /, ? or &
line  106:
E10: \ should be followed by /, ? or &
line  107:
E10: \ should be followed by /, ? or &
line  108:
E10: \ should be followed by /, ? or &
line  109:
E10: \ should be followed by /, ? or &
line  110:
E10: \ should be followed by /, ? or &
line  111:
E10: \ should be followed by /, ? or &
line  113:
E121: Undefined variable: s:debug_dump_options
E116: Invalid arguments for function add
Error detected while processing /home/devqin/.vim_runtime/sources_non_forked/syntastic/plugin/syntastic/registry.vim:
line    8:
E15: Invalid expression: 
E15: Invalid expression: {
line    9:
E10: \ should be followed by /, ? or &
line   10:
E10: \ should be followed by /, ? or &
line   11:
E10: \ should be followed by /, ? or &
line   12:
E10: \ should be followed by /, ? or &
line   13:
E10: \ should be followed by /, ? or &
line   14:
E10: \ should be followed by /, ? or &
line   15:
E10: \ should be followed by /, ? or &
line   16:
E10: \ should be followed by /, ? or &
line   17:
E10: \ should be followed by /, ? or &
line   18:
E10: \ should be followed by /, ? or &
line   19:
E10: \ should be followed by /, ? or &
line   20:
E10: \ should be followed by /, ? or &
line   21:
E10: \ should be followed by /, ? or &
line   22:
E10: \ should be followed by /, ? or &
line   23:
E10: \ should be followed by /, ? or &
line   24:
E10: \ should be followed by /, ? or &
line   25:
E10: \ should be followed by /, ? or &
line   26:
E10: \ should be followed by /, ? or &
line   27:
E10: \ should be followed by /, ? or &
line   28:
E10: \ should be followed by /, ? or &
line   29:
E10: \ should be followed by /, ? or &
line   30:
E10: \ should be followed by /, ? or &
line   31:
E10: \ should be followed by /, ? or &
line   32:
E10: \ should be followed by /, ? or &
line   33:
E10: \ should be followed by /, ? or &
line   34:
E10: \ should be followed by /, ? or &
line   35:
E10: \ should be followed by /, ? or &
line   36:
E10: \ should be followed by /, ? or &
line   37:
E10: \ should be followed by /, ? or &
line   38:
E10: \ should be followed by /, ? or &
line   39:
E10: \ should be followed by /, ? or &
line   40:
E10: \ should be followed by /, ? or &
line   41:
E10: \ should be followed by /, ? or &
line   42:
E10: \ should be followed by /, ? or &
line   43:
E10: \ should be followed by /, ? or &
line   44:
E10: \ should be followed by /, ? or &
line   45:
E10: \ should be followed by /, ? or &
line   46:
E10: \ should be followed by /, ? or &
line   47:
E10: \ should be followed by /, ? or &
line   48:
E10: \ should be followed by /, ? or &
line   49:
E10: \ should be followed by /, ? or &
line   50:
E10: \ should be followed by /, ? or &
line   51:
E10: \ should be followed by /, ? or &
line   52:
E10: \ should be followed by /, ? or &
line   53:
E10: \ should be followed by /, ? or &
line   54:
E10: \ should be followed by /, ? or &
line   55:
E10: \ should be followed by /, ? or &
line   56:
E10: \ should be followed by /, ? or &
line   57:
E10: \ should be followed by /, ? or &
line   58:
E10: \ should be followed by /, ? or &
line   59:
E10: \ should be followed by /, ? or &
line   60:
E10: \ should be followed by /, ? or &
line   61:
E10: \ should be followed by /, ? or &
line   62:
E10: \ should be followed by /, ? or &
line   63:
E10: \ should be followed by /, ? or &
line   64:
E10: \ should be followed by /, ? or &
line   65:
E10: \ should be followed by /, ? or &
line   66:
E10: \ should be followed by /, ? or &
line   67:
E10: \ should be followed by /, ? or &
line   68:
E10: \ should be followed by /, ? or &
line   69:
E10: \ should be followed by /, ? or &
line   70:
E10: \ should be followed by /, ? or &
line   71:
E10: \ should be followed by /, ? or &
line   72:
E10: \ should be followed by /, ? or &
line   73:
E10: \ should be followed by /, ? or &
line   74:
E10: \ should be followed by /, ? or &
line   75:
E10: \ should be followed by /, ? or &
line   76:
E10: \ should be followed by /, ? or &
line   77:
E10: \ should be followed by /, ? or &
line   78:
E10: \ should be followed by /, ? or &
line   79:
E10: \ should be followed by /, ? or &
line   80:
E10: \ should be followed by /, ? or &
line   81:
E10: \ should be followed by /, ? or &
line   82:
E10: \ should be followed by /, ? or &
line   83:
E10: \ should be followed by /, ? or &
line   84:
E10: \ should be followed by /, ? or &
line   85:
E10: \ should be followed by /, ? or &
line   86:
E10: \ should be followed by /, ? or &
line   87:
E10: \ should be followed by /, ? or &
line   88:
E10: \ should be followed by /, ? or &
line   89:
E10: \ should be followed by /, ? or &
line   90:
E10: \ should be followed by /, ? or &
line   91:
E10: \ should be followed by /, ? or &
line   92:
E10: \ should be followed by /, ? or &
line   95:
E15: Invalid expression: 
E15: Invalid expression: {
line   96:
E10: \ should be followed by /, ? or &
line   97:
E10: \ should be followed by /, ? or &
line   98:
E10: \ should be followed by /, ? or &
line   99:
E10: \ should be followed by /, ? or &
Error detected while processing function 248..251..263..266:
line   22:
E121: Undefined variable: g:syntastic_error_symbol
E15: Invalid expression: 'sign define SyntasticError text=' . g:syntastic_error_symbol .
line   23:
E10: \ should be followed by /, ? or &
line   24:
E121: Undefined variable: g:syntastic_warning_symbol
E15: Invalid expression: 'sign define SyntasticWarning text=' . g:syntastic_warning_symbol .
line   25:
E10: \ should be followed by /, ? or &
line   26:
E121: Undefined variable: g:syntastic_style_error_symbol
E15: Invalid expression: 'sign define SyntasticStyleError text=' . g:syntastic_style_error_symbol .
line   27:
E10: \ should be followed by /, ? or &
line   28:
E121: Undefined variable: g:syntastic_style_warning_symbol
E15: Invalid expression: 'sign define SyntasticStyleWarning text=' . g:syntastic_style_warning_symbol .
line   29:
E10: \ should be followed by /, ? or &
Error detected while processing /home/devqin/.vim_runtime/sources_non_forked/syntastic/plugin/syntastic.vim:
line  166:
E10: \ should be followed by /, ? or &
line  167:
E10: \ should be followed by /, ? or &
line  170:
E10: \ should be followed by /, ? or &
line  171:
E10: \ should be followed by /, ? or &
No user-defined commands found
line  173:
E10: \ should be followed by /, ? or &
line  174:
E10: \ should be followed by /, ? or &
Error detected while processing /home/devqin/.vim_runtime/sources_non_forked/vim-airline/autoload/airline.vim:
line  109:
E697: Missing end of List ']': 
E15: Invalid expression: [
line  110:
E10: \ should be followed by /, ? or &
line  111:
E10: \ should be followed by /, ? or &
--- Auto-Commands ---
Error detected while processing function <SNR>56_airline_toggle:
line   18:
E10: \ should be followed by /, ? or &
line   19:
E10: \ should be followed by /, ? or &
--- Auto-Commands ---
BufExplorerVimEnter  VimEnter
*call s:BESetup()
NERDTreeHijackNetrw  VimEnter
*silent! autocmd! FileExplorer
call nerdtree#checkForBrowse(expand("<amatch>"))
filetypeplugin  FileType
*call s:LoadFTPlugin()
filetypeindent  FileType
*call s:LoadIndent()
syntaxset  FileType
*exe "set syntax=" . expand("<amatch>")
line   24:
E10: \ should be followed by /, ? or &
--- Auto-Commands ---
line   27:
E10: \ should be followed by /, ? or &
line   28:
E10: \ should be followed by /, ? or &
Error detected while processing /home/devqin/.vim_runtime/sources_non_forked/vim-fugitive/plugin/fugitive.vim:
line 1069:
E15: Invalid expression: 
E116: Invalid arguments for function <SNR>61_command
line 1070:
E10: \ should be followed by /, ? or &
line 1071:
E15: Invalid expression: 
E116: Invalid arguments for function <SNR>61_command
line 1072:
E10: \ should be followed by /, ? or &
line 1103:
E10: \ should be followed by /, ? or &
line 1104:
E10: \ should be followed by /, ? or &
line 1105:
E10: \ should be followed by /, ? or &
line 1106:
E10: \ should be followed by /, ? or &
line 1107:
E10: \ should be followed by /, ? or &
line 1108:
E10: \ should be followed by /, ? or &
--- Auto-Commands ---
fugitive  BufWinLeave
*execute getwinvar(+bufwinnr(+expand('<abuf>')), 'fugitive_leave')
line 1572:
E10: \ should be followed by /, ? or &
line 1573:
E10: \ should be followed by /, ? or &
line 1574:
E10: \ should be followed by /, ? or &
--- Auto-Commands ---
line 1576:
E10: \ should be followed by /, ? or &
line 1577:
E10: \ should be followed by /, ? or &
line 1578:
E10: \ should be followed by /, ? or &
line 1815:
E10: \ should be followed by /, ? or &
line 1816:
E10: \ should be followed by /, ? or &
line 1817:
E10: \ should be followed by /, ? or &
--- Auto-Commands ---
line 2569:
E10: \ should be followed by /, ? or &
line 2570:
E10: \ should be followed by /, ? or &
line 2571:
E10: \ should be followed by /, ? or &
line 2572:
E10: \ should be followed by /, ? or &
line 2573:
E10: \ should be followed by /, ? or &
line 2574:
E10: \ should be followed by /, ? or &
--- Auto-Commands ---
line 2581:
E10: \ should be followed by /, ? or &
line 2582:
E10: \ should be followed by /, ? or &
line 2583:
E10: \ should be followed by /, ? or &
--- Auto-Commands ---
filetypedetect  BufNewFile
*if !did_filetype() && expand("<amatch>") !~ g:ft_ignore_pat | runtime! scripts.vim | endif
*call s:DetectCoffee()
*if !did_filetype() && expand("<amatch>") !~ g:ft_ignore_pat    && (getline(1) =~ '^#' || getline(2) =~ '^#' || getline(3) =~ '^#'^I|| getline(4) =~ '^#' || getline(5) =~ '^#') |   setf conf | endif
fugitive  BufNewFile
*call fugitive#detect(expand('<amatch>:p'))
filetypedetect  BufRead
*if !did_filetype() && expand("<amatch>") !~ g:ft_ignore_pat | runtime! scripts.vim | endif
*call s:DetectCoffee()
*if !did_filetype() && expand("<amatch>") !~ g:ft_ignore_pat    && (getline(1) =~ '^#' || getline(2) =~ '^#' || getline(3) =~ '^#'^I|| getline(4) =~ '^#' || getline(5) =~ '^#') |   setf conf | endif
syntastic  BufRead
*call s:BufReadPostHook()
fugitive  BufRead
*call fugitive#detect(expand('<amatch>:p'))
line 2595:
E10: \ should be followed by /, ? or &
line 2596:
E10: \ should be followed by /, ? or &
line 2597:
E10: \ should be followed by /, ? or &
line 2598:
E10: \ should be followed by /, ? or &
line 2599:
E10: \ should be followed by /, ? or &
line 2600:
E10: \ should be followed by /, ? or &
line 2601:
E10: \ should be followed by /, ? or &
line 2602:
E10: \ should be followed by /, ? or &
--- Auto-Commands ---
fugitive_utility  User
Fugitivecall s:define_commands()
fugitive_remove  User
Fugitiveif s:buffer().commit() =~# '^0\=$' |
fugitive_blame  User
Fugitiveif s:buffer().type('file', 'blob') | exe "command! -buffer -bar -bang -range=0 -nargs=_ Gblame :execute s:Blame(<bang>0,<line1>,<line2>,<count>,[<f-args>])" | endif
line 2877:
E10: \ should be followed by /, ? or &
line 2878:
E10: \ should be followed by /, ? or &
line 2879:
E10: \ should be followed by /, ? or &
Error detected while processing /home/devqin/.vim_runtime/sources_non_forked/vim-zenroom2/plugin/zenroom2.vim:
line   65:
E128: Function name must start with a capital or "s:": g:zenroom_goyo_before()
line   67:
E133: :return not inside a function
line   74:
E193: :endfunction not inside a function
line   76:
E128: Function name must start with a capital or "s:": g:zenroom_goyo_after()
line   78:
E133: :return not inside a function
line   88:
E193: :endfunction not inside a function
line   90:
E700: Unknown function: g:zenroom_goyo_before
E700: Unknown function: g:zenroom_goyo_after
Error detected while processing /home/devqin/.vim_runtime/sources_forked/yankring/plugin/yankring.vim:
line  237:
E15: Invalid expression: 
E15: Invalid expression: 
line  238:
E10: \ should be followed by /, ? or &
line  239:
E10: \ should be followed by /, ? or &
line  240:
E10: \ should be followed by /, ? or &
line  241:
E10: \ should be followed by /, ? or &
line  242:
E15: Invalid expression: 
E15: Invalid expression: 
line  243:
E10: \ should be followed by /, ? or &
line  244:
E10: \ should be followed by /, ? or &
line  245:
E10: \ should be followed by /, ? or &
line  246:
E10: \ should be followed by /, ? or &
Error detected while processing function <SNR>73_YRInit..<SNR>73_YRHistoryRead:
line    3:
E121: Undefined variable: s:yr_history_file_v2
E15: Invalid expression: s:yr_history_file_{s:yr_history_version}
line    5:
E121: Undefined variable: yr_filename
E116: Invalid arguments for function filereadable(yr_filename)
E15: Invalid expression: filereadable(yr_filename)
Error detected while processing function <SNR>73_YRInit..<SNR>73_YRHistoryRead..<SNR>73_YRHistorySave:
line    6:
E121: Undefined variable: s:yr_history_file_v2
E116: Invalid arguments for function writefile(s:yr_history_list, s:yr_history_file_{s:yr_history_version})
E15: Invalid expression: writefile(s:yr_history_list, s:yr_history_file_{s:yr_history_version})
line    8:
E121: Undefined variable: rc
E15: Invalid expression: rc == 0
line   13:
E10: \ should be followed by /, ? or &
line   14:
E10: \ should be followed by /, ? or &
line   15:
E10: \ should be followed by /, ? or &
Error detected while processing function <SNR>73_YRHistoryRead:
line    3:
E121: Undefined variable: s:yr_history_file_v2
E15: Invalid expression: s:yr_history_file_{s:yr_history_version}
line    5:
E121: Undefined variable: yr_filename
E116: Invalid arguments for function filereadable(yr_filename)
E15: Invalid expression: filereadable(yr_filename)
Error detected while processing function <SNR>73_YRHistoryRead..<SNR>73_YRHistorySave:
line    6:
E121: Undefined variable: s:yr_history_file_v2
E116: Invalid arguments for function writefile(s:yr_history_list, s:yr_history_file_{s:yr_history_version})
E15: Invalid expression: writefile(s:yr_history_list, s:yr_history_file_{s:yr_history_version})
line    8:
E121: Undefined variable: rc
E15: Invalid expression: rc == 0
line   13:
E10: \ should be followed by /, ? or &
line   14:
E10: \ should be followed by /, ? or &
line   15:
E10: \ should be followed by /, ? or &
Press ENTER or type command to continue

**Comment by benwr** [comment]
What was the result of this? I suddenly have the same problem.

**Comment by benwr** [comment]
Ah, at least for me, this ended up being because I had accidentally installed the wrong version of vim-runtime.
