### ISSUE TITLE
HowTo add pluguns

### ISSUE THREAD

**Issue by simpsonetti** [amix/vimrc#730]
Hi there, 
i'm using vim_runtime and for me it's awesome. 
But iss there a regular way to add plugins? Yes i know the folder "my_plugins" and i add one there. But what i mean is more than like it is in VSCode or "big" ide like that, where you could search a online-repo with plugins and add there right there. 

And where do you search for you plugins? 
Regards Sebastian

**EDIT** there intentions for my question is there "right" way to update the plugins. And if it is possible with vim_runtime method it would be great.

**Comment by ftamhar** [comment]
This lib is using pathogen.
This is the answer to [How to update vim plugins with pathogen?](https://vi.stackexchange.com/questions/9767/how-to-update-vim-plugins-with-pathogen-package-manager)

**Comment by amix** [comment]
You can use https://github.com/amix/vimrc#how-to-include-your-own-stuff and my_configs.vim to install anything you like and make it more IDE like.

For example, on my local machine, I am running [jedi-python](https://github.com/davidhalter/jedi-vim). You can install it something like this:
```
cd ~/.vim_runtime
git clone https://github.com/davidhalter/jedi-vim.git my_plugins/jedi-vim
```
