### ISSUE TITLE
Request: adding template `my_configs.vim`

### ISSUE THREAD

**Issue by jamesbraza** [amix/vimrc#739]
It would be nice if this repo came with a template `my_configs.vim`, instead of requiring users to make the file themselves.  That, or beef up the docs on this here: https://github.com/amix/vimrc#how-to-include-your-own-stuff.

For someone who knows `vim`, making a `my_configs.vim` may seem trivial.  For a new (two days) `vim` user like me, who doesn't know about the `.vim` extension, I am having search for examples online like [this one](https://github.com/off99555/vimrc/blob/master/my_configs.vim).

I think adding a starter template of `my_configs.vim` (or better `README` docs) to this repo would speed getting started.

For what it's worth, it seems others were tripped up by this too (https://github.com/amix/vimrc/issues/725, https://github.com/amix/vimrc/issues/618).

**Comment by amix** [comment]
You are welcome to supply a PR that improves the README 😊👍
