### ISSUE TITLE
Problem disabling autocomplete quotation marks and brackets 

### ISSUE THREAD

**Issue by thequinn** [amix/vimrc#742]
I love your Awesome VIM config, and it has been a great experience using it.  The only thing that I really need to disable is the autocomplete function to complete a closing quotation mark and bracket when I insert a left one.  Would you please add the choice or instruction to disable it?  I see many people prefer not to have this function enabled, but they can't figure out how to change the default mapping in the config file, extended.vim.  Thanks a lot!

**Comment by amix** [comment]
In [my_configs.vim](https://github.com/amix/vimrc?tab=readme-ov-file#how-to-include-your-own-stuff) add the following to disable auto pairs:

```vim
let g:AutoPairs = {}
```
