### ISSUE TITLE
Automatic addition of another set of [],{},()

### ISSUE THREAD

**Issue by blubpie** [amix/vimrc#744]
Hello! Very new to this so sorry if this is a dumb question, but whenever I type out any sort of open/close structure, it highlights it purple, and then adds another one right after it when I click space, Ex. int[][], with the first pair of [] being highlighted purple, and the second pair being involuntarily added when I click space.

Thank you!

**Comment by blubpie** [comment]
I just temporarily disabled autopair which works fine, although I don't personally dislike autopair. Another thing that keeps happening is that randomly when I click enter it messes up my syntax leaving white highlighted characters in seemingly arbitrary places and leaving an afterimage of text (not faint, but the text itself is not there and is turned back into what it really is by doing something to refresh the line.

**Comment by amix** [comment]
In general, I would recommend to fork this repo and modify as it fits your style 😊
(if the my_config.vim does not do the job)
