### ISSUE TITLE
Can't Copy To System Clipboard

### ISSUE THREAD

**Issue by rvyhvn** [amix/vimrc#747]
hello, i need help here since i'm new using vim (like 5 months) and not really into configuring vim (editing vimrc, etc.) i tried this tool and it amazes me since i hate using nvim cuz lua and this much better and easier for me. but i can't copy into system clipboard. i tried all solutions in the issue but those solutions didn't work. i'm using KDE on debian. 

here's my `my_configs.vim`
```md
set clipboard=unnamedplus
set mouse-=a
```

i also did `sh install_awesome_vimrc.sh` after adding those lines.
thanks!

**Comment by amix** [comment]
I would recommend looking on the web for help as this is more an issue with VIM, KDE + Debian. An example (using perplexity):
![CleanShot 2024-01-07 at 16 22 39@2x](https://github.com/amix/vimrc/assets/184462/7e29bedb-6d16-422d-91a4-378607068498)

**Comment by rvyhvn** [comment]
Thanks, i forgot this issue was solved by my own self. I think this is Vim's problem bcuz all of my friend that uses Vim felt the same, once i switched to Neovim with your config, clipboard problems are gone.
