### ISSUE TITLE
Weird space at start of each line when copying via mouse

### ISSUE THREAD

**Issue by roupasz** [amix/vimrc#754]
Hi, I'm a huge fan of Awesome Vim and not sure if this an issue to report here or another plugin created this but please bear with me :)

After installing and tweaking my config based on the README , I have this strange behavior where in normal or visual mode text seems fine and not spaces are found in the start of each line
![iTerm2_2024-02-05 15-39-17@2x](https://github.com/amix/vimrc/assets/53302668/88b94e28-470c-49b1-b611-eb89c269fc15)

but when I try to select a block with the mouse, I get this strange extra space in the starting of each line
![Teampaper Snap_2024-02-05 15-39-31@2x](https://github.com/amix/vimrc/assets/53302668/a166629b-8f83-4342-886e-332726558c3b)

which is of course kept while pasting to another application, for example in sublime
![Sublime Text_2024-02-05 15-39-50@2x](https://github.com/amix/vimrc/assets/53302668/40f64a9a-8a83-43ad-8189-28a2fd59ac6f)

For various reasons this is creating issues and was wondering if anyone else is experiencing this or if any plugin created this kind of issue.

Thanks for the patience and help in advance

**Comment by sjoblomj** [comment]
Yes, this seems to be the standard configuration. I assume it's in order to make it a little nicer in the editor.

You can disable this by putting `set foldcolumn=0` in your [`my_configs.vim` file](https://github.com/amix/vimrc#how-to-include-your-own-stuff).

**Comment by roupasz** [comment]
Thanks a lot, this was driving me crazy! 
Adding this option fixed the issue , thanks for taking the time to respond kind stranger
