### ISSUE TITLE
running crontab -e

### ISSUE THREAD

**Issue by tspicer** [amix/vimrc#79]
Using the awesome version

When running crontab -e in CentOS 6.5 the following error happens;

no crontab for root - using an empty one
Error detected while processing /root/.vim_runtime/vimrcs/basic.vim:
line  129:
E518: Unknown option: foldcolumn=1
Error detected while processing /root/.vim_runtime/vimrcs/filetypes.vim:
line   36:
E518: Unknown option: foldmethod=syntax
line   37:
E518: Unknown option: foldlevelstart=1
line   43:
E518: Unknown option: foldtext=FoldText()
line   51:
E518: Unknown option: foldmethod=indent
line   52:
E518: Unknown option: foldlevelstart=1
Error detected while processing /root/.vim_runtime/vimrcs/extended.vim:
line   56:
E518: Unknown option: undodir=~/.vim_runtime/temp_dirs/undodir
line   57:
E518: Unknown option: undofile
Error detected while processing /root/.vimrc:
line    9:
E484: Can't open file /root/.vim_runtime/my_configs.vim
Press ENTER or type command to continue

**Comment by WEI-HE** [comment]
you need to set the editor of crontab obviously.
I fixed this issue, by adding the following code in '~/.bashrc' file.
export EDITOR=vim
