### ISSUE TITLE
possible to resize the gvim(macvim) window to "nofullscreen" at the start?

### ISSUE THREAD

**Issue by Kaijun** [amix/vimrc#83]
i wanna to set the `fullscreen` back to `nofullscreen` without editing your vim configuration. so i have tried overwrite it under my own configuration:

```
set lines=50 columns=50
```
```
set nofu
```

neither of them works...

is it possible to use `nofullscreen` mode without modifying your vim configuration?

**Comment by jokeyrhyme** [comment]
Yeah, I'm having problems with this, too.

**Comment by jokeyrhyme** [comment]
I have my own script that I run after every update that removes the fullscreen settings:

```sh
#!/bin/bash

__dotfiles_remove_line () {
  local TEMP=`mktemp`
  sed "$2" "$1" > "$TEMP"
  mv "$TEMP" "$1"
}

__dotfiles_remove_line ~/.vim_runtime/vimrcs/extended.vim '/set fullscreen/d'
__dotfiles_remove_line ~/.vim_runtime/vimrcs/extended.vim '/set fuoptions/d'
```

**Comment by chuangbo** [comment]
+1

**Comment by amix** [comment]
Great hack @jokeyrhyme
