### ISSUE TITLE
I cannot use vim for editing commit messages

### ISSUE THREAD

**Issue by davidwilde** [amix/vimrc#88]
After installing these extensions to vim, I get the following error when I try to edit COMMIT_EDITMSG. 

error: There was a problem with the editor 'vim'.
Please supply the message using either -m or -F option.

Is this something wrong with my setup?

**Comment by zkamvar** [comment]
I am also having this issue. I'm using the basic setup on OSX 10.10.2

**Comment by ccppjava** [comment]
"Fix"
http://tooky.co.uk/there-was-a-problem-with-the-editor-vi-git-on-mac-os-x/
$ git config --global core.editor /usr/bin/vim

**Comment by zkamvar** [comment]
Thanks! It worked! :+1:

**Comment by khatchad** [comment]
I think you can also set the EDITOR environmental variable to vim.

**Comment by sparcbr** [comment]
if you want to use gvim, use gvim --nofork
