### ISSUE TITLE
mac command+c for copy is not working

### ISSUE THREAD

**Issue by joy32812** [amix/vimrc#98]
mac command+c for copy is not working

**Comment by diegoalberto** [comment]
It's happening the same with ctrl+c or ctrl+ins on kubuntu 14.10 64bit

**Comment by diegoalberto** [comment]
I created and added the following to ~/.vim_runtime/my_configs.vim
<addr>set mouse-=a</addr>

That disabled direct mouse interactions with vim that was messing with visual mode, selecting, copy and paste.

**Comment by scottrice10** [comment]
Thanks @diegoalberto - adding set mouse-=a worked for me on a mac.

**Comment by joy32812** [comment]
Thanks @diegoalberto, It works!!

**Comment by chenqiangzhishen** [comment]
:+1:
